### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by KobaCemal** [Deep-MI/FastSurfer#10]
Hello,

I am trying to run FastSurfer on a single image with this code: 

`./run_fastsurfer.sh --t1 /home/koba/Desktop/sub-001/anat/orig.mgz                     --sid subject1 --sd  /home/koba/Desktop/sub-001/fsout                    --parallel --py python3.7 --batch 2`

The script fills my swap memory after Coronal Testing and stops no matter what. It doesn't return any error codes. If I set the batch size >10, it tells me this: 

`RuntimeError: CUDA out of memory. Tried to allocate 320.00 MiB (GPU 0; 3.95 GiB total capacity; 2.49 GiB already allocated; 163.31 MiB free; 3.04 GiB reserved in total by PyTorch)`

My computer has 16 gb of ram (2 gb swap) and nvidia geforce 1050 gpu ( 4 gb)

Does that mean my computer is just insufficient for the code? Or Am I missing something in the installation?

Thank you very much!

**Comment by LeHenschel** [comment]
Hey,

yes, I think this is most likely a memory problem with your GPU. I am not sure if you tried to set the batch size to 1? In addition you can check if you can run the network on your cpu (add the --no_cuda flag):

`./run_fastsurfer.sh --t1 /home/koba/Desktop/sub-001/anat/orig.mgz --sid subject1 --sd /home/koba/Desktop/sub-001/fsout --parallel --py python3.7 --batch 1 --no_cuda --seg_only` 

Best,
Leonie

**Comment by KobaCemal** [comment]
Hi,

Thank you for your quick response! 

I ran the command you suggested with 16 batches. It has been running for 20 minutes. It occupies 10 gb of ram and 6 processors and still going on. Since it is "segmentation only", I think there is something wrong.  Maybe the computer is not enough for the procedure.

I was going to check myself but since the analysis doesn't finish, I think it is okay to ask here. Do the results require any manual correction like FreeSurfer's results do? I have read your paper and couldn't see any indication of manual correction for FreeSurfer's or FastSurfer's results. Do you think it is safe to skip that part (except the most obvious errors of course)? 

I am asking because I have a large dataset and detailed manual correction is something that I want to avoid. It wouldn't be possible to make healthy judgements on so many subjects. I would be happy to hear your opinion on this.

Thank you!

**Comment by m-reuter** [comment]
You can also try batch 1 and with the GPU. 
About manual correction: for the surface stream, manual edits can be done as in FreeSurfer if desired. Visual inspection of results is always recommended (with any automated software tool as they can all fail especially in the presence of pathologies, motion, low image quality etc.).

**Comment by LeHenschel** [comment]
I am closing this issue for now.

**Comment by tashrifbillah** [comment]
@LeHenschel , I am also experiencing this. I am trying to debug. Before, did you make `--no_cuda` a default for the docker container?

> run --gpus all -v FastSurfer:/root/FastSurfer -v `pwd`:/root/data --rm fastsurfer:gpu --seg /root/FastSurfer/aparc+aseg.mgz --sid 003 --parallel --t1 /root/data/003_T1w_resampled.nii.gz

As you see, I didn't provide `--no_cuda`, yet

```vim
Tue Jul 14 14:11:00 UTC 2020
/fastsurfer/FastSurferCNN /fastsurfer
python3.6 eval.py --in_name /root/data/003_T1w_resampled.nii.gz --out_name /root/FastSurfer/aparc+aseg.mgz --order 1 --network_sagittal_path ../checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path ../checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path ../checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 16 --simple_run
Reading volume /root/data/003_T1w_resampled.nii.gz
Conforming image to UCHAR, RAS orientation, and 1mm isotropic voxels
Input:    min: 0.0  max: 3913.0
rescale:  min: 0.0  max: 3572.569  scale: 0.07137720782999572
Output:   min: 0.0  max: 255.0
Loading Axial
Successfully loaded Image from /root/data/003_T1w_resampled.nii.gz
Loading Sagittal
Successfully loaded Image from /root/data/003_T1w_resampled.nii.gz
Loading Coronal.
Successfully loaded Image from /root/data/003_T1w_resampled.nii.gz
Cuda available: True, # Available GPUS: 1, Cuda user disabled (--no_cuda flag): False, --> Using device: cuda
...
...
```

**Comment by tashrifbillah** [comment]
Never mind, I realized it's just a message:

`Cuda user disabled (--no_cuda flag): False`, the value is `False`. 

To avoid future confusion, I think we need to make the message something like--
`Use Cuda: {False if args.no_cuda else True}`

**Comment by tashrifbillah** [comment]
Hi @KobaCemal , I am facing the same issue. As @m-reuter mentioned, did reducing `--batch` help?

**Comment by KobaCemal** [comment]
Hello @tashrifbillah, I tried --batch 1  but didnt work for me. I  think my personal computer is not strong enough. No-cuda option did take forever, so I had to stop it. How long did it take to process with --no-cuda option in your machine?

**Comment by tashrifbillah** [comment]
> No-cuda option did take forever, so I had to stop it.

Same here, so I had to stop it too!

**Comment by m-reuter** [comment]
Note that CPU processing should be significantly faster now in dev branch thanks to activating denormal flushing #165 and
a7ca03c9e46ea7067a30
