### ISSUE TITLE
Volumetric analysis

### ISSUE THREAD

**Issue by HampaliShamanth** [Deep-MI/FastSurfer#102]
Is there a way to get the volumes (physical) of the rois?

**Comment by LeHenschel** [comment]
Hey, 

with volumes (physical) are you referring to the volume segmentation statistics (aka mm^3 volume measures)? This is possible in two ways:

1. You can run FastSurfer with the --vol_segstats flag: "Additionally return volume-based aparc.DKTatlas+aseg statistics for DL-based segmentation (does not require surfaces). Can be used in combination with --seg_only in which case recon-surf only runs till CC is added (akin to --seg_with_cc_only). " In this case, the segstats are closer to the FreeSurfer provided values, as it includes partial volume correction via the norm.mgz (https://surfer.nmr.mgh.harvard.edu/fswiki/mri_segstats)
2. You can run the mri_segstats command from FreeSurfer on the segmentations directly (see https://github.com/Deep-MI/FastSurfer/issues/26). No further processing is needed, but partial volume correction will not be included.

Best,
Leonie

**Comment by liqingbioinfo** [comment]
Hi  Leonie
     
      I followed your 1st suggestion and added --seg_only --vol_segstats  to get volumetric values for 95 classes. However, your code finished analysis but didn't output aparc.DKTatlas+aseg.deep.volume.stats file. Even though Fastsurfer indicated that the output statistics were in "$SUBJECTS_DIR/$SID/stats/aparc.DKTatlas+aseg.deep.volume.stats", I could not find it. Moreover, there was no folder named stats. Could you please let me know how to solve such an issue? I highly appreciate your help. 
The code that I used to run:
>> FastSurfer/run_fastsurfer.sh --t1 xx_mprage.mgz --sid xx --sd $fastsurferdir --parallel --threads 4 --seg_only --vol_segstats

**Comment by m-reuter** [comment]
Hi liqingbioinfo , 

for --vol_segstats to work you need to have FreeSurfer 7.2 installed and sourced (and the license file from them). What does ` recon-all --version`  give you ?

Also are you using stable or dev version? And can you send the last lines of the `<subjectid>/stats/recon-surf.log` file ?

**Comment by m-reuter** [comment]
Oh and I think that you cannot use `--seg_only` at the same time. If you do, it stops after the segmentation and will not run the first part of recon-surf. So first try to drop that.

**Comment by liqingbioinfo** [comment]
Hi Martin
     
     I really appreciate your help. I removed --seg_only, and I got statistics in stats/ folder. Wonderful! Although I have such statistics, I am still a bit confused about when to use --seg_only. In https://github.com/Deep-MI/FastSurfer/issues/51, Leonie suggested using --seg_only --vol_segstats --fsaparc for volume stats. Can you please elaborate a bit more? 
      Besides, I listed all results below. Should I focus on the 4th column with the header Volume_mm3, right? The 6th to 10th describe image intensity and are not related to volume, right? 

TableCol  1 ColHeader Index 
TableCol  1 FieldName Index 
TableCol  1 Units     NA 
TableCol  2 ColHeader SegId 
TableCol  2 FieldName Segmentation Id
TableCol  2 Units     NA
TableCol  3 ColHeader NVoxels 
TableCol  3 FieldName Number of Voxels
TableCol  3 Units     unitless
TableCol  4 ColHeader Volume_mm3
TableCol  4 FieldName Volume
TableCol  4 Units     mm^3
TableCol  5 ColHeader StructName
TableCol  5 FieldName Structure Name
TableCol  5 Units     NA
TableCol  6 ColHeader normMean 
TableCol  6 FieldName Intensity normMean
TableCol  6 Units     MR
TableCol  7 ColHeader normStdDev
TableCol  7 FieldName Itensity normStdDev
TableCol  7 Units     MR
TableCol  8 ColHeader normMin
TableCol  8 FieldName Intensity normMin
TableCol  8 Units     MR
TableCol  9 ColHeader normMax
TableCol  9 FieldName Intensity normMax
TableCol  9 Units     MR
TableCol 10 ColHeader normRange
TableCol 10 FieldName Intensity normRange
TableCol 10 Units     MR
NRows 100 
NTableCols 10 
ColHeaders  Index SegId NVoxels Volume_mm3 StructName normMean normStdDev normMin normMax normRange

  1   2    244441   247425.8  Left-Cerebral-White-Matter       100.0155    11.4409    18.0000   155.0000   137.0000 
  2   4      5190     5460.8  Left-Lateral-Ventricle            17.5247    15.7788     0.0000    67.0000    67.0000 
  3   5       281      326.1  Left-Inf-Lat-Vent                 35.7758    16.0271     0.0000    76.0000    76.0000 
  4   7     15470    16295.0  Left-Cerebellum-White-Matter      93.4568    11.4313    44.0000   163.0000   119.0000 
  5   8     65770    65457.3  Left-Cerebellum-Cortex            49.9575    15.2294     0.0000   131.0000   131.0000

**Comment by LeHenschel** [comment]
Hey,

 --seg_only and --vol_segstats should run the initial part of the surface pipeline. The following message should be displayed in this case and the segstats should be saved in the indicated file (based on your initial post, I assume you got the message):

> You requested segstats without running the surface pipeline. In this case, recon-surf will run until the corpus callsoum is added to the segmentation and the norm.mgz is generated (needed for partial volume correction). The stats will be stored as (\$SUBJECTS_DIR/\$SID/stats/aparc.DKTatlas+aseg.deep.volume.stats). 

Could you share the output of your log-files? Did the surface pipeline not start at all or was there an error message?

Best,
Leonie

**Comment by m-reuter** [comment]
@LeHenschel  at least in stable seg only prevents recon-surf to be started, so it should not be combined. Haven't checked behavior in dev. 

@liqingbioinfo  yes 4th column , these are standard free surfer stats files. You can extract information across multiple subjects wir asegstats2tabke (or similar, a free surfer python script)

**Comment by LeHenschel** [comment]
@m-reuter In general yes, but not when it is combined with --vol_segstats (see here: https://github.com/Deep-MI/FastSurfer/blob/stable/run_fastsurfer.sh#L332)

Here, we specifically set seg_only=0 and add --seg_with_cc_only, so the surface pipeline will run (or should)

**Comment by m-reuter** [comment]
I think there is a bug in line https://github.com/Deep-MI/FastSurfer/blob/f314b2baa2748f1f1ba751855e853fc1b882d67b/run_fastsurfer.sh#L335 it should be set to "0" and not 0. That is why recon-surf is not called.

**Comment by LeHenschel** [comment]
Jup, you are right. Should be changed to string. I can create a pull request for stable and dev to fix it.

**Comment by LeHenschel** [comment]
Potentially fixed with #184 and #185

**Comment by liqingbioinfo** [comment]
Hi Leonie and Martin
    
    Thanks a million for your help! Does it mean we are good to run fastsurfer with --seg_only and --vol_segstats to get the volumetric values now?

**Comment by m-reuter** [comment]
Yes, if you check out the new version it should not matter anymore if you pass seg_only or not. In both cases it will do the segmentation and then run the recon_surf script up to the point after corpus callosum is added and stats files are created.
