### ISSUE TITLE
Time data does not match format '%b %d %Y %H:%M:%S'

### ISSUE THREAD

**Issue by greydongilmore** [Deep-MI/FastSurfer#103]
## Description

I'm getting a date string error when FastSurfer attempts to parse the recon_surf log file upon completion (see screenshot below).

## Steps to Reproduce

I am running the following command:

```console
export FASTSURFER_HOME=/home/greydon/Documents/GitHub/FastSurfer &&PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:4096 /home/greydon/Documents/GitHub/FastSurfer/run_fastsurfer.sh --t1 /home/greydon/data/data/SEEG/bids/sub-P080/ses-pre/anat/sub-P080_ses-pre_run-01_T1w.nii.gz --sd /home/greydon/data/data/SEEG/derivatives/fastsurfer/sub-P080 --sid fastsurfer --order 0 --py python3 --run_viewagg_on cpu
```
## Screenshots

![153234380-75125c43-d071-4b96-9010-cd6cd6ca4796](https://user-images.githubusercontent.com/26314366/153236795-8f6ccaed-69a5-4fb0-bffa-c2d5f9874e0d.png)

## Environment
 - FastSurfer Version: Master branch
 - FreeSurfer Version: 6.0
 - OS: Pop!_OS 21.10
 - CPU: Intel Core i7-9800X @ 3.80GHz
 - GPU: NVIDIA GeForce RTX 2080

Python modules:
[python_modules.txt](https://github.com/Deep-MI/FastSurfer/files/8033990/python_modules.txt)

### Execution

See above.

## Additional Context

...

**Comment by LeHenschel** [comment]
Hey,

thanks for reporting the issue. @AhmedFaisal95 can you check what is happening here?

**Comment by greydongilmore** [comment]
@AhmedFaisal95 my apologies. Pulling the most recent Master fixes this issue :+1:
