### ISSUE TITLE
How to apply transform?

### ISSUE THREAD

**Issue by jp020202** [Deep-MI/FastSurfer#105]
Running a T1 image through fastsurfer with -- or without -- the --surfreg parameter doesn't seem to do anything - there are no spatially normalized images. I see transforms in the xfm directory, but am uncertain how to apply that. As well, the transforms are there even without the --surfreg parameter! I got no error messages on output.

1. What transform do I use? Presumably the talairach.xfm?
2. How do I apply this to an output image? 

Thanks, James

**Comment by m-reuter** [comment]
Hi James, FreeSurfer and fastsurfer provide results in subject space. You get segmentations and statistics for all structures. Also you can do a cortical surface group analysis with spatial correspondence on the surfaces (eg point wise thickness analysis). All this is described on the FreeSurfer wiki and tutorials and mailing list.

**Comment by jp020202** [comment]
Thank you. I don't really see a whole lot about analysis however, but I think my problem is elsewhere. I'm going to close this one, and open another.
