### ISSUE TITLE
RuntimeError : CUDA out of memory

### ISSUE THREAD

**Issue by wtmccuddy** [Deep-MI/FastSurfer#108]
Hello, 

Looking for any guidance on GPU memory issue. I read all of the resolved comments on the issue and tried reducing batch size to 1 and checking output of nvidia-smi to kill any python processes using up GPU memory (didn't see any extra stuff running to kill; see output below). Reducing batch size did not help. It seems to me that my GPU should have enough memory for this, but maybe I'm wrong. I was able to get code to run on CPU (running now and no errors yet). Any assistance or information on how to resolve GPU memory issues would be appreciated. 

Thanks!

PS: Using linux machine running ubuntu 20.04.4

This is the error:
RuntimeError: CUDA out of memory. Tried to allocate 4.94 GiB (GPU 0; 1.82 GiB total capacity; 6.93 MiB already allocated; 286.31 MiB free; 8.00 MiB reserved in total by PyTorch)

This is the command I used to run and the subsequent output:
`(base) :~/Desktop/Sub001$ run_fastsurfer.sh --t1 /home/Desktop/Sub001//output_VBG/sub-JW001/sub-JW001_T1_nat_4parc.mgz --sid sub-JW001 --sd /home/Desktop/Sub001//output_VBG/sub-JW001/sub-JW001fastsurfer --parallel --fsaparc --threads 8 --fs_license /usr/local/freesurfer/7.2.0/license.txt --py python 
Sun 20 Feb 2022 06:25:59 PM MST

/usr/local/KUL_apps/FastSurfer/FastSurferCNN ~/Desktop/Sub001
python eval.py --in_name /home/Desktop/Sub001//output_VBG/sub-JW001/sub-JW001_T1_nat_4parc.mgz --out_name /home/Desktop/Sub001//output_VBG/sub-JW001/sub-JW001fastsurfer/sub-JW001/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path /usr/local/KUL_apps/FastSurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path /usr/local/KUL_apps/FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path /usr/local/KUL_apps/FastSurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 1 --simple_run --run_viewagg_on gpu
Reading volume /home/Desktop/Sub001//output_VBG/sub-JW001/sub-JW001_T1_nat_4parc.mgz
Cuda available: True, # Available GPUS: 1, Cuda user disabled (--no_cuda flag): False, --> Using device: cuda
Traceback (most recent call last):
  File "/usr/local/KUL_apps/FastSurfer/FastSurferCNN/eval.py", line 462, in <module>
    fastsurfercnn(options.iname, options.oname, use_cuda, small_gpu, logger, options)
  File "/usr/local/KUL_apps/FastSurfer/FastSurferCNN/eval.py", line 301, in fastsurfercnn
    pred_prob = torch.zeros((256, 256, 256, args.num_classes_ax_cor), dtype=torch.float).to(device)
RuntimeError: CUDA out of memory. Tried to allocate 4.94 GiB (GPU 0; 1.82 GiB total capacity; 6.93 MiB already allocated; 286.31 MiB free; 8.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
'
This is the output for nvidia-smi:
'      
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T400         On   | 00000000:21:00.0  On |                  N/A |
| 38%   32C    P8    N/A /  31W |    239MiB /  2048MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1094      G   /usr/lib/xorg/Xorg                 65MiB |
|    0   N/A  N/A    457378      G   /usr/lib/xorg/Xorg                112MiB |
|    0   N/A  N/A    457551      G   /usr/bin/gnome-shell               53MiB |
+-----------------------------------------------------------------------------+
`

**Comment by m-reuter** [comment]
Hi, your card, the NVIDIA T400 has only 2GB RAM (also stated by nvidia-smi: 2048MiB, out of which already 238MiB are used mainly by Xorg). This is not enough. 

@LeHenschel  or @AhmedFaisal95 can you update the README with memory requirements (with and without GPU view-aggregation and also how far batch size can help reduce mem requirement). There should be info on:
- optimal GPU memory requirement (to run everything on the GPU)
- minimal GPU memory requirement (when reducing batch size and performing view-aggreation on CPU)
- below that everything needs to be switched to CPU

**Comment by m-reuter** [comment]
I am re-opening this issue as we want to include the memory requirments information to the README for an upcoming majro release.

**Comment by knutj** [comment]
I have been able to use cuda when running with --run_viewagg_on cpu

**Comment by m-reuter** [comment]
Hi knutj on what hardware? Also T400 with 2gb?

**Comment by m-reuter** [comment]
Added recommended and minimal requirements to README in commit 1aa43feda
More details will follow later.

**Comment by knutj** [comment]
I have a Geforce 3070 with 8G ram.

**Comment by m-reuter** [comment]
Then you should be able to run also view-aggregation on GPU with batch size 1, strange. Maybe a lot of other stuff was using you GPU memory.
