### ISSUE TITLE
Why GPU is not detected?

### ISSUE THREAD

**Issue by zhould1990** [Deep-MI/FastSurfer#11]
Hello, 

I used the following command to run a test case:

**./run_fastsurfer.sh --t1 $datadir/P008/P008_T1_mri_orig.mgz \
                                 --sid P008 --sd $fastsurferdir**

But no GPU is used when the program is running. I have several GPUs available, the recon-all.log file shows:
**Cuda available: False, # Available GPUS: 0, Cuda user disabled (--no_cuda flag): False, --> Using device: cpu**

Does anyone know why this happens?
Thanks.

**Comment by LeHenschel** [comment]
Hey,

it looks like pytorch is not recognizing your GPUs. Can you post the output of `nvidia-smi` and the pytorch version you used? I suspect it has to do with the CUDA version or drivers etc. 

In addition, you can test if the FastSurferCNN docker is working for you.

Best,
Leonie

**Comment by tashrifbillah** [comment]
@LeHenschel , I am going to Google but I have a different GPU discovery error:

```vim
[root@pnl-z840-2 fs_test]# docker run --gpus all -v FastSurfer2:/root/FastSurfer2 -v `pwd`:/root/data --rm fastsurfer:gpu --seg /root/FastSurfer/aparc+aseg.mgz --sid 003 --parallel --t1 /root/data/003_T1w_resampled.nii.gz
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

Checking with you in case you know a potential solution.

**Comment by LeHenschel** [comment]
Hey @tashrifbillah,

looks like the nvidia-toolkit might be missing (see: https://github.com/NVIDIA/nvidia-docker/issues/1034).

Best,
Leonie

**Comment by tashrifbillah** [comment]
Right! People can navigate from that issue or just do--

https://nvidia.github.io/nvidia-container-runtime/
and then
https://github.com/NVIDIA/nvidia-docker/issues/1034#issuecomment-595513496

**Comment by LeHenschel** [comment]
Ok, thanks for the pointers. I am closing this issue for now then.
