### ISSUE TITLE
cross-subject correspondence

### ISSUE THREAD

**Issue by rafaloz** [Deep-MI/FastSurfer#110]
## Question/Support Request

First of all, thanks for your work! this is a very useful tool for all the community. A lot of time will be saved because of this. 
My aim is to use FastSurfer as a segmentation and feature extraction procedure for a brain age model. However, I am not sure if I require cross-subject correspondence. 

I understand that it is required for vertex-wise comparison but I haven't ever worked with vertex-wise comparison. From what I understand Spherical atlas registration would register the segmented cortex ROIs to an inflated atlas and create a correspondence among cases. So, is it similar to registering an atlas as a common space? Therefore, the features calculated after spherical atlas registration could be considered as "normalized" while previously calculated features are not? is there any documentation about that step you could refer me to?

Thanks again!

**Comment by m-reuter** [comment]
Hi rafaloz, 

If you only want to use the stats ( eg, region based volume, avg thickness or area) you do not need the spherical registration. It is used to construct point-wise correspondence for vertex wise thickness analysis.

**Comment by rafaloz** [comment]
Thank you very much!
