### ISSUE TITLE
thalamic nuclei segmentation in FastSurfer

### ISSUE THREAD

**Issue by vinkirk** [Deep-MI/FastSurfer#111]
## Question/Support Request

Hi,

Is it possible to use the thalamic segmentation script in Freesurfer to segment thalamic nuclei from the Fastsurfer directory? 

Thanks,

Vinny

**Comment by m-reuter** [comment]
HI Vinny, 

we haven't tested that, but it is likely that it just works, since we provide basically all FreeSurfer files that may be necessary. Other pipelines have been tested and we plan to document what works (hopefully all add-ons: hippo, brainstem, thalamic). 

So just try out and let us know. We will also try this.

**Comment by vinkirk** [comment]
Thanks, I'll install FastSurfer and will give it a try.

**Comment by m-reuter** [comment]
It probably needs wmparc.mgz which is not created in the default stream (as we use FastSurferCNN's DKT ATlas based cortical GM segmentation and generate a WM segmentation from that, which has the name "mapped" in it), this should be fixable via creating a symlink:

`ln -s wmparc.mapped.mgz wmparc.mgz`

**Comment by vinkirk** [comment]
Thanks for the tip.  I'll try first with the default outputted file structure, and if it doesn't work, will create the symlink.  Will update on how this goes.

**Comment by vinkirk** [comment]
I was to run FastSurfer without a problem.  However, I realized that FastSurfer requires FreeSurfer v6 stable release whereas the thalamic segmentation script ships with only Freesurfer version 7 and later.  I use FreeSurfer v7.2 and copied the thalamic seg script into the FS v6.0.1 bin folder (don't know if this is the correct thing to do), created the sym link in the FastSurfer output/mri folder, but get the following message:

_Error using SegmentThalamicNuclei (line 158)
Provided atlas mesh file does not exist_

Thanks

**Comment by m-reuter** [comment]
it should not matter that FastSurfer is (currently still) based on FreeSurfer 6.0. 
For the postprocessing you can simply source FreeSurfer 7.2 and run the thalamic seg add-on.

**Comment by vinkirk** [comment]
Thank you, this worked perfectly.

**Comment by m-reuter** [comment]
I will keep this open until:
- it is documented in the README what pipelines work after FastSurfer and how to make it work
- it is decided if we automatically create all necessary symbolic links (I think we should) and until this is implemented
(probably will be in release 1.1)

**Comment by vinkirk** [comment]
That's a great idea, thanks again for your help.

**Comment by m-reuter** [comment]
fixed by #121 now creating symlinks by default.
