### ISSUE TITLE
fastsurferCNN eval.py memory usage

### ISSUE THREAD

**Issue by BBBBryanPan** [Deep-MI/FastSurfer#12]
Hi,
I downloaded your code and tried to run eval.py in fastsurferCNN folder with this command
`python eval.py --i_dir 'adni' --o_dir output --in_name 1.nii --order 1 --batch_size 1 --simple_run false` 
our computer has 32GB ram and our GPU is 11GB 2080ti. 
Before running the code, I check the free memory is 28GB. Before running
`_, prediction_image = torch.max(torch.add(torch.mul(torch.add(prediction_probability_axial,
                                                                  prediction_probability_coronal), 0.4),
                                              torch.mul(prediction_probability_sagittal, 0.2)), 3)`
the free memory is 8GB and then the script exit unexpectedly with no warning. 
I also separate the code into 4 sentence. After running 
`a= torch.add(prediction_probability_axial, prediction_probability_coronal)`
the free memory is 2.6GB. And exit dealing with the `b = torch.mul(a,0.4)`. 
I believe it should be a problem with the memory, and it's very similar with Issue #2.

**Comment by LeHenschel** [comment]
Hey,

I will have a look at it, but it is possible that the view aggregation does indeed need a lot of CPU memory due to the large number of feature maps (95 classes).

Best,
Leonie

**Comment by BBBBryanPan** [comment]
Thanks a lot. And may I ask how many memory at least is required to run fastsurferCNN/eval.py for one image with size like (179x256x256)?

**Comment by m-reuter** [comment]
Your RAM should be sufficient (at least if you run step i CNN segmentation on the GPU, where you might need to reduce batch size, e.g. try 8). On our GPU it takes 40 sec with 8GB RAM (RTX 2080). For the part ii, 32 Gig CPU RAM should really be enough.

**Comment by BBBBryanPan** [comment]
OK, thanks, I'll try that. Another thing is that does your network support nifti format input? We use nifti format to store our brain mri images.

**Comment by LeHenschel** [comment]
Hey,

yes, nifti format is supported as well (see also #20 ). 

Best,
Leonie

**Comment by BBBBryanPan** [comment]
Hey,
I just find out a solution to decrease the memory spending.  Since 3 variable：`prediction_probability_axial，prediction_probability_coronal， prediction_probability_sagittal` is no longer used after 
`_, prediction_image = torch.max(torch.add(torch.mul(torch.add(prediction_probability_axial, prediction_probability_coronal), 0.4), torch.mul(prediction_probability_sagittal, 0.2)), 3)`
We can use 
`
a = torch.add(prediction_probability_axial, prediction_probability_coronal)
del prediction_probability_axial,prediction_probability_coronal
`
to save the memory used by the two variables. From my experience, this step save 5GB memory and the script will fit in well with 32GB ram system. 

Best,
Boyang

**Comment by LeHenschel** [comment]
Hey Boyang,

thank you :). I added the change with commit 25609f2. In total, this makes the view aggregation slightly slower (2-4 s on average on my machine).  I would however consider this as tolerable given that it assures usage on the 32GB ram system.

Best,
Leonie
