### ISSUE TITLE
Do you have the docker image?

### ISSUE THREAD

**Issue by tashrifbillah** [Deep-MI/FastSurfer#13]
Hi, do you guys distribute the docker image? I couldn't find/pull `fastsurfer:gpu`. I can build the image but it would be convenient to use one that you might have hosted somewhere.

**Comment by LeHenschel** [comment]
Hey,

we are going to put the docker images on docker hub soon. I will let you know once they are available.

Best,
Leonie

**Comment by m-reuter** [comment]
In case anyone finds this, here are the docker images:

https://hub.docker.com/r/deepmi/fastsurfer/tags
