### ISSUE TITLE
ERROR: Flag --mc unrecognized.

### ISSUE THREAD

**Issue by tashrifbillah** [Deep-MI/FastSurfer#14]
I tried to follow [this](https://github.com/Deep-MI/FastSurfer/tree/master/Docker#example-1-build-gpu-fastsurfer-container-default) example but the following flags are not accepted by `docker run --rm fastser:gpu`

> --mc --qspec -nofsaparc

**Comment by LeHenschel** [comment]
Hey,

sorry, my bad. I changed the default flags last week and forgot to update the docker README.md . Just omit these flags (--mc --qspec and --nofsaparc are now run by default, and the switch flags are --fstess (alternative to marching cube) --fsqsphere (alternative to qspec) and --fsaparc (alternative to --nofsaparcc)).

Best,
Leonie

**Comment by LeHenschel** [comment]
I updated the Docker README accordingly.

**Comment by tashrifbillah** [comment]
Closed via https://github.com/Deep-MI/FastSurfer/commit/8f66168ddd0f59681aa53ecde0ab55f2af968d56
