### ISSUE TITLE
Cannot find FreeSurfer license (Docker on Windows)

### ISSUE THREAD

**Issue by paulroeppenack** [Deep-MI/FastSurfer#161]
## Question/Support Request
Hi, 
I appear to have a problem finding the FreeSurfer license with a docker installation. I've put the license in the suggested folder structure ("home/user/my_fs_license_dir") under which path I can find and open it through ls / cat. However, when I try to run:
 
```
docker run -v /home/user/my_mri_data:/data \
           -v /home/user/my_fastsurfer_analysis:/output \
           -v /home/user/my_fs_license_dir:/fs60 \
           --rm --user 1000 fastsurfer:cpu \
           --fs_license /fs60/.license \
           --t1 /data/subject2/orig.mgz \
           --no_cuda \
           --sid subject2 --sd /output \
           --parallel
```

I get: 

> Provided FreeSurfer license file /fs60/.license could not be found. Make sure to provide the full path and name. Exiting... 

I use the docker version on win10 with wsl2 with ubuntu 20.04 (also tried with ubuntu 22.04, same error) made with: 

`docker build --rm=true -t fastsurfer:cpu -f ./Docker/Dockerfile_CPU .`

Where did I go wrong? 
(Also, this is the first time that I use docker/ubuntu/wsl2, so the problem might me really trivial)

Thanks!

**Comment by m-reuter** [comment]
Hi, 
you need to specify the full path to the directories on your host system. Is the command above the one you are trying to run? It should look more like:
```
docker run -v c:/full/path/to/my_mri_data:/data \
           -v c:/full/path/to/my_fastsurfer_analysis:/output \
           -v c:/full/path/to/my_fs_license_dir:/fs60 \
          ...
```
The -v command maps a full path on your host system (and for windows this includes the letter of the drive, here c:, could also be d: etc if your data resides on a different drive). So it is -v <global_host_path>:<global_path_inside_docker>. 
I have never used Docker on Windows, and think you also need to enable the C drive in the GUI so that it is accessible?

You can test if your mounting works at all with:
```
docker run -v c:/Users:/data alpine ls /data
```
which starts a small alpine image and lists the content of /data which should be linked to c:/Users on the host. But there could be all kinds of problems with missing credentials of the user to even see some of the directories on windows.

**Comment by paulroeppenack** [comment]
So, I've played around a bit and I think using "/mnt/c/..." does the trick, e.g.:

`docker run -v /mnt/c/users:/data alpine ls /data`

gives me a list of files in my users folder. 

Similarly, if I try the same to find the license, as in: 

`docker run -v /mnt/c/fastsurfer/my_fs_license_dir:/fs60 alpine ls /fs60`

it gives me the license file.

However, if I try to apply that to the command to run a segmentation:
```
docker run -v /mnt/c/fastsurfer/my_mri_data:/data \
           -v /mnt/c/fastsurfer/my_fastsurfer_analysis:/output \
           -v /mnt/c/fastsurfer/my_fs_license_dir:/fs60 \
           --rm --user 1000 fastsurfer:cpu \
           --fs_license /fs60/.license \
           --t1 /data/subject2/orig.mgz \
           --no_cuda \
           --sid subject2 --sd /output \
           --parallel
```

I again receive 

> Provided FreeSurfer license file /fs60/.license could not be found. Make sure to provide the full path and name. Exiting...

**Comment by m-reuter** [comment]
OK, you can try to see if you have access to the .license file: 
`docker run -v /mnt/c/fastsurfer/my_fs_license_dir:/fs60 alpine cat /fs60/.license`

Also try changing the name of the path inside the docker, like so (although the fs60 should also work): 
```
docker run -v /mnt/c/fastsurfer/my_mri_data:/data \
           -v /mnt/c/fastsurfer/my_fastsurfer_analysis:/output \
           -v /mnt/c/fastsurfer/my_fs_license_dir:/fs_license \
           --rm --user 1000 fastsurfer:cpu \
           --fs_license /fs_license/.license \
           --t1 /data/subject2/orig.mgz \
           --no_cuda \
           --sid subject2 --sd /output \
           --parallel
```

**Comment by LeHenschel** [comment]
If it is a permission issue, you might also try to run the command without the --user flag or create and interactive docker.

```
docker run -v /mnt/c/fastsurfer/my_mri_data:/data \
           -v /mnt/c/fastsurfer/my_fastsurfer_analysis:/output \
           -v /mnt/c/fastsurfer/my_fs_license_dir:/fs60 \
           --rm fastsurfer:cpu \
           --fs_license /fs60/.license \
           --t1 /data/subject2/orig.mgz \
           --no_cuda \
           --sid subject2 --sd /output \
           --parallel
```

I just build the container and checked it on my machine and did not receive any error. Is your license file called .license (sometimes it is called license.txt or sth else)? Can you show the result of `dir /mnt/c/fastsurfer/my_fs_license_dir` to make sure this is not an issue with the naming convention?

**Comment by paulroeppenack** [comment]
Hi,

thanks for your replies!

> Is your license file called .license (sometimes it is called license.txt or sth else)

I think that's the problem. The license file is license.txt (as provided from freesurfer, in the mail they also mentioned to save it as "license.txt"). 

I naively tried saving it as "license.license" and "license.lic" but neither could be accessed with 
`docker run -v /mnt/c/fastsurfer/my_fs_license_dir:/fs60 alpine cat /fs60/.license`
-->
> cat: can't open '/fs60/.license': No such file or directory


Running the command without the user flag resulted in the same error as always (no matter which of the "license versions" was provided).

**Comment by LeHenschel** [comment]
Ok, I see. Just change the .license to license.txt or whatever name you used to store the file and you should be fine. It does not have to be named .license :).

The --fs_license flag just needs to point to an existing file downloaded from the FreeSurfer page. The name does not matter. I think we should update the documentation to license.txt to avoid future confusion @m-reuter.

**Comment by paulroeppenack** [comment]
Oh sorry, I phrased that badly. I've tried everything before your last answer
(`I just build the container and checked it on my machine and did not receive any error. Is your license file called .license (sometimes it is called license.txt or sth else)? Can you show the result of dir /mnt/c/fastsurfer/my_fs_license_dir to make sure this is not an issue with the naming convention?`)
with the original file downloaded from FreeSurfer (license.txt), which did not work. Then, after your answer, changed it to "license.license", which also did not work. The output is always

> Provided FreeSurfer license file /fs60/.license could not be found. Make sure to provide the full path and name. Exiting...

no mater if the original "license.txt" or "license.license" is provided.

**Comment by m-reuter** [comment]
I changed the readmes to license.txt.

About your issue. What happens if you store the file as license.txt and run:

`docker run -v /mnt/c/fastsurfer/my_fs_license_dir:/fs alpine cat /fs/license.txt`

It should print the contents of the license file.

**Comment by paulroeppenack** [comment]
> I changed the readmes to license.txt.
> 
> About your issue. What happens if you store the file as license.txt and run:
> 
> `docker run -v /mnt/c/fastsurfer/my_fs_license_dir:/fs alpine cat /fs/license.txt`
> 
> It should print the contents of the license file.

Yes, it does.

**Comment by m-reuter** [comment]
Great, then try this:

```
docker run -v /mnt/c/fastsurfer/my_mri_data:/data \
           -v /mnt/c/fastsurfer/my_fastsurfer_analysis:/output \
           -v /mnt/c/fastsurfer/my_fs_license_dir:/fs \
           --rm fastsurfer:cpu \
           --fs_license /fs/license.txt \
           --t1 /data/subject2/orig.mgz \
           --no_cuda \
           --sid subject2 --sd /output \
           --parallel
```

Once this works you can stop it and can try specifying the correct user ID of your user via the --user flag, so that all output is also written as your user. 

If it does not work, try saving the license file again form the email (maybe it got corrupted).

**Comment by paulroeppenack** [comment]
Ok, I've tried that, no more errors concerning the license. However, now I get : 

> ERROR: T1 image (/data/subject2/orig.mgz) could not be found. Must supply an existing T1 input (conformed, full head) via --t1 (absolute path and name).

The data I provided is the 140_orig.mgz file, which is I believe a FreeSurfer example dataset?

As a side note, I really appreciate you taking the time to walk me through this in such detail, thank you!

**Comment by m-reuter** [comment]
It cannot find your input T1 file. So probably something is wrong with the path there, or the file is missing or you are specifying a wrong file name.
Make sure on your machine the file `/mnt/c/fastsurfer/my_mri_data/subject2/orig.mgz` exists and is readable.

**Comment by paulroeppenack** [comment]
Oh, my bad, downloaded it again, now it works!

Regarding this:
`Once this works you can stop it and can try specifying the correct user ID of your user via the --user flag, so that all output is also written as your user.`

Does this refer to this line?
` --rm --user 1000 fastsurfer:cpu \`

So I should run the command like this?
```
docker run -v /mnt/c/fastsurfer/my_mri_data:/data \
           -v /mnt/c/fastsurfer/my_fastsurfer_analysis:/output \
           -v /mnt/c/fastsurfer/my_fs_license_dir:/fs \
           --rm --user 1000 fastsurfer:cpu \
           --fs_license /fs/license.txt \
           --t1 /data/subject2/orig.mgz \
           --no_cuda \
           --sid subject2 --sd /output \
           --parallel
```
This also appears to be working right now.

**Comment by m-reuter** [comment]
yes, it refers to the `--user 1000` part. Not sure what this value should be on Windows. On linux it is the numerical ID for your user (as obtained via `getent passwd <username>` ). On windows you cannot run docker directly, but instead it is run from inside a virtual machine with linux. Not sure how the user mapping works there. So try if you can read the output images.

**Comment by paulroeppenack** [comment]
Quick update: I've tried it now with the test dataset and everything worked smoothly. Thank you for your detailed help, much appreciated!
