### ISSUE TITLE
Confusing Error Message for missing T1 when running --surf_only

### ISSUE THREAD

**Issue by LeHenschel** [Deep-MI/FastSurfer#162]
## Documentation

Running the run_fastsurfer.sh command with the --surf_only option without specifying the --conformed_name flag can lead to a misleading error message. 

Example command:
```
docker run -v /freesurfer_dir/fs60:/fs60 -v /home/user/Test/data:/data --rm --user $(id -u):$(id -g) fastsurfer:cpu --fs_license /fs60/.license --t1 /data/bert.nii.gz --sid berty --seg /data/bert/aparc.DKTatlas+aseg.deep.mgz --surf_only --sd /data
```

By default, --conformed_name is set to mri/orig.mgz. With --surf_only, recon_surf.sh is called and the image specified under --conformed_name from run_fastsurfer is passed forward as T1. When the orig.mgz is, however, in a different directory for whatever reason, the script will produce the following error:

```
ERROR: T1 image (/data/berty/mri/orig.mgz) could not be found. Must supply an existing T1 input (conformed, full head) via --t1 (absolute path and name).
```

This can be confusing, as the error is not from the --t1 flag in the initial command, but from the missing specification of the --conformed_name flag. 

Non-error command:
```
docker run -v /freesurfer_dir/fs60:/fs60 -v /home/user/Test/data:/data --rm --user $(id -u):$(id -g) fastsurfer:cpu --fs_license /fs60/.license --t1 /data/bert.nii.gz --sid berty --conformed_name /data/bert/mri/orig.mgz --seg /data/bert/aparc.DKTatlas+aseg.deep.mgz --surf_only --sd /data
```

Proposition: Check if --conformed_name image exist in run_fastsurfer.sh when --surf_only is set and produce a more descriptive error message

```
ERROR: Specified to run surface pipeline only (--surf_only), but conformed T1 image (/data/berty/mri/orig.mgz) could not be found. Must supply an existing conformed T1 input  via --conformed_name (absolute path and name) to run the surface pipeline only. Default: $sd/$sid/mri/orig.mgz.
```

**Comment by m-reuter** [comment]
makes sense. please generate a pull request to dev. Since it is not really a bug, we can include this into the new release and need no hotfix to stable.

**Comment by LeHenschel** [comment]
Updated in pull request #163
