### ISSUE TITLE
Improving CPU inference time

### ISSUE THREAD

**Issue by pbou** [Deep-MI/FastSurfer#165]
I've noticed that the inference time using CPU is quite slow. A simple fix is to add `torch.set_flush_denormal(True)` for CPU inference. This sets to zero floating point values that are extremely small, resulting in massive speed-up with minimal loss of precision.
In my limited tests on a couple of images, it reduced the inference time from 85minutes to 11minutes with no difference in the segmentation output.

**Comment by m-reuter** [comment]
Wow, that's an improvement. Thanks for the great idea. We will test that.

**Comment by LeHenschel** [comment]
Thanks a lot for the suggestion. The denormal flushing was now added to FastSurferCNN in #171
