### ISSUE TITLE
recon-surf.sh stops because of unbound variables

### ISSUE THREAD

**Issue by themeo** [Deep-MI/FastSurfer#166]
## Description
`recon-surf.sh` script stops at 2 different points complaining about an unbound variable. 

## Steps to Reproduce
I'm already after the segmentation step. I run:
`./run_fastsurfer.sh --sid sub-s06 --sd dir1 --t1 dir2/sub-s06_acq-t1mprage_run-1_T1w.nii.gz --parallel --threads 4 --surf_only`

The script immediately breaks with the following error:
> ./recon-surf.sh: line 260: POSITIONAL[@]: unbound variable

If I comment out the respective line, it breaks again some time later:
> RunBatchJobs: Logfile: dir1/scripts/recon-surf.log
> RunBatchJobs: CMDF: dir1/scripts/lh.processing.cmdf
> ./recon-surf.sh: line 129: PIDS[@]: unbound variable

## Environment
 - FastSurfer Version: 1.1.0 (installed via `pip`)
 - OS: CentOS Linux 7 (Core)

Run Command: `./run_fastsurfer.sh --sid sub-s06 --sd dir1 --t1 dir2/sub-s06_acq-t1mprage_run-1_T1w.nii.gz --parallel --threads 4 --surf_only`

**Comment by LeHenschel** [comment]
Hey, can you uncomment this line https://github.com/Deep-MI/FastSurfer/blob/stable/recon_surf/recon-surf.sh#L18 and see if it runs through?

**Comment by themeo** [comment]
It was uncommented, I commented it and now everything works like a charm. Thanks!

**Comment by LeHenschel** [comment]
Great :) 

@m-reuter maybe we should remove this line. The check does not seem useful to me, rather the opposite (have also had some problems with it before). Or is there any advantage I overlook?

opened a pull request #167

**Comment by m-reuter** [comment]
agreed
