### ISSUE TITLE
Error:  unable to find "./run_fastsurfer.sh" (GPU, Docker on Windows)

### ISSUE THREAD

**Issue by paulroeppenack** [Deep-MI/FastSurfer#169]
Hi,

when I try to run 

```

docker run --gpus all -v /mnt/c/fastsurfer/my_mri_data:/data \
           -v /mnt/c/fastsurfer/my_fastsurfer_analysis:/output \
           -v /mnt/c/fastsurfer/my_fs_license_dir:/fs \
           --rm --user 1000 fastsurfer:gpu \
           --fs_license /fs/license.txt \
           --t1 /data/subject2/orig.nii \
           --sid subject2 --sd /output \
           --parallel

```

I get the error message:

> docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./run_fastsurfer.sh": stat ./run_fastsurfer.sh: no such file or directory: unknown.
> 

I used the docker version on win10 with wsl2 and ubuntu 20.04

The same error also occurs when I try to run the CPU version, which is curious as it worked fine before I've installed my new GPU. 

The GPU appears to be connected and working, this is the output from nvidia-smi:

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 515.48.07    Driver Version: 516.40       CUDA Version: 11.7     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
> |  0%   51C    P8    15W / 170W |   1222MiB / 12288MiB |      2%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+

and a quick benchmarking gives me this:

> > Compute 8.6 CUDA device: [NVIDIA GeForce RTX 3060]
> 28672 bodies, total time for 10 iterations: 26.053 ms
> = 315.542 billion interactions per second
> = 6310.834 single-precision GFLOP/s at 20 flops per interaction
> 

Any ideas how this could be fixed?
Thanks!

**Comment by LeHenschel** [comment]
Did you build the docker yourself and if so can you provide the command with which you did it? Which version of FastSurfer (newest v1.1.0)?

Do you also get the error when you pull the official image from the repository (docker pull deepmi/fastsurfer:gpu-v1.1.0)?

**Comment by paulroeppenack** [comment]
I've used 
`docker build --rm=true -t fastsurfer:gpu -f ./Dockerfile .`
for the build. I assume this gets the newesest version?

I'll try again after `docker pull deepmi/fastsurfer:gpu-v1.1.0` is done installing.

**Comment by LeHenschel** [comment]
From the command it looks like you ran it from inside the Docker directory. The command needs to be executed from the parent directory (FastSurfer). That is probably why the files were not copied into the docker and run_fastsurfer.sh does not exist (this is the relevant line in the Dockerfile: https://github.com/Deep-MI/FastSurfer/blob/stable/Docker/Dockerfile#L90).

This should give you a  working docker (see also example 1 in the [Docker README](https://github.com/Deep-MI/FastSurfer/tree/stable/Docker#example-1-build-gpu-fastsurfer-container-default)):
```
cd $FASTSURFER_DIR
docker build --rm=true -t fastsurfer:gpu -f ./Docker/Dockerfile .
```

**Comment by paulroeppenack** [comment]
Oh I see, thanks!
That fixed the error.

However, after running it, I get different error: 

> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/THCGeneral.cpp line=371 error=48 : no kernel image is available for execution on the device
> Traceback (most recent call last):
>   File "eval.py", line 483, in <module>
>     fastsurfercnn(options.iname, options.oname, options.conformed_name, use_cuda, small_gpu, logger, options)
>   File "eval.py", line 318, in fastsurfercnn
>     params_model, model, logger, gpu_small)
>   File "eval.py", line 213, in run_network
>     temp = model(images_batch)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/fastsurfer/FastSurferCNN/models/networks.py", line 69, in forward
>     encoder_output1, skip_encoder_1, indices_1 = self.encode1.forward(x)
>   File "/fastsurfer/FastSurferCNN/models/sub_module.py", line 267, in forward
>     out_block = super(CompetitiveEncoderBlockInput, self).forward(x)  # To be concatenated as Skip Connection
>   File "/fastsurfer/FastSurferCNN/models/sub_module.py", line 191, in forward
>     x0 = self.conv0(x0_bn)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 343, in forward
>     return self.conv2d_forward(input, self.weight)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Which looks very similar to what was posted in #68. Should the same fix work here?

**Comment by LeHenschel** [comment]
Potentially yes, but it is a bit surprising because the newest docker has been upgraded to pytorch 1.10 and cuDNN 11.3 (https://github.com/Deep-MI/FastSurfer/blob/stable/fastsurfer_env_gpu.yml#L12). 

Can you confirm that these are the packages installed inyour docker? And have you tested if your GPU set-up works in general with pytorch?

Edit: I checked the Nvidia pages and it might be that your driver does not support cuDNN 11.3. If you upgrade to 11.7 it should work (same way as explained in the other issue). However, it seems like so far there is no pytorch support for this cuda version (https://github.com/pytorch/builder/issues/1042). 

So in case you have pytorch 1.10 and cuDNN 11.3 installed and this still gives the above error, you have two options:
1. Build pytorch from source with cuDNN11.7
2. Downgrade your driver to a version supporting the older 11.3 cuDNN version (https://docs.nvidia.com/deploy/cuda-compatibility/index.html#use-the-right-compat-package)

**Comment by paulroeppenack** [comment]
Hi,

> Can you confirm that these are the packages installed inyour docker?

I'm not totally sure how to do this. Maybe to clarify what I've did: 

I've downloaded the fastsurfer repository from github and put those files into my wsl2 environment. 
Then in ubuntu navigated to the fastsurfer folder and executed 
`docker build --rm=true -t fastsurfer:gpu -f ./Docker/Dockerfile .`

And when I take a look in the "Dockerfile" it starts off with : 

> FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu16.04
> ENV LANG=C.UTF-8
> ARG PYTHON_VERSION=3.6

and further below: 

>  /opt/conda/bin/conda install -y -c pytorch cudatoolkit=10.0 "pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0" torchvision=0.4.0 && \

I've also tried to use 
`docker pull deepmi/fastsurfer:gpu-v1.1.0`
Which produces a different image (I think? The size is different atleast.)
However, when I try to run 
```
docker run --gpus all -v /mnt/c/fastsurfer/my_mri_data:/data \
           -v /mnt/c/fastsurfer/my_fastsurfer_analysis_5:/output \
           -v /mnt/c/fastsurfer/my_fs_license_dir:/fs \
           --rm --user 1000 fastsurfer:gpu \
           --fs_license /fs/license.txt \
           --t1 /data/subject2/orig.nii \
           --sid subject2 --sd /output \
           --parallel
```
It doesn't find the image. 

> Unable to find image 'fastsurfer:gpu' locally
> docker: Error response from daemon: pull access denied for fastsurfer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.

But it does show up when I use "docker images".

**Comment by LeHenschel** [comment]
Oh, ok. This clarifies things.

>  And when I take a look in the "Dockerfile" it starts off with: 
> FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu16.04
> ENV LANG=C.UTF-8
> ARG PYTHON_VERSION=3.6
> 
> and further below:
> 
> /opt/conda/bin/conda install -y -c pytorch cudatoolkit=10.0 "pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0" torchvision=0.4.0 && \

The Dockefile you used is v1.0.0 which still uses the old pytorch and cuda toolkit. That is why you see the CUDA error.  In v1.1.0 (current stable version) the dockerfiles were updated and contain the newer pytorch version. This is also the case for the one you pulled from docker hub.

> Which produces a different image (I think? The size is different atleast.)

Yes! It is the new 1.1.0 version and is the one that should work with your GPU.

> However, when I try to run
> 
> docker run --gpus all -v /mnt/c/fastsurfer/my_mri_data:/data \
>            -v /mnt/c/fastsurfer/my_fastsurfer_analysis_5:/output \
>            -v /mnt/c/fastsurfer/my_fs_license_dir:/fs \
>            --rm --user 1000 fastsurfer:gpu \
>            --fs_license /fs/license.txt \
>            --t1 /data/subject2/orig.nii \
>            --sid subject2 --sd /output \
>            --parallel
> It doesn't find the image.
> 
> Unable to find image 'fastsurfer:gpu' locally
> docker: Error response from daemon: pull access denied for fastsurfer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.
> 
> But it does show up when I use "docker images".

The problem here is, that the image is stored under the pull name: deepmi/fastsurfer:gpu-v1.1.0. So if you change your command to the below it should work:

docker run --gpus all -v /mnt/c/fastsurfer/my_mri_data:/data \
            -v /mnt/c/fastsurfer/my_fastsurfer_analysis_5:/output \
            -v /mnt/c/fastsurfer/my_fs_license_dir:/fs \
            --rm --user 1000 deepmi/fastsurfer:gpu-v1.1.0 \
            --fs_license /fs/license.txt \
            --t1 /data/subject2/orig.nii \
            --sid subject2 --sd /output \
            --parallel

Let me know if this works!

**Comment by paulroeppenack** [comment]
Hi,
yes, thank you, it works!
Thanks for efforts, very helpful and much appreciated!
