### ISSUE TITLE
pandas and torchio not included in requirements.txt

### ISSUE THREAD

**Issue by 1-w** [Deep-MI/FastSurfer#170]
## Description
Cannot find packages pandas and torchio

## Steps to Reproduce
set up conda environment from scratch
conda create fastsurfer python=3.8 
pip install -r requirements.txt
run ./run_fastsurfer.sh --t1 ...

## Environment
 - FastSurfer Version: feature/vinn branch
 - FreeSurfer Version: 7.2
 - OS: Linux

**Comment by LeHenschel** [comment]
VINN is still WIP (see #168 ). Requirements.txt and dockerfile have not been updated yet. Will probably be done this week.

**Comment by LeHenschel** [comment]
Fixed in https://github.com/Deep-MI/FastSurfer/pull/168/commits/76c76bf91447606cbc2838275128c3d0c1dc65e4
