### ISSUE TITLE
Should be = instead of +=

### ISSUE THREAD

**Issue by 1-w** [Deep-MI/FastSurfer#172]
https://github.com/Deep-MI/FastSurfer/blob/dbb56df763f5dbce09345aded3784181691f4a7a/FastSurferCNN/run_prediction.py#L177

**Comment by LeHenschel** [comment]
Changed in https://github.com/Deep-MI/FastSurfer/pull/168/commits/ed2fa93971cae14ee245af43b5d7cc2f51bd38ad
