### ISSUE TITLE
extra classes

### ISSUE THREAD

**Issue by ggrrll** [Deep-MI/FastSurfer#173]
## Feature Description

Hi, 

thanks for the tool
As we  need a whole-head model, we would need to segment also skin, skull, CSF ...so I was wondering if these classes were somehow present at some point during the training  and then ditched, or if we would need a completely new training , with more labels in the  dataset 

thanks

## Motivation

need to build 3D head model

**Comment by m-reuter** [comment]
Hi ggrrll,
sadly those classes are not included and this would require having a large ground-truth dataset with those labels and re-training. We hope to extend FastSurfer in the future with more classes, but currently we supply only the close to 100 classes of FreeSurfer's Aparc+Aseg (DKT Atlas for cortical GM).
