### ISSUE TITLE
Support for the Apple MPS backend

### ISSUE THREAD

**Issue by dkuegler** [Deep-MI/FastSurfer#178]
## Feature Description
The pytorch nightly build natively supports the Apple Metal GPU-acceleration backend, see
https://pytorch.org/get-started/locally/
https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/#metal-acceleration
https://towardsdatascience.com/installing-pytorch-on-apple-m1-chip-with-gpu-acceleration-3351dc44d67c

With respect to #109 , I don't see an obvious way to get metal acceleration inside of docker as of yet. That does not 

## Motivation
Reportedly, that should get upwards of 10x (maybe 20x) speed acceleration on Apple M1 GPUs.

**Comment by dkuegler** [comment]
Early investigation into this implies it may be very simple to implement using Metal (as simple as just changing the `device`).
@m-reuter maybe I can prepare a branch/pull request and you see how that effects the performance?

**Comment by m-reuter** [comment]
see #109
