### ISSUE TITLE
Update Tutorials

### ISSUE THREAD

**Issue by m-reuter** [Deep-MI/FastSurfer#182]
## Documentation

The tutorials are outdated. In the meantime we updated file names (DKTatlas and mapped, see #121 and  #129 ), and maybe also command line flags. Also we have docker images at dockerhub so there is no need to build your own. 

These things should be updated in the tutorial slides: 
https://docs.google.com/presentation/d/1xuMFBo-AQMwdH8MplUWgEvn9z0bJk6p1mzi2vm-mKvs/edit#slide=id.gd6816a7d85_0_166 

and also double check the colab tutorials. 

It probably makes sense to do all this for the next major release with the FastSurferVinn.

**Comment by m-reuter** [comment]
- I have added an INSTALL.md (which may need some further updates and checks) in 9451196 . 
- Further, I re-formatted and updated the --help texts of run_fastsurfer.sh and recon-surf.sh  (see 6f02277 ). Other scripts may need similar treatment (also in python, output formatting could probably be improved). 
- newly added python scripts in recon_surf need coherent docstring formting for the new functions.

**Comment by dkuegler** [comment]
This should probably be moved up on the priority list now. @agirodi should address this and open a PR for updated Tutorials.

**Comment by m-reuter** [comment]
Documentation and tutorials have been updated to v 2.0
