### ISSUE TITLE
An AttributeError when I use Fastsurfer on Docker

### ISSUE THREAD

**Issue by daozaichen** [Deep-MI/FastSurfer#186]
There is an AttributeError when I use Fastsurfer on Docker.What should I do?

========= Creating filled from brain (brainfinalsurfs, wm.asegedit, wm)  =======
 
recon-all -s subject -asegmerge -normalization2 -maskbfs -segmentation -fill
Traceback (most recent call last):
  File "/opt/freesurfer/python/scripts/rca-config2csh", line 25, in <module>
    for var_name, var_config in config.items():
AttributeError: 'NoneType' object has no attribute 'items'
ERROR: must specify a subject id
Command exited with non-zero status 1
@#@FSTIME  2022:08:30:06:26:16 recon-all N 7 e 0.32 S 0.03 U 0.07 P 32% M 11616 F 10 R 4976 W 0 c 11 w 69 I 2144 O 0 L 1.89 7.09 4.96
@#@FSLOADPOST 2022:08:30:06:26:16 recon-all N 7 1.89 7.09 4.96

 - OS: Ubuntu20.04

Run Command: 
docker run -v /home/zkli/Documents/my_mri_data:/data -v /home/zkli/Documents/dy_fastsurfer_analysis:/output -v /home/zkli/Documents/my_fs_license_dir:/fs_license --rm --user root fastsurfer:cpu --fs_license /fs_license/license.txt --t1 /data/subject/houjie.mgz --no_cuda --sid subject --sd /output --parallel

**Comment by m-reuter** [comment]
Did you create that Docker image yourself (based on what branch?). Maybe try our provided image `docker pull deepmi/fastsurfer:cpu-v1.1.1` and run that one.

**Comment by daozaichen** [comment]
> Did you create that Docker image yourself (based on what branch?). Maybe try our provided image `docker pull deepmi/fastsurfer:cpu-v1.1.1` and run that one.

Dear m-reuter, 

Thank you for your help! With your help, I have solved this problem. But there is a new problem:

error: not enough inputs supplied to 'subject'
Linux f0c1a84b8035 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s subject exited with ERRORS at Wed Sep  7 05:15:32 UTC 2022

Is this problem from fastsurfer or freesurfer? What should I do?

**Comment by m-reuter** [comment]
Can you send the exact command that you called? And probably I need to see the recon-surf.log file also.

**Comment by daozaichen** [comment]
> Can you send the exact command that you called? And probably I need to see the recon-surf.log file also.

The exact command is as follows:

docker run -v /home/zkli/Documents/my_mri_data:/data -v /home/zkli/Documents/ey_fastsurfer_analysis:/output -v /home/zkli/Documents/my_fs_license_dir:/fs_license --rm --user root deepmi/fastsurfer:cpu-v1.1.1 --fs_license /fs_license/license.txt --t1 /data/subject/orig.mgz --no_cuda --sid subject --sd /output --parallel

recon-surf.log is as follows:

cd /output/subject/mri
mris_place_surface --thickness ../surf/rh.white ../surf/rh.pial 20 5 ../surf/rh.thickness
   Update not needed
#@# area and vertex vol rh Wed Sep  7 05:15:32 UTC 2022
cd /output/subject/mri
mris_place_surface --thickness ../surf/rh.white ../surf/rh.pial 20 5 ../surf/rh.thickness
   Update not needed

 mri_brainvol_stats subject 

error: not enough inputs supplied to 'subject'
Linux f0c1a84b8035 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s subject exited with ERRORS at Wed Sep  7 05:15:32 UTC 2022

For more details, see the log file /output/subject/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Command exited with non-zero status 1
@#@FSTIME  2022:09:07:05:15:30 recon-all N 3 e 1.73 S 0.33 U 1.47 P 104% M 32784 F 1 R 112830 W 0 c 94 w 907 I 8 O 824 L 1.05 1.12 1.72
@#@FSLOADPOST 2022:09:07:05:15:32 recon-all N 3 1.05 1.12 1.72

**Comment by m-reuter** [comment]
Thanks, I was able to replicate your problem. I have a few ideas, what it could be and will investigate.

**Comment by m-reuter** [comment]
OK, looks like the name of the subject cannot be "subject". `recon-all -subject subject -segstats` fails otherwise. This is a FreeSurfer bug that we inherit. More specifically `mri_brainvol_stats subject` fails when called from here: https://github.com/freesurfer/freesurfer/blob/e5ee495b3a2714a55cf0509a519f35b82524095e/scripts/recon-all#L4706
Seems like the argparse is getting confused here:
https://github.com/freesurfer/freesurfer/blob/e5ee495b3a2714a55cf0509a519f35b82524095e/mri_brainvol_stats/mri_brainvol_stats.cpp#L17 

Anyway short story: don't ever use "subject" as the subject name :-)

**Comment by dkuegler** [comment]
@m-reuter You are correct, freesurfer/utils/argparse.cpp works a bit funny in that way, because it "stores" `"subject"` in `index` and therefore recognizes `"subject"` as a flag (which it clearly is not), instead of the positional, that it actually would be.
In https://github.com/freesurfer/freesurfer/blob/e5ee495b3a2714a55cf0509a519f35b82524095e/utils/argparse.cpp#L225 it then goes into the flag branch instead of the positional branch....

**Comment by m-reuter** [comment]
This needs to be fixed on the FreeSurfer side. I submitted a bug report there 
https://github.com/freesurfer/freesurfer/issues/1022
where further comments or fixes can go.

**Comment by m-reuter** [comment]
was fixed upstream in https://github.com/freesurfer/freesurfer/commit/53b852282f58757d4820569b6cf16c3f240589b2 and i added a check for "subject" and error exit (as we use FS7.2) 474a85245ff78faa8a0313f4a9e355f53c817945 . In future releases this can be tested and removed again. 
@daozaichen hope that everything works for you now.
