### ISSUE TITLE
[Suggestion] log should be displayed on console on the go

### ISSUE THREAD

**Issue by tashrifbillah** [Deep-MI/FastSurfer#19]
I understand that you tee them to a log file and I don't think that is a good practice:
https://github.com/Deep-MI/FastSurfer/blob/master/run_fastsurfer.sh#L283

When running a program, I want to be able to monitor how my job is doing. Storing the logs in a file and printing them all at once at the end hinders that ability.

**Comment by LeHenschel** [comment]
Hey,

the program output should be displayed on your terminal as well in addition to being written into the log-file akin to FreeSurfer's recon-all process.

Best,
Leonie

**Comment by tashrifbillah** [comment]
@LeHenschel , I like that you manage the issues very efficiently but it would be great if you can keep them open after making a response so the user can try that out and share their feedback :)

**Comment by tashrifbillah** [comment]
> python is buffering its output by default

If I do `python3.6 eval.py`, there is no such buffering. Buffering seems to be present only when `run_fastsurfer.sh` is used. I believe it is being buffered there:

https://github.com/Deep-MI/FastSurfer/blob/master/run_fastsurfer.sh#L284

What do you say?

**Comment by LeHenschel** [comment]
Hey,

basically every time you do not call the python process directly you will get the buffering. This is why this happens with the docker as well as the run_fastsurfer.sh script. In case you are not using the docker the solution is basically the same: you need to set the environment variable to disable the default behavior. 

So in case you run the script locally you need to call
`export PYTHONUNBUFFERED=0`

Then the output will show up directly within the terminal as well as the log-file. I added this information to the main README as well per commit d1db5be.

I hope this clears things up and makes it work for you?

Best,
Leonie

**Comment by LeHenschel** [comment]
Short update: I changed the logging procedure in eval.py with commit c9d8119. Therefore, even if the PYTHONUNBUFFERED=0 is not set, the output will now be displayed on the terminal and the console.

**Comment by tashrifbillah** [comment]
Thanks @LeHenschel , I'll pull and give it a try.
