### ISSUE TITLE
replace deprecated image.header.get_affine with image.affine

### ISSUE THREAD

**Issue by dkuegler** [Deep-MI/FastSurfer#190]
## Feature Description
Search and replace `get_affine()` by `image.affine`

Both master and feature/vinn use it at least in `FastSurferCNN/data_loader/conform.py`.
In general, best practice is to always use `image.affine`, since header and `image.affine` only get synchronized during initialization and when `image.update_header()` is called (this updates the header by pushing the `image.affine` into the header).

Probably also move the conversion from any format to mgh into a dedicated function.

## Motivation
`image.header.get_affine()` and `image.get_affine()` is deprecated by nibabel since version 2.0

See also https://github.com/Deep-MI/FastSurfer/pull/189

**Comment by m-reuter** [comment]
After updating it should be tested with both mgz and nii inputs and with various headers (e.g. non-isotropic voxels)

**Comment by dkuegler** [comment]
Currently, `get_affine` is only used in `conform.py`. However, `conform.py` really only supports the output of `MGHImage`s, which is a special case for the affine calculation.
In essence, our code right now internally requires `MGHImage`s and `MGHHeader`s to work properly.
Ideally, we would adapt instances, where we "explicitly" create `MGHImage`s to be more versatile.
