### ISSUE TITLE
Accepted File Formats

### ISSUE THREAD

**Issue by FL33TW00D** [Deep-MI/FastSurfer#20]
Hi there,
What are the accepted file formats for FastSurfer? I would like to use it to improve speed/performance compared to FreeSurfer, but in all examples you provide a "orig.mgz" file which is a file created by FreeSurfer?

Many Thanks,
Chris

**Comment by LeHenschel** [comment]
Hey,

the input does not have to be a .mgz. Theoretically, anything that can be read with nibabel should be processable (nifti-images for example).

Best,
Leonie

**Comment by FL33TW00D** [comment]
Hi Leonie,
Thanks for the quick response.
I can run the files through FreeSurfer to obtain the .mgz prior to running through FastSurfer, will using a .nii.gz hinder performance?

Many Thanks,
Chris

**Comment by LeHenschel** [comment]
Hey Chris,

no, in my experience there is no timing difference in using .nii.gz compared to .mgz. You can of course use mri_convert for file conversion and add -c to already conform the image to the input requirements of FastSurfer (UCHAR, 256x256x256, 1 mm voxels and standard slice orientation), but we anyhow check and conform the image in case it does not comply before running the network (and this takes no more than 1-2s).

Best,
Leonie

**Comment by FL33TW00D** [comment]
Hi Leonie,
Thanks for the advice, will go ahead and use the .nii.gz.
Your work here is brilliant.

Many Thanks,
Chris
