### ISSUE TITLE
FastsurferCNN on Ubuntu

### ISSUE THREAD

**Issue by Bhagyasree-knauparthi** [Deep-MI/FastSurfer#200]
## Question/Support Request

I'm trying to run FastSurfer CNN for segmentation on my unbuntu. I was able to build docker container for CPU using your instructions given in example 4. But, there seems to be some problem running the program. When I execute the following  error:

Total Dataset Size is 2
Running Fast Surfer on 005.mgz
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
NotADirectoryError: [Errno 20] Not a directory: '/data/005.mgz/005.mgz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 535, in <module>
    input_image = nib.load(invol)
  File "/venv/lib/python3.8/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/data/005.mgz/005.mgz'

The program creates the correct output folder structure at /home/nayan/Documents/fastsurfer/fastsurferCNN_results/sub005/005.mgz/mri/orig.
But, there is no output files in there. Any clue what might be going wrong?

## Environment
 - FastSurfer Version: ... sudo git clone https://github.com/Deep-MI/FastSurfer.git

### Execution

sudo docker build --rm=true -t fastsurfercnn:cpu -f ./Docker/Dockerfile_FastSurferCNN_CPU .

Run Command: 

sudo docker run -v /home/nayan/Documents/sub005/mri/orig:/data -v /home/nayan/Documents/fastsurfer/fastsurferCNN_results/sub005:/output --rm --user 1004 fastsurfercnn:cpu --i_dir /data --in_name 005.mgz --o_dir /output --out_name mri/aparc.DKTatlas+aseg.deep.mgz --log deep_surfer.log --no_cuda

**Comment by m-reuter** [comment]
Hi @Bhagyasree-knauparthi there should be no need to build your own docker images. Just use our stable released ones from docker hub, e.g. `docker pull deepmi/fastsurfer:cpu-v1.1.1` . Building your own is for developers or testers of the dev version, which can be broken at any point.  And when calling it try this (or similar): 

```
docker pull deepmi/fastsurfer:cpu-v1.1.1
docker run   -v /home/nayan/Documents/sub005/mri/orig:/data \
                      -v /home/nayan/Documents/fastsurfer/fastsurferCNN_results:/output \
                      --rm --user 1004 deepmi/fastsurfer:cpu-v1.1.1 \
                      --t1 /data/005.mgz \
                      --sid sub005 --sd /output \
                      --no_cuda --seg_only
```

and make sure that the file `/home/nayan/Documents/sub005/mri/orig/005.mgz` exists on the host system. Once this works, you can try the CNN-only container (we also have that on Docker : `docker pull deepmi/fastsurfer:segonly-cpu-v1.1.1` but I would need to lookup the flags for calling it.

**Comment by af-a** [comment]
Hi @Bhagyasree-knauparthi.

In case you are building the docker image from the current `stable` FastSurfer, the [example](https://github.com/Deep-MI/FastSurfer/tree/stable/Docker#example-4-build-cpu-fastsurfercnn-container-segmentation-only) you followed demonstrates processing multiple subjects within `/data` in `$SUBJECT_DIR/mri/orig.mgz` sub-directories.

In your case, you are processing a single subject and the image seems to be located in `$SUBJECT_DIR/mri/orig/005.mgz`.

You could either:
1. Run a `--simple_run` for a single subject; note that you need to specify `--in_name`, `--out_name`, and `--conf_name` file paths. For example:
```
docker run -v /home/nayan/Documents/sub005/mri/orig:/data \
           -v /home/nayan/Documents/fastsurfer/fastsurferCNN_results/sub005:/output \
           --rm --user 1004 fastsurfercnn:cpu \
           --in_name /data/005.mgz --out_name /output/mri/aparc.DKTatlas+aseg.deep.mgz \
           --conf_name /output/mri/orig.mgz --log deep_surfer.log --simple_run
```
2. Run the same command but with an adjusted `--i_dir` as in the following:
```
docker run -v /home/nayan/Documents/:/data \
           -v /home/nayan/Documents/fastsurfer/fastsurferCNN_results/sub005:/output \
           --rm --user 1004 fastsurfercnn:cpu \
           --i_dir /data --in_name mri/orig/005.mgz --o_dir /output \
           --out_name mri/aparc.DKTatlas+aseg.deep.mgz --log deep_surfer.log
```
(Note that in the second case the program will look for all sub-directories of `/data` that contain `$SUBJECT_DIR/mri/orig/005.mgz` and process them sequentially, so it's recommended that you have a dedicated directory that contains only the subject directories.)

Let us know if this does not resolve your issue.

**Comment by Bhagyasree-knauparthi** [comment]
thanks for the reply, It is working for me

**Comment by af-a** [comment]
Closing as the original issue was resolved and the relevant usage details were clarified.
