### ISSUE TITLE
How can I limit number of CPUs used for inference?

### ISSUE THREAD

**Issue by astewartau** [Deep-MI/FastSurfer#211]
## Question/Support Request

How can I limit the number of CPUs that are used for inference? Limiting the number of `--threads` does not seem to impact the number of CPUs that are used. My CPU usage always goes to 100% * the number of CPUs on my system, but I would like to specify a limit.

## Screenshots

...

## Environment
 - FastSurfer Version: Latest version from GitHub
 - FreeSurfer Version: None 
 - OS: Neurodesk / Ubuntu 20.04.4 LTS (Focal Fossa)

 - CPU: 11th Gen Intel(R) Core(TM) i5-11500 @ 2.70GHz
 - GPU: None

```
(qsmxt) user@neurodesktop-latest:~$ pip freeze
attrs==22.1.0
certifi @ file:///croot/certifi_1665076670883/work/certifi
charset-normalizer==2.1.1
ci-info==0.3.0
click==8.1.3
cloudstor==0.1.4
contourpy==1.0.6
cycler==0.11.0
DateTime==4.7
etelemetry==0.3.0
exceptiongroup==1.0.4
fastai==2.2.5
fastcore==1.3.9
filelock==3.8.0
fonttools==4.38.0
humanfriendly==10.0
idna==3.4
iniconfig==1.1.1
isodate==0.6.1
joblib==1.2.0
kiwisolver==1.4.4
looseversion==1.0.2
lxml==4.9.1
matplotlib==3.6.2
networkx==2.8.8
nibabel==4.0.2
nilearn==0.9.2
nipype==1.8.5
numpy==1.23.5
osfclient==0.0.5
packaging==21.3
pandas==1.5.2
Pillow==9.3.0
pluggy==1.0.0
prov==2.0.0
psutil==5.9.4
pydicom==2.1.2
pydot==1.4.2
pyparsing==3.0.9
pytest==7.2.0
python-dateutil==2.8.2
pytz==2022.6
rdflib==6.2.0
requests==2.28.1
scikit-image==0.17.2
scikit-learn==1.1.3
scipy==1.9.3
seaborn==0.12.1
SimpleITK==2.0.2
simplejson==3.18.0
six==1.16.0
threadpoolctl==3.1.0
tomli==2.0.1
torch==1.7.0
torchvision==0.8.1
tqdm==4.64.1
traits==6.3.2
urllib3==1.26.13
webdav==1.1.7
zope.interface==5.5.2
```

### Execution

[Docker container build script](https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/qsmxt/build.sh)

Run Command: 
```
run_fastsurfer.sh --sd `pwd` --seg_only --sid output --py python3.8 --t1 /neurodesktop-storage/data/WIP-Stuff/201X-SAHMRI/bids/sub-masopma010001bl/ses-1/anat/sub-masopma010001bl_ses-1_run-01_T1w.nii --parallel --threads 3
```

**Comment by m-reuter** [comment]
When using --seg_only the --threads option is not used as it affects the recon-surf (surface) pipeline only (same for the --parallel option). 

Since you have no GPU, the pyTorch neural network evaluation is falling back to CPU. Reducing the threads will  - of course - significantly extend processing time.

You could try setting the environment variable OMP_NUM_THREADS=1 to reduce threads, but not sure this will affect pytorch everywhere.

**Comment by dkuegler** [comment]
Hi,
if you are running FastSurfer within a docker container, you can start the container with additional flags to restrict the process availability, e.g. `--cpus=0.5`.
See alse https://docs.docker.com/config/containers/resource_constraints/#cpu

If you use a local installation of FastSurfer, running it with nice might help. See also https://wiki.ubuntuusers.de/nice/

The OMP_NUM_THREADS=1 flags might help reduce the flags, but might not work great. See also https://discuss.pytorch.org/t/how-to-limit-the-number-of-cpus-each-process/153645

**Comment by astewartau** [comment]
Thanks for the suggestions! This has solved our problem and we have updated our package to use the suggested solution using `OMP_NUM_THREADS`.
