### ISSUE TITLE
Error running FastSurfer

### ISSUE THREAD

**Issue by nunoloucao** [Deep-MI/FastSurfer#24]
Hi,

I'm getting this error:
./run_fastsurfer.sh: line 285: syntax error near unexpected token `&'
./run_fastsurfer.sh: line 285: `  date  |& tee -a $seg_log'

When i run the code in the examples.
Can you help me out?

Thanks.
Best,Nuno

**Comment by LeHenschel** [comment]
Hey Nuno,

I guess this is related to issue #7 . What OS are you on and what version of bash are you using?

Best,
Leonie

**Comment by nunoloucao** [comment]
Hey Leonie,

I'll check issue 7.
MacOS 10.15.6 and bash 5.0.18.

Thanks.
Best,
Nuno

**Comment by m-reuter** [comment]
We don't support MacOS yet. Until we do you need to use docker. Sorry.

**Comment by m-reuter** [comment]
Update: in our upcoming release we added support for Mac (Intel cpu-based and M Apple Silicon also GPU on mps device) for the segmentation. Furthermore, we updated install instructions (especially to update the bash shell) and modified recon-surf slightly in #198 to run through. We do not do any testing on the Mac, so you should inspect results.
