### ISSUE TITLE
failed to create docker image

### ISSUE THREAD

**Issue by sandeepganji** [Deep-MI/FastSurfer#25]
Hi,

When I build the docker image from "Dockerfile_FastSurferCNN_CPU", I get the following error after at the *"# Add FastSurfer (copy application code) to docker image"* stage.

error message:
*COPY failed: stat /var/lib/docker/tmp/docker-builder791633763/FastSurferCNN: no such file or directory*

System: Windows 10 (2004, Build 19041) + Docker Desktop Community (2.3.0.3)

**Comment by LeHenschel** [comment]
Hey,

can you post the exact command you were running and from which directory?

Best,
Leonie

**Comment by sandeepganji** [comment]
I figured it out, the best way to install on a Windows with Docker Desktop is

`git clone https://github.com/Deep-MI/FastSurfer/    c:\Temp\FastSurfer`
`cd   c:\Temp\FastSurfer`
`docker build   -t   fastsurfercnn_cpu/cpu    -f   c:\Temp\FastSurfer\Docker\Dockerfile_FastSurferCNN_CPU . `

However I see a lot more docker images, are all these necessary of only *fastsurfercnn_cpu/cpu* is enough for testing the FastSurfer
![image](https://user-images.githubusercontent.com/12124746/88510249-40646c80-cfa8-11ea-9e99-237c0c1bf236.png)

Thank you

**Comment by LeHenschel** [comment]
These look like intermediate images where the build failed/was rerun. You should be able to remove them with `docker system prune` (at least on centos/linux, I have never used Docker on Windows). Only the last image (with the actual name) should be the relevant one.

The fastsurfercnn_cpu image can be used to run just the segmentation network on the cpu. Mind you, this might take some time and we recommend using a gpu instead (1 min). On our servers with 72 cores FastSurferCNN (3 segmentation networks and view aggregation) finishes in around 20-23 mins on the CPU. When using only 6 cores it takes 1h. Just so you know...

**Comment by sandeepganji** [comment]
That's what I thought about too that these images without names are intermediate containers. I would add a note in the instructions to use `--rm=true` to the docker build to remove intermediate containers after a successful build.

I can't use the GPU one on the windows, since docker images with GPU support needs the nvidia-container, which is only available on Linux hosts. Also trying of testing the FastSurfer on a VMware ESXi server, where I can assign a GPU to a Linux VM. That was one easy, wanted to make a Windows test too.

Thanks

**Comment by LeHenschel** [comment]
Ok, cool thanks! I was not aware of the --rm=true flag for the docker build command. I added it in the documentation and default build script (commits c5e9677 and 2f2edfa).
