### ISSUE TITLE
Get additional parcellation stats

### ISSUE THREAD

**Issue by araikes** [Deep-MI/FastSurfer#267]
I have a pre-run version of Fastsurfer outputs (#256), but I'd like to get not just the DKT parcellation but also just `aparc` for use with Enigma Toolbox. I know there's the `--fsaparc` flag but I didn't use it the first time around. 

Is there away to get the aparc parcellation stats without having to reprocess everything? I tried adding `--seg_only --fsaparc` but it complained about using the existing output directory.

**Comment by LeHenschel** [comment]
Hey araikes,

if you already ran the recon-surf pipeline including the --surf-reg option (which is turned on by default), you can create the aparc stats using FreeSurfer commands by running mris_ca_label and mris_anatomical_stats (see also https://github.com/Deep-MI/FastSurfer/issues/89):

```
cd $SUJECTS_DIR/<subjid>/mri

# create atlas annotations (?h.aparc.annot)
mris_ca_label -l ../label/lh.cortex.label -aseg mri/aseg.presurf.mgz <subjid> ?h ?h.sphere.reg $FREESURFER_HOME/average/?h.curvature.buckner40.filled.desikan_killiany.2007-06-20gcs ?h.aparc.annot

# Get stats
mris_anatomical_stats -th3 -mgz -cortex ../label/?h.cortex.label -f stats/?h.aparc.stats -b -a label/?h.aparc.annot -c label/aparc.annot.ctab <subjid> ?h
```

Kind regards,
Leonie

**Comment by m-reuter** [comment]
Have you tested if the Enigma tools also take DKT? I am not familiar with it, but the two are very similar with a few regions missing in DKT. Enigma tools may still run. 
Given that the DKT is the improved atlas it would be good to adjust the Enigma tools if necessary.

**Comment by LeHenschel** [comment]
For clarity: The aparc.DKTatlas and aparc differ in four structures. FastSurfer returns the DKTatlas segmentations by default, which has 31 labels per hemisphere (paper: https://www.frontiersin.org/articles/10.3389/fnins.2012.00171/full). The aparc+aseg.mgz (=aparc) is based on an older atlas version (Desikian, 35 parcels per hemisphere; paper: https://www.sciencedirect.com/science/article/abs/pii/S1053811906000437?via%3Dihub). The DKTatlas is basically an adaptation thereof where four labels (bankstss (1001, 2001), corpus callosum (1004, 2004), frontal pole (1032, 2032), and temporal pole (1033, 2033)) have been merged with other labels.

Overall as Martin said, they are very similar. The DKTatlas paper also explains why merging the labels is beneficial.

**Comment by araikes** [comment]
That's perfect. I knew there had to be something simple.

As far as using the DKT atlas, currently the plotting functions use just DK (or Schaefer atlases), so I'm working within what's available for the moment.

**Comment by m-reuter** [comment]
Yes, but would it not just skip plotting the missing labels? There are no additional labels in DKT which makes this really simple.

**Comment by araikes** [comment]
That's a fair point and one which I will need to investigate.

**Comment by araikes** [comment]
Just a few small edits based on Fastsurfer `2.0.x` and Freesurfer `7.3.2`, in case anyone else is looking for this (date is different for the `lh.curvature.buckner40.filled` file and `aparc.annot.ctab` is `aparc.annot.mapped.ctab` in the current Fastsurfer version).

```
cd $SUJECTS_DIR/<subjid>/mri

# create atlas annotations (?h.aparc.annot)
mris_ca_label -l ../label/?h.cortex.label -aseg mri/aseg.presurf.mgz <subjid> ?h ?h.sphere.reg $FREESURFER_HOME/average/?h.curvature.buckner40.filled.desikan_killiany.2010-03-25.gcs ?h.aparc.annot

# Get stats
mris_anatomical_stats -th3 -mgz -cortex ../label/?h.cortex.label -f stats/?h.aparc.stats -b -a label/?h.aparc.annot -c label/aparc.annot.mapped.ctab <subjid> ?h
```
