### ISSUE TITLE
"docker pull deepmi/fastsurfer:gpu-v2.0.0" doesn't work

### ISSUE THREAD

**Issue by mafortin** [Deep-MI/FastSurfer#268]
## Documentation

Quick Issue to mention that the command "docker pull deepmi/fastsurfer:gpu-v2.0.0" doesn't work but "docker pull deepmi/fastsurfer" does (at least for Ubuntu 18).

The output error is:
"""
Error response from daemon: manifest for deepmi/fastsurfer:gpu-v2.0.0 not found: manifest unknown: manifest unknown
"""

Have a nice day! :)

**Comment by LeHenschel** [comment]
The newest version is v2.0.4. If you want the gpu version, the latest tag would also work:

docker pull deepmi/fastsurfer:gpu-v2.0.4

or 

docker pull deepmi/fastsurfer:latest

**Comment by mafortin** [comment]
_docker pull deepmi/fastsurfer_ will automatically pull the latest version. :)
