### ISSUE TITLE
freesurfer qcache error after running fastsurfer - no jacobian_white

### ISSUE THREAD

**Issue by pavgreen9** [Deep-MI/FastSurfer#281]
## Question/Support Request

Hi, I ran fastsurfer just fine but require the qcache fwhm output for mris_preproc analysis. A previous user had a [similar issue](https://github.com/Deep-MI/FastSurfer/issues/49) and fixed it by manually inputting the --surfreg flag and their qcache output turned out fine. 

I've noticed that the --surfreg flag has been automatically enabled since then given rh/lh.sphere that is already in my surf directory. However, when I run qcache in recon-all I get the error 

```
ERROR: cannot find /home/pavgreen/Documents/LRGS/MRI/Participants/fast_out/A686/surf/lh.jacobian_white
Command exited with non-zero status 1
```

## Environment
 - FastSurfer Version: 2.0.4 Docker GPU
 - FreeSurfer Version: 7.3.2 
 - OS: Ubuntu 22.04.2
 - CPU: Ryzen 5 3600
 - GPU: GTX 1070 Ti

### Execution

**Fastsurfer**: 
while read participant; do
	nohup docker run --gpus all \
		-v /home/pavgreen/Documents/LRGS/MRI/Participants/unprocessed_raws/${participant}/mprage/anat:/data \
		-v /home/pavgreen/Documents/LRGS/MRI/Participants/fast_out:/output \
		-v /usr/local/freesurfer/7.3.2:/fs_license \
		--rm --user $(id -u):$(id -g) deepmi/fastsurfer:latest \
		--fs_license /fs_license/license.txt \
		--t1 /data/${participant}.nii \
		--sid ${participant} --sd /output \
		--parallel \
		--threads 12 \
		--surfreg \
		--vox_size 1
	sleep 90S
done < subjList.txt

**Freesurfer qcache**:
recon-all -s A686 -qcache

Thank you

**Comment by LeHenschel** [comment]
Seems like the jacobian is not generated by default in FastSurfer. You can create it with  FreeSurfer:

mris_jacobian ?h.white ?h.sphere.reg ?h.jacobian_white

We might want to add this by default @m-reuter @AhmedFaisal95 . The command takes less than a second.

**Comment by m-reuter** [comment]
Yes, should be done at same spot as in recon-all. Not sure how this got lost. Is anything else missing?

**Comment by LeHenschel** [comment]
Not as far as I know. For me qcache runs through without error once the jacobian is generated. The other measures are generated around line 904 (https://github.com/Deep-MI/FastSurfer/blob/stable/recon_surf/recon-surf.sh#L904).

Added in pull request #282

**Comment by pavgreen9** [comment]
Hi, thank you for the replies. There doesn't seem to be anything else missing on my side either. 

Thank you for the help.

**Comment by LeHenschel** [comment]
Great. I am closing this issue then. Feel free to reopen if anything else comes up
