### ISSUE TITLE
generate_hf5.py creates 'empty' HDF5 datasets

### ISSUE THREAD

**Issue by mafortin** [Deep-MI/FastSurfer#284]
## Description

Hi! :) I've been trying to train FastSurferVINN with my own datasets, but I've been facing issues with the 'generate_hdf5.py' script. In my case, 'generate_hdf5.py' _runs_ for a few minutes, creates a HDF5 document, and exits without error. Everything looks ok until you give the HDF5 dataset to the 'train.py' script (as described in the documentation) and it tries to load images in the HDF5 which contains 0 images. To double check, I tried to load the HDF5 in python (with a separate script) to verify its content and it's empty. Another thing that lets me believe the HDF5 dataset is empty is its size, which is **always** 800 bytes.

I followed the steps in the documentation in the README.md for 'generate_hdf5.py' in the FastSurferCNN folder and even tried with two different datasets in addition of testing for both the 'stable' and 'dev' branches, but all cases resulted in the same issue (i.e., creating empty HDF5 datasets). 

## Steps to Reproduce

1. I activate my 'fsvinn' conda virtual environment and 'cd' to the 'FastSurfer-stable/FastSurferCNN/' folder.
2. Then, I type the following command: *python3 generate_hdf5.py --hdf5_name /home/marc/Data/training/HCP_20/test-hcp20subs.hdf5 --csv_file /home/marc/Data/training/HCP_20/test-csv-hcp-20.csv --image_name T1w/T1w_acpc_dc_restore.nii.gz --gt_name T1w/aparc+aseg.nii.gz --gt_nocc T1w/aparc+aseg.nii.gz*
3. After a few minutes, the script finishes running and a HDF5 dataset with the expected name is created.

## Expected Behavior
I expect the HDF5 to not be empty and usable for retraining FastSurferVINN as described in the documentation.

## Screenshots

- miniconda virtual environment screenshot (I am using a native install): 
![image](https://user-images.githubusercontent.com/51452174/230582586-d91a0caa-5704-4e71-ba54-cd393fa68254.png)

## Environment

 - FastSurfer Versions: v2.0.4 (latest) & dev version also
 - FreeSurfer Version: freesurfer-linux-ubuntu18_x86_64-7.2.0-20210721-aa8f76b (but not using recon-surf)
 - OS: Ubuntu 18.04.6 LTS
 - CPU: 16 cores, 62.9 Gb of RAM available (not sure about exact details)
 - GPU: NVIDIA Tesla P100 PCIe 16 GB

### Execution

I typed the following command: *python3 generate_hdf5.py --hdf5_name /home/marc/Data/training/HCP_20/test-hcp20subs.hdf5 --csv_file /home/marc/Data/training/HCP_20/test-csv-hcp-20.csv --image_name T1w/T1w_acpc_dc_restore.nii.gz --gt_name T1w/aparc+aseg.nii.gz --gt_nocc T1w/aparc+aseg.nii.gz*

## Additional Context

- One of the dataset I used was a subset of 20 HCP datasets in the untouched folder architecture as you download the data from their data sharing 'app'/website. The other dataset was a local dataset with 20 subjects. Images in both datasets had the *.nii.gz* format. The HCP dataset has a resolution of (0.7mm)3 and the other one 1mm3.
- The CSV file isn't empty and contains the fullpath down to the subject folder (as described in the documentation).

**Comment by LeHenschel** [comment]
Hey there,

if it just runs through in a few minutes it is probably an issue with the file path, i.e. the files are not found. If you have a log-file there should be an error message in there (sth like "Volume: {} Failed Reading Data. Error: {}"). Would be helpful to look at to see why this happens.

**Comment by mafortin** [comment]
@LeHenschel hi! I also suspect that, even if the paths are correct... Are there supposed to be log files produced because I don't see any in the directory?

**Comment by LeHenschel** [comment]
Not by default. Logging is directed to stdout. But as you did not mention an error message, I thought you might redirect the output. You can also uncomment the try except block in the .py file (https://github.com/Deep-MI/FastSurfer/blob/stable/FastSurferCNN/generate_hdf5.py#L112). This way the processing will fail directly at whatever step causes the error.

**Comment by mafortin** [comment]
Ok! I've been trying to debug it since this morning, and the loading of the images seems to eb ok. However, I discovered that the labels in the HCP segmentations are not exactly like the one given by fs-vinn (n=87 vs n=79). This outputs an *'AssertationError': Error: segmentation image contains classes not listed in the labels: [...]* at line ~165, but the script still runs thoroughly.

**Comment by mafortin** [comment]
oh quick Q: How much should I expect the *generate_hdf5.py* to run for a ~20 subjects dataset?

**Comment by LeHenschel** [comment]
Yes the script runs because of the try .. except clause. But the resulting hdf5-set will be empty because it fails on each subject. You should be able to pass a look-up table with the classes you want to train on (see the help):

--lut : FreeSurfer-style Color Lookup Table with labels to use in final prediction. Has to have columns: ID	LabelName	R	G	B	A. Default: ./config/FastSurfer_ColorLUT.tsv.

Depending on left-right splits you might also need to adjust the description for it with
--combi : Suffixes of labels names to combine. Default: Left- and Right- (for the lateralization)
--sag_mask : Suffixes of labels names to mask for final sagittal labels. Default: Left- and ctx-rh

Also, for FastSurfer we train on the DKTatlas and combine some cortical labels during training and split them afterwards which is why the network output is 79 classes while the final segmentation has 96 (33 subcortical + 31x2 cortical classes + 1 for Background; see e.g. table 5 in the appendix of FastSurferVINN https://www.sciencedirect.com/science/article/pii/S1053811922000623?via%3Dihub).  This is automatically done if --processing is set to aparc (default in generate_hdf5.py).

**Comment by mafortin** [comment]
Ok great it does make sense! Thank you! I will have to do some work before confirming whether it is *really* this the issue or not, but it looks promising! :)

**Comment by LeHenschel** [comment]
Sure thing :). Let us know if anything else comes up. 

Also @m-reuter, I think we should remove the try except block in the code as this has caused confusion for a few people by now. This was mainly included to skip processing if one or two subjects are not found without interrupting the whole generation process. Addition of a separate check if a.) all files can be found and if b.) the labels are in agreement with the LUT before starting the processing makes more sense.

**Comment by m-reuter** [comment]
I agree. Can you change that in dev?

**Comment by mafortin** [comment]
Not related, but might be relevant:

@m-reuter @LeHenschel quick code discrepancy in *generate_hdf5.py* between the dev and stable versions: 
More precisely where the --lut argument is parsed. 

**dev** has *default=join(dirname(__file__), './config/FastSurfer_ColorLUT.tsv')* 

**stable** has *default='./config/FastSurfer_ColorLUT.tsv'*

Thus, the **dev** version produces a combination of the current working directory + './config/FastSurfer_ColorLUT.tsv' instead of simply changing the './' for the working directory.

**Comment by m-reuter** [comment]
I just checked dev and in https://github.com/Deep-MI/FastSurfer/blob/cc102890407f906b2a95712b9f405b9bb8bdcc18/FastSurferCNN/generate_hdf5.py#L209 it is without the '.' so that should be ok.

**Comment by mafortin** [comment]
FYI: I was finally able to create a HDF5 dataset with *generate_hdf5.py* with the solution proposed by @LeHenschel ! :) Thanks!
