### ISSUE TITLE
Different results during training and test

### ISSUE THREAD

**Issue by d0ng231** [Deep-MI/FastSurfer#285]
## Question/Support Request

I trained FastSurferCNN on my own datasets, the prediction plots generated during training seems OK, but when I tried to run prediction (run_prediction.py) on one of the subjects in the training set, the results are in very poor quality.

I debugged the script a few times, made sure that the input images were correct, but still cannot solve the problem. 

Below is the cofig I used for axial images(similar for coronal and sagittal), the MRI data I used is already preprocessed to 320x320x320, with voxel size 0.7, and value in between 0 and 256:

MODEL:
  MODEL_NAME: "FastSurferCNN"
  NUM_CLASSES: 79
  NUM_FILTERS: 71
  KERNEL_H: 3
  KERNEL_W: 3
  BASE_RES: 0.7
  NUM_CHANNELS: 5
  OUT_TENSOR_WIDTH: 320
  OUT_TENSOR_HEIGHT: 320
  HEIGHT: 320
  WIDTH: 320

DATA:
  SIZES: [320]
  PADDED_SIZE: 320
  PLANE: "axial"
  PATH_HDF5_TRAIN: "/datadisk/chenjun/dataset/HCP/hdf5_set/train_set_axial.hdf5"
  PATH_HDF5_VAL: "/datadisk/chenjun/dataset/HCP/hdf5_set/val_set_axial.hdf5"
  AUG: ["None", "Gaussian"]

DATA_LOADER:
  NUM_WORKERS: 3

OPTIMIZER:
  LR_SCHEDULER: cosineWarmRestarts
  OPTIMIZING_METHOD: adamW

TRAIN:
  NUM_EPOCHS: 200
  BATCH_SIZE: 16

NUM_GPUS: 2
LOG_DIR: "./experiments"
EXPR_NUM: "FastSurferFA_axial_1"

## Screenshots

The plots during training
<img width="324" alt="iShot_2023-04-16_14 57 33" src="https://user-images.githubusercontent.com/41299046/232278708-89595f17-3af1-46f2-959d-8fb286549f97.png">
The prediction I got
<img width="1310" alt="iShot_2023-04-16_14 59 38" src="https://user-images.githubusercontent.com/41299046/232278812-ee2c34bc-ec61-426e-901b-2e75b78bb248.png">
Tensorboard info (since I used preprocessed diffusion MRI as the T1 input, the dice score can only reach approximately 0.7, but the prediction I got is clearly not even close to 0.7 dice score)
<img width="885" alt="iShot_2023-04-16_11 07 47" src="https://user-images.githubusercontent.com/41299046/232279085-624703b0-d412-4f29-a4a0-5d03744614a0.png">

## Environment
 - FastSurfer Version: 2.0.4

### Execution

python3 run_prediction.py \
> --sd /home/fan1/chenjun/output/HCP \
> --sid 101410 \
> --t1 /datadisk/chenjun/dataset/HCP/101410/fa.mgz \
> --lut ./config/FastSurfer_ColorLUT.tsv \
> --aparc_aseg_segfile pred.mgz \
> --cfg_ax ./config/FastSurferFA_axial.yaml \
> --ckpt_ax ./experiments/FastSurferFA_axial/checkpoints/FastSurferFA_axial_1/Best_training_state.pkl \
> --cfg_cor ./config/FastSurferFA_coronal.yaml \
> --ckpt_cor ./experiments/FastSurferFA_coronal/checkpoints/FastSurferFA_coronal_1/Best_training_state.pkl \
> --cfg_sag ./config/FastSurferFA_sagittal.yaml \
> --ckpt_sag ./experiments/FastSurferFA_sagittal/checkpoints/FastSurferFA_sagittal_1/Best_training_state.pkl
[INFO: run_prediction.py:  345]: Checking or downloading default checkpoints ...
[INFO: run_prediction.py:  159]: Output will be stored in: /home/fan1/chenjun/output/HCP
[INFO: misc.py:  159]: Using device: cuda
[INFO: run_prediction.py:  122]: Running view aggregation on cuda
[INFO: inference.py:   95]: Loading checkpoint ./experiments/FastSurferFA_coronal/checkpoints/FastSurferFA_coronal_1/Best_training_state.pkl
[INFO: inference.py:   95]: Loading checkpoint ./experiments/FastSurferFA_sagittal/checkpoints/FastSurferFA_sagittal_1/Best_training_state.pkl
[INFO: inference.py:   95]: Loading checkpoint ./experiments/FastSurferFA_axial/checkpoints/FastSurferFA_axial_1/Best_training_state.pkl
[INFO: run_prediction.py:  363]: Analyzing single subject /datadisk/chenjun/dataset/HCP/101410/fa.mgz
[INFO: run_prediction.py:  251]: Successfully saved image as /home/fan1/chenjun/output/HCP/101410/mri/orig/001.mgz
[INFO: run_prediction.py:  177]: Conforming image
Input:    min: 0.0  max: 0.9999992251396179
rescale:  min: 0.0  max: 0.8859993134737015  scale: 287.810606760215
Output:   min: 0.0  max: 255.0
[INFO: run_prediction.py:  251]: Successfully saved image as /home/fan1/chenjun/output/HCP/101410/mri/orig.mgz
[INFO: run_prediction.py:  211]: Run coronal prediction
[INFO: dataset.py:   55]: Loading Coronal with input voxelsize (0.7, 0.7)
[INFO: dataset.py:   64]: Successfully loaded Image from /datadisk/chenjun/dataset/HCP/101410/fa.mgz
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 320/320 [00:09<00:00, 32.87batch/s]
[INFO: inference.py:  198]: Inference on 320 batches for coronal successful
[INFO: inference.py:  217]: Coronal inference on /datadisk/chenjun/dataset/HCP/101410/fa.mgz finished in 9.7417 seconds
[INFO: run_prediction.py:  211]: Run sagittal prediction
[INFO: dataset.py:   46]: Loading Sagittal with input voxelsize (0.7, 0.7)
[INFO: dataset.py:   64]: Successfully loaded Image from /datadisk/chenjun/dataset/HCP/101410/fa.mgz
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 320/320 [00:08<00:00, 36.71batch/s]
[INFO: inference.py:  198]: Inference on 320 batches for sagittal successful
[INFO: inference.py:  217]: Sagittal inference on /datadisk/chenjun/dataset/HCP/101410/fa.mgz finished in 8.7177 seconds
[INFO: run_prediction.py:  211]: Run axial prediction
[INFO: dataset.py:   51]: Loading Axial with input voxelsize (0.7, 0.7)
[INFO: dataset.py:   64]: Successfully loaded Image from /datadisk/chenjun/dataset/HCP/101410/fa.mgz
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 320/320 [00:06<00:00, 48.64batch/s]
[INFO: inference.py:  198]: Inference on 320 batches for axial successful
[INFO: inference.py:  217]: Axial inference on /datadisk/chenjun/dataset/HCP/101410/fa.mgz finished in 6.5803 seconds
[INFO: run_prediction.py:  251]: Successfully saved image as /home/fan1/chenjun/output/HCP/101410/pred.mgz
[INFO: run_prediction.py:  394]: Creating brainmask based on segmentation...
Creating dilated mask ...
Frontal region special treatment:  1224
  Found 56 connected component(s)!
  Selecting largest component!
[INFO: run_prediction.py:  251]: Successfully saved image as /home/fan1/chenjun/output/HCP/101410/mri/mask.mgz
[INFO: run_prediction.py:  400]: Creating aseg based on segmentation...
Reducing to aseg ...
Traceback (most recent call last):
  File "run_prediction.py", line 403, in <module>
    aseg = rta.flip_wm_islands(aseg)
  File "/home/fan1/chenjun/FastSurfer/FastSurferCNN/reduce_to_aseg.py", line 147, in flip_wm_islands
    assert( labels.max() != 0 ) # assume at least 1 connected component
AssertionError

(Thought the execution error was just caused by low segmentation quality)

**Comment by LeHenschel** [comment]
Does the saved orig.mgz look ok (the conformed image)? Also what is the floating scale of the intensity image directly before passing it through the model? Is it the same during training? Was the training also performed with conformed images (e.g. LIA orientation, high-res, scaled to 0-255)? I would guess that this is an issue with a mismatch between the processing of the images in training and prediction (i.e. either conforming/intensity issues or slice views are not identical). 

The execution error only comes up during the aseg reduction and is like you point out due to low segmentation quality.

**Comment by d0ng231** [comment]
Thank you for the reply @LeHenschel
Yes, I checked orig.mgz, looks fine to me (floating scale [0 255]) 
<img width="1060" alt="iShot_2023-04-18_09 55 55" src="https://user-images.githubusercontent.com/41299046/232650378-042b0c4a-ad9a-4b75-91c3-6241de7ae2fa.png">
I just debugged train.py and inference.py again, the floating scales before directly passing through the model are both around [0 1] (I used np.ptp() to check this), the scale factors are around 1.0. 

Besides, when I was generating hdf5 dataset before training, I added "orig*=255.0" in  _load_volumes() (generate_hdf5.py) to rescale the input to [0 255]. However, it seems that during training the values will be scaled back to [0 1] before passing through the model. But this still can not explain the error I got.

Train.py
<img width="1087" alt="iShot_2023-04-18_10 33 15" src="https://user-images.githubusercontent.com/41299046/232656491-ba610949-333d-404d-883d-2d31a08a274b.png">

Inference.py (run prediction)
<img width="1001" alt="iShot_2023-04-18_10 36 43" src="https://user-images.githubusercontent.com/41299046/232656510-adc160a3-119a-44d3-a7d2-bc4bcd514355.png">

**Comment by LeHenschel** [comment]
As I mentioned, this seems to be an issue with the images and not the code so it is difficult to say what is going wrong. I would recommend going step by step to see what you did different in the hdf5-set versus the prediction.py processing. For example, did you also conform the images for the hdf5-set? What you can do: run inference (not training) on one image in the hdf5-set (i.e. use the image as stored in the hdf5-set, not the raw image from disk). I assume this will work. Then check how the slices look in there. Do they look the same if you load the image from disk? Is there a discrepancy in the orientation, intensities (local) or view being displayed? Also does this issue come up for all views (coronal, axial, sagittal) or only in one of them/the view aggregation?

**Comment by d0ng231** [comment]
Thank you very much, I think I had just fixed the problem by commenting out the conforming process in prediction, the output finally looks normal!

**Comment by LeHenschel** [comment]
Great :). I will close this issue then.

For reference, in FastSurfer training we use the conformed orig.mgz images and hence also conform the input image during inference. If you do not use a conformed image during the hdf5-set generation, but use it in the prediction, the image is too different for the network to correctly work.
