### ISSUE TITLE
Help needed in reading aseg.stats file

### ISSUE THREAD

**Issue by shijinknox007** [Deep-MI/FastSurfer#288]
Hi All,
I tried "freesurfer_stats" python library to read aseg.stats file. But I am getting some AssertionError for stats.read(stream) function. Is there any sample python program to read the aseg.stats file?

Regards,
Shijin Knox G.U.

**Comment by LeHenschel** [comment]
pandas read_csv with delim_whitespace=True, comment="#"?

What does the Error message exactly say for freesurfer_stats?

**Comment by shijinknox007** [comment]
Please find the error I am getting while trying to read "wmparc.DKTatlas.mapped.stats" file ....

Traceback (most recent call last):
  File "statfile.py", line 2, in <module>
    stats = CorticalParcellationStats.read('wmparc.DKTatlas.mapped.stats')
  File "/home/cvlab/.local/lib/python3.6/site-packages/freesurfer_stats/__init__.py", line 248, in read
    stats._read(stream)
  File "/home/cvlab/.local/lib/python3.6/site-packages/freesurfer_stats/__init__.py", line 205, in _read
    == "# Table of FreeSurfer cortical parcellation anatomical statistics"
AssertionError

**Comment by m-reuter** [comment]
Does the freesurfer_stats tool work on e.g. aseg.stats? Anyway, the stats above (wmparc.DKT...) are created by FreeSurfer's mri_segstats command (at least currently in stable). See https://github.com/Deep-MI/FastSurfer/blob/d0fdf8346c840283bdbb4cc2f97c228204fa605a/recon_surf/recon-surf.sh#L1037 
so if it cannot read standard FreeSurfer stats files, that would be something to discuss with the freesurfer_stats developers, not here.

**Comment by m-reuter** [comment]
one other pointer: FreeSurfer provides scripts asegstats2table and aparcstats2table that can read the stats files (even from multiple subjects) and stack them into a CSV table.

**Comment by shijinknox007** [comment]
thank you so much  ... I will try that and revert ....

**Comment by LeHenschel** [comment]
Based on the Error Message, it looks to me like the module you are using can only read the cortical parcellation statistics, not the white matter parcellation. Maybe check, if they have a module for WhiteMatterParcellationStats. As @m-reuter pointed out, seems to be an issue with the freesurfer_stats module, not the FastSurfer generated stats-files.
