### ISSUE TITLE
Availability FastSurfer(CNN/VINN) of HDF5 I/O data

### ISSUE THREAD

**Issue by jhlegarreta** [Deep-MI/FastSurfer#294]
## Question/Support Request

I am wondering whether you can share the entire input data that you used to build your HDF5 model and the generated file for FastSurferCNN and/or FastSurferVINN. I would be interested in training the model and seeing if I can reproduce your results before going on and using the model to train it on a different set of labels.

## Screenshots

Does not apply.

## Environment

Does not apply.

### Execution

Does not apply.

PS: Thanks for your work.

**Comment by m-reuter** [comment]
No, sorry, but we cannot share that data. Most data providers to not permit sharing it further.
