### ISSUE TITLE
timeout during checkpoint downlaod: b2share.fz-juelich.de down

### ISSUE THREAD

**Issue by m-reuter** [Deep-MI/FastSurfer#297]
This Issue is to track problems with the Jülich File Share. Please report here, if the server is down, and - if possible - also if it is back up.

We see sporadic issues with those servers, which host the checkpoints data files. The python script:
`FastSurferCNN/download_checkpoints.py --all`
tries to download them (and also run_fastsurfer if they are missing), and will time out after a while.
Neural networks for the segmentation cannot be run if these files are missing. Currently there is no alternative way to retrieve them. 

Report downtime or other issues below...

**Comment by m-reuter** [comment]
Currently Jülich File Share is not responding.

**Comment by Stefano314** [comment]
The website is up again and the problem is solved, at least for now

**Comment by m-reuter** [comment]
Thanks for testing. Yes I contacted their support yesterday and they fixed it immediately. I guess they were not aware of this issue. We should contact them sooner next time.
