### ISSUE TITLE
error happened with run_prediction.py

### ISSUE THREAD

**Issue by jessyblues** [Deep-MI/FastSurfer#298]
## Question/Support Request
When I run FastSurfer with singularity on Linux, an error occured. 
It seems that run_prediction.py got an unrecognized  arguments: asegdkt_segfile which should not be passed. But the following information says FastSurfer asegdkt segmentation failed QC checks, which implies that the image is of bad quality and leads to failure. I'm confused and don't know how to fix this.

The script I use and the the screenshots of terminal are as follows:
![img2](https://github.com/Deep-MI/FastSurfer/assets/62341741/d2ebb62a-8e60-45cb-b12d-6721e6f67733)
![img1](https://github.com/Deep-MI/FastSurfer/assets/62341741/0f77b238-39ee-454d-939f-9b6ff652705b)

## Environment: 
 - FastSurfer Version: build by command "singularity build fastsurfer-latest.sif docker://deepmi/fastsurfer:latest" so the latest on 5/15, 2023
 - OS: Ubuntu 20.04
 - CPU: NVIDIA TITAN RTX
 - GPU: Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
 - Singularity 3.7.1 

### Execution

singularity build fastsurfer-latest.sif docker://deepmi/fastsurfer:latest

Thank you!

**Comment by LeHenschel** [comment]
Did you build the docker image yourself from dev? The one we provide on the web is build on stable. You can not mix different versions of fastsurfer, which seems to be what you are doing (using the dev version of run_fastsurfer.sh from your home directory in a docker turned singularity image build on stable). So depending on what you want to do, you have two options:

1. fastsurfer stable version (v2.0.4):  By changing the entry point from /home1/...FastSurfer-dev/run_fastsurfer.sh to /fastsurfer/run_fastsurfer.sh, everything should run without an error (this will run the latest stable release). 
2. fastsurfer dev version: Build your own docker image based on the dev branch (https://github.com/Deep-MI/FastSurfer/tree/dev/Docker#example-1-build-gpu-fastsurfer-image-default) and create a singularity image from it (see second set of commands here: https://github.com/Deep-MI/FastSurfer/tree/dev/Singularity#fastsurfer-singularity-image-creation-1). This image is then compatible with the dev version, you have in your home dir.

**Comment by jessyblues** [comment]
> Did you build the docker image yourself from dev? The one we provide on the web is build on stable. You can not mix different versions of fastsurfer, which seems to be what you are doing (using the dev version of run_fastsurfer.sh from your home directory in a docker turned singularity image build on stable).

Thanks a lot, that's exactly the problem. I change to use the run_fastsurfer.sh in the docker and it works well.

**Comment by LeHenschel** [comment]
Ok, great. Glad you got it working :).
