### ISSUE TITLE
Missing output file from "--seg_only" option

### ISSUE THREAD

**Issue by slee-prenuvo** [Deep-MI/FastSurfer#309]
## Question/Support Request

...
README.md explains the list of output files when --seg_only is used, but aseg+DKT.stats, deep-seg.log, and orig_nu.mgz are missing in the output files.

## Screenshots

...

<img width="663" alt="image" src="https://github.com/Deep-MI/FastSurfer/assets/131090810/cc1ad95f-1933-482f-b016-538637ee3b94">

## Environment
 - FastSurfer Version: docker pull deepmi/fastsurfer:latest
 - FreeSurfer Version: freesurfer-linux-ubuntu18_x86_64-7.4.0-20230510-e558e6e
 - OS: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1051-aws x86_64v)
 - CPU: ...
 - GPU:  NVIDIA-SMI 450.119.03   Driver Version: 450.119.03   CUDA Version: 11.0

### Execution

<img width="1046" alt="image" src="https://github.com/Deep-MI/FastSurfer/assets/131090810/58779f10-100a-4655-89e7-eba00625556f">

Run Command:

**Comment by LeHenschel** [comment]
The deepmi/fastsurfer:latest is based on the last stable release (v2.0.4). The additional files you mention and the README section are from the dev version. There should be a new release soon, and consequently also an update of the docker images on dockerhub.

In the meantime, you would have to build the image yourself from the dev Dockerfile (https://github.com/Deep-MI/FastSurfer/tree/dev/Docker#example-1-build-gpu-fastsurfer-image-default): 

```
git checkout dev # make sure you are on the dev branch
cd $FASTSURFER_HOME
docker build --rm=true -t fastsurfer:gpu -f ./Docker/Dockerfile .
```

**Comment by slee-prenuvo** [comment]
Thank you very much for your reply! I was able to build the image successfully according to your suggestion and get the output files that I had missed before. Thanks!
