### ISSUE TITLE
hanging docker images from the setup

### ISSUE THREAD

**Issue by sandeepganji** [Deep-MI/FastSurfer#31]
There are at least 9 docker images that are created during the FastSurfer setup that never gets deleted.
![image](https://user-images.githubusercontent.com/12124746/91274789-d543bc80-e744-11ea-8e49-290aa02d1c28.png)

Even when I use the docker force remove option on the images `docker rmi -f IMAGE_ID`  I get the following error and can't delete these temporary images
![image](https://user-images.githubusercontent.com/12124746/91275015-2c499180-e745-11ea-95b6-9eb400111b80.png)

System info:
CentOS 7 X64
Docker version: 18.09.9
CPU:  Intel  Xeon Gold 5118
GPU: Tesla P4

Did you guys see similar behavior or have suggestion to cleanup the docker images a bit?
Thanks

**Comment by m-reuter** [comment]
Docker is very conservative in cleaning up, so you need to prune incomplete and dangling images yourself: 
https://docs.docker.com/config/pruning/
