### ISSUE TITLE
Google colab issue - loading user file

### ISSUE THREAD

**Issue by neuropil** [Deep-MI/FastSurfer#314]
## Description

....

Thank you for providing the Google Colab implementation!

We trying to run the block of code for installing a user file, I get the following error when attempting run the FastSurfer function blcok.

ERROR: T1 image (/content/BaseMR_MP.nii) could not be found. Must supply an existing T1 input (full head) via 
--t1 (absolute path and name) for generating the segmentation.

I've verified that the file is present (as far as the block of code for user input file is concerned):

![image](https://github.com/Deep-MI/FastSurfer/assets/1816960/4574b4ce-b2d3-4ea3-8391-848cd6416dd4)

I've also tried the non-gunzipped .nii version of the file.

**Comment by LeHenschel** [comment]
Can you describe a little more in detail what you did? Did you upload the image with the provided call button or did you manually change the path? Which parts did you run (and in which order) and which one of them caused the error?

**Comment by LeHenschel** [comment]
Seems like the ! cd command does not work correctly, hence the image is downloaded into /content/fastsurfer and not /content (see https://github.com/googlecolab/colabtools/issues/40). Changing the command to %cd in the uploading call fixes the issue. 

UPDATE: This occurs only on the current stable branch. In dev this is fixed. The tutorials default to stable, even when checking out the dev branch. If you manually change the url in your browser (replace stable with dev, i.e. https://colab.research.google.com/github/Deep-MI/FastSurfer/blob/dev/Tutorial/Tutorial_FastSurferCNN_QuickSeg.ipynb), it works. We are going to release the next stable version soon, so not sure if this fix will be added to the v2.0.4 Tutorial version.

**Comment by neuropil** [comment]
Wonderful - thank you!! Really, really appreciate the effort involved in making the Google Colab implementation!
