### ISSUE TITLE
vertex locs is not set to surfaceRAS

### ISSUE THREAD

**Issue by Stefano314** [Deep-MI/FastSurfer#318]
## Description

During the analysis ran by using "./run_fastsurfer.sh --t1 PATH-TO.nii.gz --sd ~/OutputDir --sid TestDir" I encounter an error which states: 
""" python3.9 /home/user/FastSurfer/recon_surf/rewrite_mc_surface.py --input /export/home/user/ou$Reading in surface: /export/home/user/output_dir/TestDir/surf/lh.orig.nofix ...
Outputing surface as: /export/home/user/OutputDir/TestDir/surf/lh.orig.nofix
mris_info /export/home/user/OutputDir/TestDir/surf/lh.orig.nofix | grep -q 'vertex locs : surfac$volume geometry:
extent  : (256, 256, 256)
voxel   : ( 1.0000,  1.0000,  1.0000)
x_(ras) : (-1.0000, -0.0000,  0.0000)
y_(ras) : (-0.0000,  0.0000, -1.0000)
z_(ras) : (-0.0000,  1.0000,  0.0000)
c_(ras) : (-1.5241, 24.1642, -5.5585)
file    : /export/home/user/OutputDir/TestDir/mri/filled-pretess255.mgz
$nofix: vertex locs is not set to surfaceRAS. Exiting..."""

Now, I also noticed that during the processing I get another message saying:
"""nu_correct: Command not found."""
which I don't know if it may be lead to other mistakes.

Does anyone know how to fix this? Thanks a lot!

**Comment by m-reuter** [comment]
Try our supported docker container. I bet that your native install has the wrong dependencies installed. For example currently FreeSurfer 7.3.2 is supported, not 7.4 yet. Similarly it could be a wrong version in any of the python packages.

**Comment by Stefano314** [comment]
I do have FreeSurfer 7.3.2 and python 3.9 installed, so this error was quite unexpected. However, I'll give Docker a try on the server I'm currently working on. Thank you!

**Comment by m-reuter** [comment]
Closing this for now, feel free to re-open. Your error nu_correct not found indicates that it cannot find FreeSurfer's nu_correct , so maybe you did not source FreeSurfer correctly ( FREESURFER_HOME environment var needs to be setup for example).
