### ISSUE TITLE
ERROR: asegdkt statsfile generation failed

### ISSUE THREAD

**Issue by yizhwan** [Deep-MI/FastSurfer#328]
Hi, 

I am tryinng to run run_fastsurfer.sh in a conda environment set up with the fastsurfer_gpu.yml file. I am receiving the following error when I run run_fastsurfer.sh, it runs until the following point:

converting to UCHAR
writing: /mri/orig_nu.mgz
write MGZ (FreeSurfer) image via nibabel...
python $FASTSUFER_DIR/segstats.py --segfile /stats/aseg+DKT.stats --normfile /mri/orig_nu.mgz  --empty --excludeid 0 --ids 2 4 5 7 8 10 11 12 13 14 15 16 17 18 24 26 28 31 41 43 44 46 47 49 50 51 52 53 54 58 60 63 77 251 252 253 254 255 1002 1003 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1034 1035 2002 2003 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2034 2035 --lut /FastSurfer/FastSurferCNN/config/FreeSurferColorLUT.txt --threads 20 
Traceback (most recent call last):
  File "/home/yizhou/Documents/FastSurfer/FastSurferCNN/segstats.py", line 944, in <module>
    sys.exit(main(args.parse_args()))
  File "/home/yizhou/Documents/FastSurfer/FastSurferCNN/segstats.py", line 260, in main
    table: List[PVStats] = pv_calc(seg_data, norm_data, labels, **kwargs)
  File "/home/yizhou/Documents/FastSurfer/FastSurferCNN/segstats.py", line 670, in pv_calc
    for vols in pool.map(partial(pv_calc_patch, global_crop=global_crop, loc_border=loc_border, border=border,
  File "/home/yizhou/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/home/yizhou/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/yizhou/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/yizhou/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yizhou/Documents/FastSurfer/FastSurferCNN/segstats.py", line 865, in pv_calc_patch
    max_counts_index = np.round(pat1d_label_counts * is_valid, log_eps).argmax(axis=0, keepdims=False)
TypeError: argmax() got an unexpected keyword argument 'keepdims'
ERROR: asegdkt statsfile generation failed

This is strange because when I run: 

python $FASTSUFER_DIR/segstats.py --segfile /stats/aseg+DKT.stats --normfile /mri/orig_nu.mgz  --empty --excludeid 0 --ids 2 4 5 7 8 10 11 12 13 14 15 16 17 18 24 26 28 31 41 43 44 46 47 49 50 51 52 53 54 58 60 63 77 251 252 253 254 255 1002 1003 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1034 1035 2002 2003 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2034 2035 --lut /FastSurfer/FastSurferCNN/config/FreeSurferColorLUT.txt --threads 20 

by itself within the same conda environment, It runs fine with no errors.

Can anyone shed some light on this issue?

Thanks!

**Comment by m-reuter** [comment]
Your are using an old version of numpy that does not know the keep dims argument. Probably your environment is not setup correctly.
