### ISSUE TITLE
GPU error using docker on Windows

### ISSUE THREAD

**Issue by DongDChen** [Deep-MI/FastSurfer#329]
## Question/Support Request

...
I use docker version, and the command is as follows:
docker run --gpus all -v I:/huashan_preprocess/nii:/data -v D:/freesurfer_linux:/output -v D:/freesurfer_linux/my_fs_license_dir:/fs_license --rm deepmi/fastsurfer:latest --fs_license /fs_license/license.txt --t1 /data/Bi_Ai_Xiu/t1_mprage_3D_20180912141453_19.nii.gz --sid Bi_Ai_Xiu --sd /output --parallel

error shows:
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown.

![1685948877048](https://github.com/Deep-MI/FastSurfer/assets/20920484/74ab5b5f-22ba-4945-947b-9dc028e79635)

**Comment by LeHenschel** [comment]
This is an error with Docker on Windows not FastSurfer. See the following thread for a potential workaround:
https://github.com/NVIDIA/nvidia-container-toolkit/issues/155

**Comment by DongDChen** [comment]
Thank you very much, I'll check that.

**Comment by m-reuter** [comment]
See also https://github.com/Deep-MI/FastSurfer/blob/stable/INSTALL.md#windows
