### ISSUE TITLE
[Question] Space of orig and aparc.DKTatlas+aseg

### ISSUE THREAD

**Issue by tashrifbillah** [Deep-MI/FastSurfer#33]
The training [input](https://github.com/Deep-MI/FastSurfer/blob/master/FastSurferCNN/generate_hdf5.py#L172) for FastSurfer is `mrig/orig.mgz` and `mri/aparc.DKTatlas+aseg.mgz`. My question--are the two files in any standard space such as MNI? I know the two are created by FreeSurfer but I do not know the answer.

I noticed at the top of FreeSurfer, `mri_convert -c` is applied that makes `orig.mgz` with the following:

```vim
voxel to ras transform:
               -1.0000   0.0000   0.0000   128.5000
                0.0000   0.0000   1.0000  -127.5000
                0.0000  -1.0000   0.0000   128.5000
                0.0000   0.0000   0.0000     1.0000
```

**Comment by m-reuter** [comment]
No this is still in subject space, the only thing FS does is conform it to 1mm isotropic and rotate it to a standard position (according to the matrix that you show). This ensures that the correct directions are along the right axes. Further, it robustly maps intensites to UCHAR (0..255). 
If your inputs are not conform, FastSurfer should make them conform (we have a python script that basically mimics the mri_convert conform command).

**Comment by tashrifbillah** [comment]
Hi @m-reuter ,

I understand the conform step is materialized via `scipy.ndimage.affine_transform`:
https://github.com/Deep-MI/FastSurfer/blob/196d9f7c021cc7961264f6cfa9ea31f4e2423cdd/FastSurferCNN/data_loader/conform.py#L66

```python
new_data = affine_transform(img.get_data(), inv(vox2vox), output_shape=out_shape, order=order)
```


cc @sbouix.

**Comment by m-reuter** [comment]
Yes, the voxel to voxel transform can have scaling if the voxel sizes are not already 1mm isotropic.
