### ISSUE TITLE
freesurfer getfullpath needed

### ISSUE THREAD

**Issue by bloyl** [Deep-MI/FastSurfer#330]
## Description
When generating surfaces, the freesurfer program `getfullpath` is needed by `recon-all` and by `talairach_avi`. It is however not installed in the dockerhub containers ( at least not v2.0.4) versions

Adding the file `/opt/freesurfer/bin` solves the issue. 

I suspect adding this to `install_fs_pruned.sh` would solve the issue.

**Comment by m-reuter** [comment]
Thanks for reporting this. What error did you get and what was the command you used? We have successfully processed surfaces with those docker images. 

Thanks.

**Comment by m-reuter** [comment]
@bloyl can you provide more info please so that we can try to replicate this?
