### ISSUE TITLE
Fastsurfer not generating ?.sphere.reg / Fastsurfer thickness into a table

### ISSUE THREAD

**Issue by NeuroJulian** [Deep-MI/FastSurfer#333]
### Hi!
Usually when I use Freesurfer, I'm generating thickness stats from aparcstats2table (I just want CSV with cortical thickness of structures in Destrieux Atlas). I followed steps in issue #89, but to use these commands (eg. `mris_ca_label -l label/lh.cortex.label -aseg mri/aseg.presurf.mgz 1 lh lh.sphere.reg $FREESURFER_HOME/average/lh.destrieux.simple.2009-07-29.gcs label/lh.aparc.a2009s.annot`) I need `lh.sphere.reg`, which should be generated by default.

## Environment
 - FastSurfer Version: 2.1.1 (latest)
 - FreeSurfer Version: 7.4.1 (latest)
 - OS: Windows 10 (Ubuntu 20.04 WSL)
 - CPU: Intel i7-3930K
 - GPU: Nvidia RTX 3060
 
### Execution

```
time docker run --gpus all \
           -v /home/julian/PD:/data \
           -v /home/julian/PD/fastsurfer:/output \
           -v /home/julian/freesurfer:/fs_license \
           --rm --user $(id -u):$(id -g)  deepmi/fastsurfer:latest \
           --fs_license /fs_license/license.txt \
           --t1 /data/1/orig.mgz \
           --sd /output \
           --sid 1 \
           --parallel --threads 12
```

### Fastsurfer generated directory
```
├── label
│   ├── lh.cortex+hipamyg.label
│   ├── lh.cortex.label
│   ├── lh.nofix.cortex.label
│   ├── rh.cortex+hipamyg.label
│   ├── rh.cortex.label
│   └── rh.nofix.cortex.label
├── mri
│   ├── T1.mgz
│   ├── antsdn.brain.mgz
│   ├── aparc.DKTatlas+aseg.deep.mgz
│   ├── aparc.DKTatlas+aseg.deep.withCC.mgz
│   ├── aparc.DKTatlas+aseg.orig.mgz
│   ├── aseg.auto.mgz
│   ├── aseg.auto_noCCseg.mgz
│   ├── aseg.presurf.mgz
│   ├── brain.finalsurfs.mgz
│   ├── brain.mgz
│   ├── brainmask.mgz
│   ├── cerebellum.CerebNet.nii.gz
│   ├── filled-pretess127.mgz
│   ├── filled-pretess255.mgz
│   ├── filled.auto.mgz
│   ├── filled.mgz
│   ├── lh.surface.defects.mgz
│   ├── mask.mgz
│   ├── norm.mgz
│   ├── nu.mgz
│   ├── orig
│   ├── orig.mgz
│   ├── orig_nu.mgz
│   ├── rawavg.mgz -> orig.mgz
│   ├── rh.surface.defects.mgz
│   ├── segment.dat
│   ├── tmp
│   ├── transforms
│   │   ├── bak
│   │   ├── cc_up.lta
│   │   ├── talairach.auto.xfm
│   │   ├── talairach.auto.xfm.lta
│   │   ├── talairach.lta -> talairach.xfm.lta
│   │   ├── talairach.xfm
│   │   ├── talairach.xfm.lta
│   │   ├── talairach_avi.log
│   │   └── talairach_with_skull.lta -> talairach.xfm.lta
│   ├── wm.asegedit.mgz
│   ├── wm.mgz
│   └── wm.seg.mgz
├── scripts
│   ├── build-stamp.txt
│   ├── deep-seg.log
│   ├── defect2seg.log
│   ├── lastcall.build-stamp.txt
│   ├── lh.processing.cmdf
│   ├── patchdir.txt
│   ├── ponscc.cut.log
│   ├── recon-all-status.log
│   ├── recon-all.cmd
│   ├── recon-all.done
│   ├── recon-all.env
│   ├── recon-all.env.bak
│   ├── recon-all.local-copy
│   ├── recon-all.log
│   ├── recon-config.yaml
│   ├── recon-surf.log
│   ├── rh.processing.cmdf
│   └── unknown-args.txt
├── stats
│   ├── aseg+DKT.stats
│   └── cerebellum.CerebNet.stats
├── surf
│   ├── autodet.gw.stats.lh.dat
│   ├── autodet.gw.stats.rh.dat
│   ├── lh.defect_borders
│   ├── lh.defect_chull
│   ├── lh.defect_labels
│   ├── lh.defects.pointset
│   ├── lh.inflated
│   ├── lh.inflated.H
│   ├── lh.inflated.K
│   ├── lh.inflated.nofix
│   ├── lh.orig
│   ├── lh.orig.nofix
│   ├── lh.orig.premesh
│   ├── lh.qsphere.nofix
│   ├── lh.smoothwm
│   ├── lh.smoothwm.nofix
│   ├── lh.sulc
│   ├── lh.white.H -> lh.white.preaparc.H
│   ├── lh.white.K -> lh.white.preaparc.K
│   ├── lh.white.preaparc
│   ├── lh.white.preaparc.H
│   ├── lh.white.preaparc.K
│   ├── rh.defect_borders
│   ├── rh.defect_chull
│   ├── rh.defect_labels
│   ├── rh.defects.pointset
│   ├── rh.inflated
│   ├── rh.inflated.H
│   ├── rh.inflated.K
│   ├── rh.inflated.nofix
│   ├── rh.orig
│   ├── rh.orig.nofix
│   ├── rh.orig.premesh
│   ├── rh.qsphere.nofix
│   ├── rh.smoothwm
│   ├── rh.smoothwm.nofix
│   ├── rh.sulc
│   ├── rh.white.H -> rh.white.preaparc.H
│   ├── rh.white.K -> rh.white.preaparc.K
│   ├── rh.white.preaparc
│   ├── rh.white.preaparc.H
│   └── rh.white.preaparc.K
├── tmp
├── touch
│   ├── asegmerge.touch
│   ├── fill.touch
│   ├── inorm2.touch
│   ├── lh.autodet.gw.stats.touch
│   ├── lh.cortex+hipamyg.touch
│   ├── lh.cortex.touch
│   ├── lh.inflate.H.K.touch
│   ├── lh.inflate1.touch
│   ├── lh.inflate2.touch
│   ├── lh.qsphere.touch
│   ├── lh.smoothwm2.touch
│   ├── lh.topofix.touch
│   ├── lh.white.H.K.touch
│   ├── lh.white.preaparc.touch
│   ├── rh.autodet.gw.stats.touch
│   ├── rh.cortex+hipamyg.touch
│   ├── rh.cortex.touch
│   ├── rh.inflate.H.K.touch
│   ├── rh.inflate1.touch
│   ├── rh.inflate2.touch
│   ├── rh.qsphere.touch
│   ├── rh.smoothwm2.touch
│   ├── rh.topofix.touch
│   ├── rh.white.H.K.touch
│   ├── rh.white.preaparc.touch
│   └── wmsegment.touch
└── trash	
```
### recon-all.log
[https://pastebin.com/eNYdZrRW](https://pastebin.com/eNYdZrRW)

 So, there is any other method which can generate cortical thickness into a table?

**Thank You very much**
_Julian_

**Comment by LeHenschel** [comment]
Hey,

looks to me like your fastsurfer run crashed because there is also no pial surface generated. You need to check the recon-surf.log, not the recon-all.log.

Kind regards,
Leonie

**Comment by NeuroJulian** [comment]
### Hey,

Thank You for the quick reply :)

Here's [recon-surf.log](https://pastebin.com/zMcsES6p)

Errors which I found:
`inflating to sphere (rms error < 2.00)`
`final distance error %100000.00`

**Thank You very much,**
_Julian_

**Comment by LeHenschel** [comment]
Something goes wrong in the mapping from the labels to the surface (Command terminated by signal 9):

`mris_sample_parc -ct /opt/freesurfer/average/colortable_desikan_killiany.txt -file /fastsurfer/recon_surf/rh.DKTatlaslookup.txt -projmm 0.6 -f 5  -surf white.preaparc 1 rh aparc.DKTatlas+aseg.orig.mgz aparc.DKTatlas.mapped.prefix.annot`

Try to run this command alone and see what error message comes up.

**Comment by NeuroJulian** [comment]
```
d.prefix.annot
embedding color table /opt/freesurfer/average/colortable_desikan_killiany.txt into output annot file
using  as translation fname
projecting 0.60 mm along surface normal
applying mode filter 5 times to parcellation
using white.preaparc as surface name
reading parcellation volume from /home/julian/freesurfer/subjects/1/mri/aparc.DKTatlas+aseg.orig.mgz...
error: mghRead(/home/julian/freesurfer/subjects/1/mri/aparc.DKTatlas+aseg.orig.mgz, -1): could not open file
error: mris_sample_parc: could not read input volume /home/julian/freesurfer/subjects/1/mri/aparc.DKTatlas+aseg.orig.mgz
```


I tried to open the  `aparc.DKTatlas+aseg.orig.mgz` with freeview, failed to load MRI.

**Comment by m-reuter** [comment]
two things you could try:
- run everything from scratch but use a different subject name. Maybe some of the commands interpret the "1" not correctly. name it subject1 or something.
- if that fails, run everything from scratch in docker, because something could be setup incorrectly in your local install.

**Comment by NeuroJulian** [comment]
I forgot to change SUBJECTS_DIR...

Here's updated error:
`d.prefix.annot
embedding color table /opt/freesurfer/average/colortable_desikan_killiany.txt into output annot file
using  as translation fname
projecting 0.60 mm along surface normal
applying mode filter 5 times to parcellation
using white.preaparc as surface name
reading parcellation volume from /home/julian/PD/fastsurfer/1/mri/aparc.DKTatlas+aseg.orig.mgz...
reading input surface /home/julian/PD/fastsurfer/1/surf/rh.white.preaparc...
error: No such file or directory
error: CTABreadASCII(/opt/freesurfer/average/colortable_desikan_killiany.txt): could not open file
error: No such file or directory
error: mris_sample_parc: could not read color file /opt/freesurfer/average/colortable_desikan_killiany.txt`

So I copied average folder from my freesurfer directory (/home/julian/freesurfer) to /opt/freesurfer/average 
` mris_sample_parc -ct /opt/freesurfer/average/colortable_desikan_killiany.txt -file /fastsurfer/recon_surf/rh.DKTatlaslookup.txt -projmm 0.6 -f 5  -surf white.preaparc 1 rh aparc.DKTatlas+aseg.orig.mgz aparc.DKTatlas.mapped.prefix.annot
embedding color table /opt/freesurfer/average/colortable_desikan_killiany.txt into output annot file
using  as translation fname
projecting 0.60 mm along surface normal
applying mode filter 5 times to parcellation
using white.preaparc as surface name
reading parcellation volume from /home/julian/PD/fastsurfer/1/mri/aparc.DKTatlas+aseg.orig.mgz...
reading input surface /home/julian/PD/fastsurfer/1/surf/rh.white.preaparc...
Killed`

**Comment by NeuroJulian** [comment]
I'll try run Fastsurfer on different subject.
Also I have question about generating thickness table - is this good way?

**Comment by m-reuter** [comment]
Yes that is the correct way.

**Comment by NeuroJulian** [comment]
### Hi!
The problem was in amount of RAM (I have 16GB, I've increased SWAP to 64GB). Running recon-surf consume all of my RAM and over 30GB of swap (in older versions of FastSurfer, the problem with RAM size didn't occur). I've downgraded FreeSurfer to 7.3.2 version, but it did nothing, constantly it's consuming a lot of memory. Installing other distro in WSL and reinstalling docker with FastSurfer also doesn't help. However one problem fixed - all of generated files are correct.

_Thank You very much for Your help_
**_Julian_**

**Comment by m-reuter** [comment]
Thanks for reporting. This is indeed strange as FreeSurfer (FastSurfer uses FreeSurfer tools for the surfaces) does not require that much. Even for a VM they recommend 8-12GB and less if you run it natively. So I think this has to do with the Windows WSL somehow. If you need to run a lot of cases, probably best to install dual boot with ubuntu.
