### ISSUE TITLE
Training crashes wen trying to calculate MIoU for when DATA.CLASS_OPTIONS == ['aseg'] is set

### ISSUE THREAD

**Issue by mafortin** [Deep-MI/FastSurfer#346]
## Description

I've been doing few successful retrainings of the FastSurferVINN network up to now to produce subcortical segmentations only (i.e., only aseg, not aseg+aparc) with my own data. However, I've discovered that when I explicitly set *DATA.CLASS_OPTIONS* to ['aseg'] it crashes at the end of the first validation process (see screenshot below). 

I also discovered that if I don't explicitly set this flag, it doesn't crash but it tries to calculate the quantitative metrics for all cortex parcellations resulting in NaN values for the average metrics across volumes. While not setting this flag enables me to have a network that learns, it is slightly inconvenient when I try to get the values of these quantitative metrics to evaluate my netowrk learning process.

## Steps to Reproduce

Error message:
![image](https://github.com/Deep-MI/FastSurfer/assets/51452174/5e60597d-9a25-407d-9248-66a4f24139f7)

## Expected Behavior

To not crash when I set the *DATA.CLASS_OPTIONS* properly to aseg.

## Environment
 - FastSurfer Version: v2.0.4 (i think) **developer version** (I cloned the dev branch on 04/05/23).
 - OS: Linux Ubuntu 20.04
 - CPU: 
 - GPU: Tesla P100-PCIE 16 Gb

pip freeze outputs:
![image](https://github.com/Deep-MI/FastSurfer/assets/51452174/c709ccdf-ab7e-4891-b0ba-d2b0c54f2f3b)

### Execution

Flags used for the *run_model.py* script:
![image](https://github.com/Deep-MI/FastSurfer/assets/51452174/557a145c-8a87-45ba-b75f-b825cbbcd937)
(**Working directory being FastSurfer/FastSurferCNN/**)

## Additional Context

Thanks in advance for your feedback! :)

**Comment by LeHenschel** [comment]
What do you have set for the MODEL.NUM_CLASSES? Is this the same length as the aseg labels?

**Comment by mafortin** [comment]
@LeHenschel I set it to 36 which is the number of labels in my LUT. Still crashes at index 33

**Comment by LeHenschel** [comment]
The problem is, that the class names for aseg only have 33 entries, which is read from here: https://github.com/Deep-MI/FastSurfer/blob/stable/FastSurferCNN/config/global_var.py#L59C16-L93C10

So you need to check which additional labels you have in your LUT and add them there. 

@dkuegler , I think it would be better to read the class names from the provided LUT instead of hard coding them

**Comment by mafortin** [comment]
@LeHenschel as expected, by modifying manually *CLASS_DICT* it worked. 

As you mentioned, since we already provide the LUT, it would make sense to read it from it instead of hard-coding it.

Thanks for your quick help! :)

**Comment by dkuegler** [comment]
> The problem is, that the class names for aseg only have 33 entries, which is read from here: https://github.com/Deep-MI/FastSurfer/blob/stable/FastSurferCNN/config/global_var.py#L59C16-L93C10
> 
> So you need to check which additional labels you have in your LUT and add them there.
> 
> @dkuegler , I think it would be better to read the class names from the provided LUT instead of hard coding them

I think it is always better to dynamically read labels. I think we should get rid of labels in config files in the long run. 
I'd say this is a pretty low-priority thing to do, but I would prefer mappings of labels similar to CerebNet, see https://github.com/Deep-MI/FastSurfer/blob/stable/CerebNet/config/CerebNet2FreeSurfer.json , as these mappings / equivalences have to be stored somewhere, but it should be way more obvious and easy to understand than right now....
