### ISSUE TITLE
Were the segonly docker images removed from docker hub?

### ISSUE THREAD

**Issue by fw-ashmistry** [Deep-MI/FastSurfer#347]
## Question/Support Request
Were the segonly docker images removed from docker hub? Was trying to build `deepmi/fastsurfer:segonly-gpu-v1.1.1` and noticed that it wasn't found. Looks like only the Complete Fastsurfer images are available
...

**Comment by m-reuter** [comment]
Yes, we stopped publishing the seg only and surf only images to reduce complexity. The surf pipeline only increases the size marginally. We have flags to run only surf or seg in the full package. Alternatively users can also specify run_prediction as the entry point directly (in case default run_fastsurfer is not sufficient).

**Comment by dkuegler** [comment]
Just do add that tiny bit of documentation @ashmistry36 
replace `deepmi/fastsurfer:segonly-gpu-v1.1.1` to `--entrypoint "python /fastsurfer/FastSurferCNN/run_prediction.py" deepmi/fastsurfer:latest` to get the segonly interface in current images.

**Comment by LeHenschel** [comment]
Unless you want to use the csv-option to process multiple images, you can also just add the --seg_only flag, in wich case there is no need to redefine the entrypoint.

`... deepmi/fastsurfer:latest --sd $SUBJECTS_DIR --sid $SID --t1 $path_to_t1 --seg_only`
