### ISSUE TITLE
WSL2: lh.white not created

### ISSUE THREAD

**Issue by stanmarecek** [Deep-MI/FastSurfer#353]
Hello, 
I am trying to use Fastsurfer as a faster alternative to Freesurfer, but (at the very least) my lh.white and rh.white seems to be missing in all subjects I run?
I use WSL 2 (Ubuntu 22.04.2 LTS), and singularity container (ver 3.11.4-jammy). The command I use is: 

singularity exec --nv -B /mnt/c/Users/sttan/Desktop/cortical_thickness/:/data \
                  -B /mnt/d/PGS/fastsurfer:/output \
                  -B /usr/local/freesurfer/7.4.1:/fs_license \
                   ./fastsurfer-gpu.sif \
                   /fastsurfer/run_fastsurfer.sh \
                  --fs_license /fs_license/license.txt \
                  --t1 /data/RBDNORMA01/1/t1.nii.gz \
                  --sid RBDNORMA01 --sd /output \
                  --parallel

I am attaching files that may be relevant.

Best regards,
Stan

![surf](https://github.com/Deep-MI/FastSurfer/assets/115405211/5d6a904b-fc90-4a0c-ba48-e4ab5dcba3e0)
[recon-all-status.log](https://github.com/Deep-MI/FastSurfer/files/12063663/recon-all-status.log)
[recon-all.log](https://github.com/Deep-MI/FastSurfer/files/12063664/recon-all.log)
[recon-all.done.txt](https://github.com/Deep-MI/FastSurfer/files/12063666/recon-all.done.txt)

**Comment by m-reuter** [comment]
Hi Stan, 
we do not have much experience with WSL, but those files should be there. can you add the recon-surf.log file thanks.

**Comment by stanmarecek** [comment]
Sure, here it is 
[recon-surf.log](https://github.com/Deep-MI/FastSurfer/files/12064037/recon-surf.log)

**Comment by m-reuter** [comment]
Hmm it fails here:
```
mris_sample_parc -ct /opt/freesurfer/average/colortable_desikan_killiany.txt \
     -file /fastsurfer/recon_surf/rh.DKTatlaslookup.txt -projmm 0.6 -f 5  -surf white.preaparc \
     RBDNORMA01 rh aparc.DKTatlas+aseg.orig.mgz aparc.DKTatlas.mapped.prefix.annot 

Command terminated by signal 9
```

This is the step where we map the deep learning-based segmentation to the white.preaparc surface. It does not give more details. Ways to debug this:

- try on a linux system with docker or singularity to make sure it is not a WSL thing (like limited memory etc). 
- visually inspect the white.preaparc surface and the segmentations to make sure inputs are not already corrupted. Sometimes errors occur earlier in the stream silently. 
- start the container interactively , change to that directory, setup SUBJECTS_DIR and FREESURFER_HOME env variables and run the command directly, maybe it gives more detailed error messages on the screen (although I doubt that). 

If all else fails, we could try to replicate the issue on our side, but would need the input image.

**Comment by stanmarecek** [comment]
I will look into it write back. Thank you!

**Comment by stanmarecek** [comment]
dmesg | grep -i 'killed process' showed, that the process was killed because of insufficient memory. I had to allocate more memory to WSL 2 and it now it works. Thank you for your help!
