### ISSUE TITLE
Surface Recon fails on GPU but not on CPU (AWS GPU and CPU instance)

### ISSUE THREAD

**Issue by fw-ashmistry** [Deep-MI/FastSurfer#356]
## Question/Support Request

I am running surface reconstruction through a subprocess that runs `./recon-surf.sh --sd /output/Output --sid T1w --t1 /output/Output/conformed_sub-RC4210_ses-1_T1w.nii.gz --asegdkt_segfile /output/Output/sub-RC4210_ses-1_T1w.nii.gz/mri/aparc.DKTatlas+aseg.deep.mgz --allow_root`. The recon fails when run on a GPU instance that has 16 GB mem available, however doesn't fail on a CPU with 8 GB mem. `--threads` are set to default which is `1`, I am running the pipeline sequentially so left hemi first then right. The memory usage spikes considerably (~11 GB) for a few seconds during `mris_sample_parc`, and then I get `error: mris_sample_parc: LabelAlloc() could not allocate 0-sized vector\x00'` and it crashes. I run the same exact command, but on my CPU and recon runs perfectly fine. It does get heavily loaded during `mris_sample_parc` but it's able to struggle through and move onto the next step. Given that there is 8 GB mem on my CPU instance it's understandable that it would take `recon-surf-run-time-hours  2.077`, much longer than the 60 min that the docs refer to.

I know that recon doesn't use the GPU at all and the reason why a GPU instance is used (preferred) because I run the segmentation prior to the recon in a single run, and like to take advantage of the ~1 min segmentation time.

These are the dimensions of my input t1 file after running `fslinfo sub-RC4210_ses-1_T1w.nii.gz`
```
pixdim1		1.000000
pixdim2		1.000000
pixdim3		1.000000
pixdim4		0.007629
```
The GPU instance **has been successful** in running the recon for a few runs. The dimensions of those file(s) are:

```
pixdim1		0.976562
pixdim2		0.976562
pixdim3		1.000000
pixdim4		1.760000
```

Anybody have any ideas? Is it something to do with dim4 or is it really just something with with the instances I'm using.

**Comment by m-reuter** [comment]
Hi, 
The high memory requirement during mri_sample_parc is strange. Maybe the freesurfer folks know why this is necessary ( or maybe they are not yet aware of this)? For that you can check their email support list and archive. 

Wrt the input, you need to pass 3d images. We should check for that and stop if 4d is passed. That could cause all kinds of problems. Can you run freesurfers mri_info on the inputs? Also on the images that come out of our segmentation after conforming?

**Comment by fw-ashmistry** [comment]
You're right, passing in 3D images results in successful recon runs. Thanks!

I ran `mri_info --conformed` on those input T1s' (that were 4D) segmentation outputs and they are conformed and 3D. (probably got lucky with recon finishing successfully despite those T1s not being 3D).
