### ISSUE TITLE
Does reconstruction utilize GPU?

### ISSUE THREAD

**Issue by fw-ashmistry** [Deep-MI/FastSurfer#357]
## Question/Support Request

Does reconstruction utilize GPU? According to the docs it should take 60 min, but I noticed that on our GPU it takes 2 hours. Also noticed that running `nvidia-smi` during it shows that no processes are using the GPU. What were the arguments for that 60 min benchmark (threads and run hemi in parallel?)? 

I'm running using default threads (1) and running sequentially, left hemi then right.

**Comment by m-reuter** [comment]
Hi, the segmentation modules use the GPU but the surface reconstruction is CPU only. For 1h you probably need to run --parallel  and maybe increase threats also. The actual runtime varies and depends on the quality of the images etc. For example in some cases, it takes much longer to fix the topology of the surface than in others.
