### ISSUE TITLE
FastSurfer environment compatibility with Ubuntu 20.04

### ISSUE THREAD

**Issue by dkuegler** [Deep-MI/FastSurfer#359]
### Known bug/limitation

If you are getting an error message like
```
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by <pandas/sk-image/...>)
```

### Solution

If you are using **Ubuntu 20.04**, you will need to upgrade to a newer version of libstdc++, as some 'newer' python packages need GLIBCXX 3.4.29, which is not distributed with Ubuntu 20.04 by default.

```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt install -y g++-11
```

**Comment by ssghirripa** [comment]
Hi there, I am having this issue but I am trying to run a native install of FastSurfer on a university HPC and therefore don't have root privileges. Do you have any suggestions for how this might be solved in this situation?

**Comment by m-reuter** [comment]
Hi, maybe you can ask the HPC IT if they can install singularity. That would allow you to run our singularity container ( https://github.com/Deep-MI/FastSurfer/tree/dev/Singularity#readme ) and you would have the fully supported system. Lots of HPC allow singularity (and not docker) as it is considered safer.
