### ISSUE TITLE
Conform.py function deforms some MRI scans

### ISSUE THREAD

**Issue by MehriB** [Deep-MI/FastSurfer#36]
Hi,

FastSurfer is a great work, I have been using it since it was released, I have a question though.
For some images, I dont know why the conform.py function deforms the images?
The files are big to upload here, so I uploaded only a screenshot. Please find the full files before and after the conform.py function here:
https://mega.nz/folder/Bo8z2KgR#xlamrUXuJDwSWBq8fEobIg

Could you please help me why this happens, because FastSufer does not give a reasonable segmentation on the files that are deformed during the preprocessing.

![before_68](https://user-images.githubusercontent.com/45103993/97159157-bd0b1080-177a-11eb-962f-083551997133.png)
![after_68](https://user-images.githubusercontent.com/45103993/97159167-c0060100-177a-11eb-90d6-d7ce17743699.png)

Thank you,
Mehri

**Comment by MehriB** [comment]
Some additional info:

The voxel spacing of this image is 0.5x0.5x1 mm
and the dimension is 512x512x148
Orientation: RAI
Intensity range: 0 - 234e+04

These should be the factors that change by the "conform" function.

I think the original voxel spacing of the image plays a big role, because for me, the closer the voxel spacing of the original image is to 1x1x1mm, the better result I get. This gets worse if the spacing is less than 1 rather than more. 

Best,
Mehri

**Comment by m-reuter** [comment]
Hi MehriB , 
thanks, this could be a bug in conform.py as it should not deform anything. It should reslice it to 1mm isotropic. We will take a look. Until then you can use mri_convert --conform input output to conform the files and try running those.

**Comment by MehriB** [comment]
Thank you for the quick reply.

Actually I only need the segmentation and not the recon, so I dont have FreeSurfer (I have just the license).
I just created a virtual env with the requirements of FastSurfer and started to use it.

If I am not wrong, mri_convert is from FreeSurfer. If yes, then I will try to install FreeSurfer.

**Comment by m-reuter** [comment]
Yes, it is a freesurfer command. Your situation is actually why we implemented a python alternative to the FS conform command. So that people can run the segmentation without having to install FS at all.

**Comment by MehriB** [comment]
Yeah it is a very good idea to have a python version of it.
I just tried with the mri_convert of freesurfer and the image looks fine, it is not deformed. 
So, as you mentioned probably there is a bug in the conform.py

**Comment by LeHenschel** [comment]
Hey MehriB,

I checked the files you uploaded and it turns out that the problem here is actually an error in the header of your nifti-file. Specifically, the sform is wrong (the qform on the other hand, is correct). Unfortunately, nibabel constructs the affine by default using the sform (https://nipy.org/nibabel/nifti_images.html#choosing-the-image-affine) which in this case leads to the scaling issues you observe. 
```bash
import nibabel as nib
img = nib.load("/data/before_68.nii.gz")
print(img.affine)

# Wrong affine --> voxel sizes not correctly represented!
array([[ -1.        ,   0.        ,   0.        , 140.3710022 ],
       [  0.        ,  -1.        ,   0.        , 206.22599792],
       [  0.        ,   0.        ,   1.        , -52.17739868],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

# Wrong sform which leads to the wrong affine:
print(img.get_sform())
array([[ -1.        ,   0.        ,   0.        , 140.3710022 ],
       [  0.        ,  -1.        ,   0.        , 206.22599792],
       [  0.        ,   0.        ,   1.        , -52.17739868],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

# Correct qform which leads to correct affine:
print(img.get_qform())
array([[ -0.50779998,   0.        ,   0.        , 140.3710022 ],
       [  0.        ,  -0.50779998,   0.        , 206.22599792],
       [  0.        ,   0.        ,   1.        , -52.17739868],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

# You can also see the wrong sform entries in the header (srow_x, srow_y, srow_z)
print(img.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 512 512 148   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.     0.5078 0.5078 1.     0.     0.     0.     0.    ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 1.0
qoffset_x       : 140.371
qoffset_y       : 206.226
qoffset_z       : -52.1774
srow_x          : [ -1.      0.      0.    140.371]
srow_y          : [  0.     -1.      0.    206.226]
srow_z          : [  0.       0.       1.     -52.1774]
intent_name     : b''
magic           : b'n+1'

```

FreeSurfer's mri_convert detects the error by comparing the Vox2RAS Matrix with the defined voxel sizes and automatically corrects the issue (and also issues a warning):

```bash
mri_convert before_68.nii.gz after_68_mri_convert.nii.gz 

reading from before_68.nii.gz...
WARNING: MRIsetRas2VoxFromMatrix(): voxels sizes are inconsistent
   (0.5078,1) (0.5078,1) (1,1) 
This is probably due to shear in the vox2ras matrix
Input Vox2RAS ------
-1.00000   0.00000   0.00000   140.37100;
 0.00000  -1.00000   0.00000   206.22600;
 0.00000   0.00000   1.00000  -52.17740;
 0.00000   0.00000   0.00000   0.00000;
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, 0, 0)
j_ras = (0, -1, 0)
k_ras = (0, 0, 1)
writing to after_68_mri_convert.nii.gz...
```
Now, if you e.g. set the sform with the correct qform and run conform.py on it, the output is correct as well (no deformation):

```bash
import nibabel as nib
img = nib.load("/data/before_68.nii.gz")
corr_affine = img.get_qform()
img.set_sform(corr_affine)
img.update_header()
img.to_filename('/data/mri/before_fix_sform_68.nii.gz')
```

```bash
cd /FastSurfer/FastSurferCNN/data_loader 
python3 conform.py -i /data/mri/before_fix_sform_68.nii.gz -o /data/mri/before_fix_sform_68_conform.mgz
```

![screenshot_rescale_issue](https://user-images.githubusercontent.com/31760921/97287587-0fb0ff00-1845-11eb-808a-01c7df99189e.png)

I will look into options to catch this type of error in the conform.py script. 
I hope this helps. 

Best,
Leonie

**Comment by MehriB** [comment]
Thank you for the complete explanations. It is totally clear now :) 
I will double check my images and make sure the headers are correct before feeding them into FastSurfer. 

Best,
Mehri

**Comment by LeHenschel** [comment]
Great :). glad we could clear everything up.

I now also added some checks for the affine if the input is a nifti image with commit 0235f90. We now check for differences in qform and sform-transform as well as differences in the voxel sizes stored in the header and affine and issue Warnings in both cases. I am therefore closing this issue for now.
