### ISSUE TITLE
About docker cpu on windows！

### ISSUE THREAD

**Issue by NewboySoCool** [Deep-MI/FastSurfer#361]
Hi, I am a freshman to 
1、 How to use this FastSurfer tools to get a segmentation image for 6 tissues, including Cortical WhiteMatter, Cortical Grey Matter, Cerebellum White Matter, Cerebellum Cortex, Brain Stem, and Cerebrospinal Fluid. Like the following images. Can you provide detail code?
![image](https://github.com/Deep-MI/FastSurfer/assets/93995539/a75e807b-1a55-4492-9ffe-7da9e0f93a6f)

2、when use docker on windows with cpu,  ERROR: Flag --no_biasfield unrecognized. ERROR: Flag --cereb_segfile unrecognized\ERROR: Flag --no_cereb unrecognized. What should I do ?
![image](https://github.com/Deep-MI/FastSurfer/assets/93995539/61c8d903-5ff6-4348-ba29-f7d9b543a562)

3、I get aparc.DKTatlas+aseg.deep.mgz, but why left part is different part to right?
![image](https://github.com/Deep-MI/FastSurfer/assets/93995539/ea75c313-d701-4468-8fe3-4ba7efa9666e)

**Comment by LeHenschel** [comment]
Hey,

> How to use this FastSurfer tools to get a segmentation image for 6 tissues, including Cortical WhiteMatter, Cortical Grey Matter, Cerebellum White Matter, Cere�bellum Cortex, Brain Stem, and Cerebrospinal Fluid. Like the following images

I am not sure where the image is from. It looks like the subcortical structures are merged into the cortical label as well. You can run FastSurfer and would have to check which structures to merge together to get your desired segmentation output. Commands to generate the aparc segmentation are given in the README (https://github.com/Deep-MI/FastSurfer#example-1-fastsurfer-docker).


> when use docker on windows with cpu, ERROR: Flag --no_biasfield unrecognized. ERROR: Flag --cereb_segfile unrecognized\ERROR: Flag --no_cereb unrecognized. What should I do ?

What version of FastSurfer are you using? The flags are new and therefore only exist in our newest release.

> I get aparc.DKTatlas+aseg.deep.mgz, but why left part is different part to right?

The segmentation differentiates between left and right hemisphere. Therefore, the IDs differ. If you want to display them as the same color, you would have to use a look up table.

**Comment by NewboySoCool** [comment]
> f you want to display them as the same color, you would have to use a look up table.

Thanks，but I'm not know about the loook up table.ks，but I'm not know about the loook up table.

**Comment by LeHenschel** [comment]
[FreeSurferColorLUT.txt](https://github.com/Deep-MI/FastSurfer/files/12259362/FreeSurferColorLUT.txt)
We follow the freesurfer color LUT

**Comment by NewboySoCool** [comment]
> [FreeSurferColorLUT.txt](https://github.com/Deep-MI/FastSurfer/files/12259362/FreeSurferColorLUT.txt) We follow the freesurfer color LUT

Thanks for your reply，but I don't know how to use the table when I run the docker? Can you provide the detail code?

**Comment by LeHenschel** [comment]
You do not need it for docker. The IDs are correct as is, i.e. the left- and right-hemisphere structures have different IDs. if you want to DISPLAY them with the same color in your GUI, you can often times use a look-up table to make them look identical (e.g. in Freeview). If you want them to BE identical (and remove any lateralization) you have to code that mapping.

**Comment by NewboySoCool** [comment]
> You do not need it for docker. The IDs are correct as is, i.e. the left- and right-hemisphere structures have different IDs. if you want to DISPLAY them with the same color in your GUI, you can often times use a look-up table to make them look identical (e.g. in Freeview). If you want them to BE identical (and remove any lateralization) you have to code that mapping.

Thanks again，I‘ll have a try!

**Comment by NewboySoCool** [comment]
> You do not need it for docker. The IDs are correct as is, i.e. the left- and right-hemisphere structures have different IDs. if you want to DISPLAY them with the same color in your GUI, you can often times use a look-up table to make them look identical (e.g. in Freeview). If you want them to BE identical (and remove any lateralization) you have to code that mapping.

Sorry, I haven't used freeview before, so, if I wanna display with 3D Slicer, is there a way to display them with the same color?

**Comment by m-reuter** [comment]
That is a question that you need to ask the slicer crew. For Freeview you can look at their wiki and tutorials. 
Or if you know how to program, you can open the segmentation, replace the id's from one hemisphere with the one from the other and save it as a separate file. You will loose all the lateralisation information that way, but when you open that image it will display those regions with the same color. Not sure why you would want to do that, but it is easy enough to merge or replace labels.

**Comment by NewboySoCool** [comment]
> That is a question that you need to ask the slicer crew. For Freeview you can look at their wiki and tutorials. Or if you know how to program, you can open the segmentation, replace the id's from one hemisphere with the one from the other and save it as a separate file. You will loose all the lateralisation information that way, but when you open that image it will display those regions with the same color. Not sure why you would want to do that, but it is easy enough to merge or replace labels.

Ok, It's nice of you,  I'll have a try, thanks again!

**Comment by NewboySoCool** [comment]
> That is a question that you need to ask the slicer crew. For Freeview you can look at their wiki and tutorials. Or if you know how to program, you can open the segmentation, replace the id's from one hemisphere with the one from the other and save it as a separate file. You will loose all the lateralisation information that way, but when you open that image it will display those regions with the same color. Not sure why you would want to do that, but it is easy enough to merge or replace labels.

Why I wanna do this?  Because I see the paper，Spatial Attention-based Implicit Neural Representation for Arbitrary Reduction of MRI Slice Spacing,  use FastSurfer to do that, but I don't know how to do. 
![image](https://github.com/Deep-MI/FastSurfer/assets/93995539/286f83e1-8570-439d-b377-22e25d88431f)

They use FastSurfer and get the segmentatio results. I feel confused about,  I have any idea about it
![image](https://github.com/Deep-MI/FastSurfer/assets/93995539/a680d720-a8b1-4ec3-b16c-9235123cc8a6)

**Comment by m-reuter** [comment]
Yes, they merged multiple labels into one (e.g. all cortical GM labels into a single label). From the image it looks like they also merged subcortical structures into that label. You should ask the authors what they did exactly, as there is not much detail in the paper (not even what FastSurfer version they used as far as I can see). 

Also note, that FastSurfer works on full head input images. They seem to be using skull stripped images, as their super-resolution approach does not predict head regions (they say due to the blurring of the de-facing step). Not sure how well that works. 

And while FastSurer has not been trained or validated on super-resolution images either, it is good to see that it still performs pretty well on those (with dice around 96%, Table IV). 

Anyway, there is not much we can do here. The paper does not specify what version was used and what labels were merged, so you need to find out from them, or merge labels yourself to get something that is close to what they have. We use the same label ids as FreeSurfer, their meaning can be found in the FreeSurfer lookup table, e.g here:

https://github.com/freesurfer/freesurfer/blob/dev/freeview/resource/FreeSurferColorLUT.txt

**Comment by NewboySoCool** [comment]
> 

Thanks again！ It's nice of you!
