### ISSUE TITLE
run_fastsurfer.sh calls FastSurferCNN from a relative path

### ISSUE THREAD

**Issue by bhvieira** [Deep-MI/FastSurfer#37]
[Line 43 in run_fastsurfer.sh](https://github.com/Deep-MI/FastSurfer/blob/master/run_fastsurfer.sh#L43) reads:

    fastsurfercnndir="./FastSurferCNN"

So `run_fastsurfer.sh` must be run from the same dir it's located.
This could be changed however to allow calling `run_fastsurfer.sh` from elsewhere.
A possible solution is using optional environment variables (a la $FREESUFER_HOME) and, if they exist, FastSurferCNN is called from there.

**Comment by LeHenschel** [comment]
Thank you very much for the suggestion. I finally got around to adding this feature in commit 569bbc7.

We now use a $FASTSURFER_HOME variable to indicate the base location of the FastSurfer code. This can be set via:

`export FASTSURFER_HOME=/path_to/your_copy_of/FastSurfer`

and allows running fastsurfer from any directory via:

`$FASTSURFER_HOME/run_fastsurfer.sh --t1 ....`

If the $FASTSURFER_HOME variable is not set upon running _run_fastsurfer_, it defaults to the current working directory.

Best,
Leonie

**Comment by bhvieira** [comment]
Glad to see this merged! This suggestion can be closed now :)
