### ISSUE TITLE
Smoothness and resolution differs from Freesurfer recon-all

### ISSUE THREAD

**Issue by karellopez** [Deep-MI/FastSurfer#372]
Dear developers,

I have tried your tool and the results are accurate and it would be nice to add it to our protocol. We currently use recon-all, then we manually edit the brainmask and then re-run recon-all. The final result is almost perfect, but time consuming since is manual.
Fast surfer could enhance the speed of this process for us, since the segmentation is accurate that normal recon-all. 
However, we noticed that the resolution and smoothness in the brainmask from Fast surfer does not match with the Freesurfer's recon-all brainmask. In recon-all output, the brainmask is 1.0 1.0 1.0 voxel size and no smoothness in the image. whereas, In the fastsurfer output it seems like it maintain the original resolution, more slices and also apply smoothing.

Is there some way to make fast surfer out to match to recon-all output?

Thanks in advance.
Best regards,
Karel Lopez

**Comment by LeHenschel** [comment]
Hey Karel,

by default, fastsurfer processes the image at the original resolution as you point out (which leads to a larger slice number and "smoother" results if you have high-resolution images as they are not downsampled). If you want results at 1.0 mm, you can specify it with the --vox_size flag:

--vox_size: Forces processing at a specific voxel size. If a number between 0.7 and 1 is specified (below is experimental) the T1w image is conformed to that isotropic voxel size and processed. If "min" is specified (default), the voxel size is read from the size of the minimal voxel size (smallest per-direction voxel size) in the T1w image: If the minimal voxel size is bigger than 0.98mm, the image is conformed to 1mm isometric. If the minimal voxel size is smaller or equal to 0.98mm, the T1w image will be conformed to isometric voxels of that voxel size. The voxel size (whether set manually or derived) determines whether the surfaces are processed with highres options (below 1mm) or not.

Kind regards,
Leonie
