### ISSUE TITLE
code for FastSurferVINN

### ISSUE THREAD

**Issue by romainVala** [Deep-MI/FastSurfer#376]
Hello
in  your neuroimage paper 2022 (FastSurferVINN: Building resolution-independence into deep learning
segmentation methods—A solution for HighRes brain MRI), you said, the code will be in this directory.

Sorry if I miss it, is it already the case ?

Many thanks
Romain

**Comment by m-reuter** [comment]
Yes, both stable and dev branches are using the VINN architecture.

**Comment by romainVala** [comment]
I first just looked at the documentation, but indeed, i found it in the  code
thanks for sharing this nice works (I do like resolution independence)
