### ISSUE TITLE
Error running FastSurfer: python 3.6 command not found

### ISSUE THREAD

**Issue by SaraRomanella** [Deep-MI/FastSurfer#38]
Hi, I was trying to run FastSurfer on a MRI and it gave me the following error:

~/freesurfer/FastSurfer-master/FastSurferCNN ~/freesurfer/FastSurfer-master
python3.6 eval.py --in_name /home/osboxes/freesurfer/Astro/001.mgz --out_name /home/osboxes/freesurfer/Astro/subject1/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path ../checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path ../checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path ../checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 8 --simple_run
./run_fastsurfer.sh: line 291: python3.6: command not found

Even if I modify the default python 3.6 with the current I am using (3.8.3) the error is the same:
./run_fastsurfer.sh: line 291: 3.8.3: command not found

Could you please give me an idea of how fixing this? Thank you so much!

**Comment by LeHenschel** [comment]
Hey,

could you post the exact command you ran which resulted in the second error (./run_fastsurfer.sh: line 291: 3.8.3: command not found)? It looks to me like you only passed the version number of python so sth. like:

```bash
./run_fastsurfer.sh --sid test --sd ../data --t1 ../data/test.mgz --seg_only --py 3.8.3
```

For the --py flag you basically have to paste the same command with which you would evoke python from the command line (e.g. python3 or python3.8 in your case):
```bash
user@computer:~/mydir/FastSurfer$ python3.8
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
>>> exit()
```
which then translates to the command:
```bash
./run_fastsurfer.sh --sid test --sd ../data --t1 ../data/bert_orig.mgz --seg_only --py python3.8
```

Best,
Leonie

**Comment by SaraRomanella** [comment]
Thank you for your answer. I did try adding the --py python3.8 but the error I now get is:
  File "eval.py", line 26, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

I am using a 
ython 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

May it be a problem with anaconda environment maybe? 
Thank you so much.
Sara

**Comment by SaraRomanella** [comment]
Oh I am sorry! I just figured it out, it was so easy! Thank you again for all!

**Comment by JaBlake** [comment]
Sorry to drag up an old ticket, but @SaraRomanella can you tell me what you did to fix this?

I was able to run FastSurferCNN on one subject. 
However, the second time I try to do it in the same env I've gotten the same error as the OP. 

Python version = 3.6.10
on Ubuntu 20.04
env = fastsurfer_cpu

What I am running is:

# Defining the data directory first
datadir=/home/jablake/Desktop/FastSurfer/subjects
fastsurferdir=/home/jablake/Desktop/FastSurfer/my_fastsurfer_analysis

# Then I run:
./run_fastsurfer.sh --t1 $datadir/subject1.nii \
                    --sid subject1 --sd $fastsurferdir \
                    --parallel --threads 4 \
                

The log is:

python3.6 eval.py --in_name /home/jablake/Desktop/FastSurfer/subjects/subject1.nii --out_name /home/jablake/Desktop/FastSurfer/my_fastsurfer_analysis/subject1/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path /home/jablake/Desktop/FastSurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path /home/jablake/Desktop/FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path /home/jablake/Desktop/FastSurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 8 --simple_run
./run_fastsurfer.sh: line 314: python3.6: command not found

The log after adding --py python3.6.10 (my python version) is:

/home/jablake/Desktop/FastSurfer/FastSurferCNN /home/jablake/Desktop/FastSurfer
python3.6.10 eval.py --in_name /home/jablake/Desktop/FastSurfer/subjects/subject1.nii --out_name /home/jablake/Desktop/FastSurfer/my_fastsurfer_analysis/subject1/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path /home/jablake/Desktop/FastSurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path /home/jablake/Desktop/FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path /home/jablake/Desktop/FastSurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 8 --simple_run
./run_fastsurfer.sh: line 314: python3.6.10: command not found


I am relatively new to linux so I may not have correctly followed @LeHenschel 's response, but I was able to run segmentation once before getting this error.

**Comment by LeHenschel** [comment]
Hey Jake,

I assume you are using your own local install and not the docker? If you type python3.6.10 (or python3.6/python3) in your command line (inside the environment), does it open up the python shell?
(akin to what I posted above, just with your python version:
```
user@computer:~/mydir/FastSurfer$ python3.8
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
>>> exit()
```
)

Best,
Leonie

**Comment by JaBlake** [comment]
Hi Leonie,

Thank you for your help!

This is what I get when I type "python3.6"

```shell
(fastsurfer_cpu) jablake@CINL-GPU1:~/Desktop/FastSurfer$ python3.6
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

**Comment by LeHenschel** [comment]
Hey,

this is an odd error. I was not able to reproduce it on my machine so far. As the basic python3.6 command invokes the correct shell, it seems like everything is set up correctly. If you do `echo $PATH`, is the directory you installed conda and the environments listed correctly (sth like this should be displayed at the beginning: /opt/conda/envs/fastsurfer_cpu/bin:/opt/conda/condabin:/opt/conda/bin)? And what version of conda are you using? 

For now, I would recommend to try a fresh install of the environment and see if the error persists... 

So I created the environment with this command:
`conda env create --name fastsurfer_cpu --file ./fastsurfer_env_cpu.yml`

And everything runs smoothly once I activate it (also the output for python3.6 looks exactly the same as yours):
`conda activate fastsurfer_cpu`

```bash
(fastsurfer_cpu) user@machine:/FastSurfer# python3.6
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(fastsurfer_cpu) user@machine:/FastSurfer# ./run_fastsurfer.sh --sid bert_test --sd /bert --t1 /bert/mri/orig.mgz --seg_only
Setting ENV variable FASTSURFER_HOME to current working directory /FastSurfer. 
Change via enviroment to location of your choice if this is undesired (export FASTSURFER_HOME=/dir/to/FastSurfer)
Wed Apr 28 09:31:17 UTC 2021

/FastSurfer/FastSurferCNN /FastSurfer
python3.6 eval.py --in_name /bert/mri/orig.mgz --out_name /bert/bert_test/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path /FastSurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path /FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path /FastSurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 8 --simple_run
Reading volume /bert/mri/orig.mgz
Cuda available: False, # Available GPUS: 0, Cuda user disabled (--no_cuda flag): False, --> Using device: cpu
Loading Axial
Successfully loaded Image from /bert/mri/orig.mgz
Loading Axial Net from /FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl
Axial model loaded.
...
```

Best,
Leonie

**Comment by JaBlake** [comment]
Hi Leonie,

Thank you again so much for your help. I really appreciate it.
I have deleted and remade the environment and I'm getting the same error as above. I even tried the _gpu yaml env and it's the same problem. I'd also like to say how weird it is that I did successfully run FastSurferCNN once and I'm getting this problem on the second attempt.

As I was writing a response to your question, I found something odd.

when I ```echo $PATH```, I get:

> /home/jablake/miniconda3/envs/fastsurfer_cpu/bin:/usr/local/freesurfer/bin:/usr/local/freesurfer/fsfast/bin:/usr/local/freesurfer/tktools:/usr/local/freesurfer/mni/bin:**~/conda/bin:/home/jablake/miniconda3/condabin:**/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:

When I double checked my conda version, I got this:

```shell
(fastsurfer_cpu) jablake@CINL-GPU1:~$ conda info

     active environment : fastsurfer_cpu
    active env location : /home/jablake/miniconda3/envs/fastsurfer_cpu
            shell level : 1
       user config file : /home/jablake/.condarc
 populated config files : 
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __linux=5.10.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/jablake/miniconda3  (writable)
      conda av data dir : /home/jablake/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jablake/miniconda3/pkgs
                          /home/jablake/.conda/pkgs
       envs directories : /home/jablake/miniconda3/envs
                          /home/jablake/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.5 Linux/5.10.0-051000-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1003:1005
             netrc file : None
           offline mode : False
```

When I saw that it listed my python version as 3.8.5, I tried running fastsurfer again with the argument: ```-py python3.8```

When I ran it this time, I got this error:
```shell
Traceback (most recent call last):
  File "eval.py", line 19, in <module>
    import nibabel as nib
ModuleNotFoundError: No module named 'nibabel'
```

but when I ```$ conda list nibabel``` I get:

```shell 
(fastsurfer_gpu) jablake@CINL-GPU1:~/Desktop/FastSurfer$ conda list nibabel
# packages in environment at /home/jablake/miniconda3/envs/fastsurfer_gpu:
#
# Name                    Version                   Build  Channel
nibabel                   2.5.1                      py_0    conda-forge

```
and when I do ```which python``` and ```python --version```
I get 
```shell
(fastsurfer_cpu) jablake@CINL-GPU1:~/Desktop/FastSurfer$ which python
/home/jablake/miniconda3/envs/fastsurfer_cpu/bin/python
```
```shell
(fastsurfer_cpu) jablake@CINL-GPU1:~/Desktop/FastSurfer$ python --version
Python 3.6.10 :: Anaconda, Inc.
```

So it seems like something got mixed up but I'm not sure where to start to fix it.

Thank you again for your all of your help.

Cheers,
JB

**Comment by JaBlake** [comment]
I'm just going to make this a seperate comment.

So I am not sure why, but when I simply run it as:
```shell
./run_fastsurfer.sh --sid test2 --sd /home/jablake/Desktop/FastSurfer/my_fastsurfer_analysis --t1 /home/jablake/Desktop/FastSurfer/subjects/subject1.nii --seg_only --py python3.6
``` 
it works

**Comment by LeHenschel** [comment]
Hey JB,

ok, I think the problem stems from the fact that as soon as you run the shell script (run_fastsurfer.sh) inside the environment, the conda base environment or local python install is initialized and not the fastsurfercnn_cpu env. In the base install you have python version 3.8 but none of the necessary packages are installed (as they are only present in the fastsurfercnn_cpu env). Hence, the eval.py script is executed because python3.8 is actually found within the dirs listed in PATH but you get the "No Module named nibabel" error as nibabel is only installed for the python3.6 inside fastsurfercnn_cpu. 

This has mostly likely to do with the way conda modifies the PATH variable. If you run `conda config --show-sources` , is auto_activate_base set to False? 

Also if you call `source $CONDA_BASE/etc/profile.d/conda.sh` and then activate the environment, does the error persist?
(In the commands above, $CONDA_BASE is equivalent with the path to your miniconda / anaconda installation. You can find that out by running: `conda info | grep -i 'base environment'`. Should be /home/jablake/miniconda3 for you.

Best,
Leonie
