### ISSUE TITLE
Dictionary for results?

### ISSUE THREAD

**Issue by karllandheer** [Deep-MI/FastSurfer#380]
Hello, I am able to run your great pipeline on my images to produce aparc.DKTatlas+aseg.deep.mgz. I have two quick questions.

Firstly, do you have a dictionary that translates the class label to which region it is? I can't seem to find this. Maybe this is standard for DKT atlas? But either way, not sure where to find that.

Secondly, the resulting image aparc.DKTatlas+aseg.deep.mgz is not the same size as the input image. The output image is 256x256x256, while my image is 182x218x182. I found that all I had to do was crop the output back to original for it to match up, but was wondering if this was normal behavior or if I'm running something slightly incorrectly? Any help with these would be greatly appreciated!

**Comment by m-reuter** [comment]
Three label IDs are the same as in the freesurfer lookup take ( I think a link was posted somewhere here, but we should add this to our documentation for sure). @LeHenschel  maybe can you look that up again? 

About the images, similar to Freesurfer we conform images to isotropic voxels,  rotate to perfect LIA orientation and adjust the field of view to 256 mm . So simply croping will not usually work. You will find the adjusted input that fits to the segmentation, eg in orig.mgz . While you could map the labels back to the input space this usually requires interpolation and is not recommended. 

If you are interested in volumes, you can look at the stats files, if you want to do an ROI analysis on a different modality, you could map that modality to the fastsurfer/Freesurfer conform space.

**Comment by LeHenschel** [comment]
Hey there,

as Martin said, the labels follow the FreeSurfer Look-Up table (specifically the DKTatlas). You can find a compiled list in the FastSurferCNN/config directory: https://github.com/Deep-MI/FastSurfer/blob/dev/FastSurferCNN/config/FastSurfer_ColorLUT.tsv

Second question was answered by Martin as well (input images are conformed. The resulting file is called orig.mgz in the $SUBJECT_ID/mri folder).

Hope this helps.
