### ISSUE TITLE
CUDA initialization: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by LeHenschel** [Deep-MI/FastSurfer#39]
Hi, I am sorry. I write here because of the error I am having may be due to requirements. I am running the whole segmentation and after the trials in coronal, axial, sagittal the process stops and it says it does not recognize the original MRI. The error above that is:

/home/osboxes/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0

Is there a specific NVIDIA I have to download and install? I am running fastsurfer on a linux on a Ubuntu. Thank you so much for any info you can give me!

_Originally posted by @SaraRomanella in https://github.com/Deep-MI/FastSurfer/issues/18#issuecomment-735642306_

**Comment by LeHenschel** [comment]
Hey Sara, 

in order to run pytorch on your system you would need a working NVIDIA driver on your machine. That is basically the only thing you need to preinstall. CUDA and cuDNN will be installed via the prebuild binaries in both pip or conda. Here, you only need to make sure that the NVIDIA driver on your system supports the selected CUDA version. 

You can check which NVIDIA-driver you have installed by running
```bash
nvidia-smi
```

which will give an output similar to this:
```bash
Mon Nov 30 10:48:15 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02                               |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 00000000:01:00.0  On |                  N/A |
|  0%   44C    P5    18W / 200W |    273MiB /  4039MiB |      1%      Default |
|                               |                      |                  N/A 
```

And here is an overview which drivers support which CUDA version:

CUDA Toolkit | Linux x86_64 Driver Version
-- | --
CUDA 11.1 (11.1.0) | >= 450.80.02
CUDA 11.0 (11.0.3) | >= 450.36.06
CUDA 10.2 (10.2.89) | >= 440.33
CUDA 10.1 (10.1.105) | >= 418.39
CUDA 10.0 (10.0.130) | >= 410.48
CUDA 9.2 (9.2.88) | >= 396.26
CUDA 9.1 (9.1.85) | >= 390.46
CUDA 9.0 (9.0.76) | >= 384.81
CUDA 8.0 (8.0.61 GA2) | >= 375.26
CUDA 8.0 (8.0.44) | >= 367.48
CUDA 7.5 (7.5.16) | >= 352.31
CUDA 7.0 (7.0.28) | >= 346.46

Now, for FastSurfer we used pytorch v1.2.0 gpu version for CUDA 10.0, which is the default for **pip** (see instructions for v1.2.0 (Wheel): https://pytorch.org/get-started/previous-versions/#linux-and-windows-9):

```
# CUDA 10.0
pip install torch==1.2.0 torchvision==0.4.0

# CUDA 9.2
pip install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

# CPU only
pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
If you are using **conda**, the process is similar. Here, you just specify the CUDA version via the cudatoolkit part (see instructions for v1.2.0 (conda): https://pytorch.org/get-started/previous-versions/#linux-and-windows-8):

```
# CUDA 9.2
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=9.2 -c pytorch

# CUDA 10.0
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch

# CPU Only
conda install pytorch==1.2.0 torchvision==0.4.0 cpuonly -c pytorch
```

In case you need to install the nvidia-driver, there are a number of step-by-step tutorials online (just google install nvidia-driver ubuntu version XYZ).

Hope this helps.

Best,
Leonie

**Comment by SaraRomanella** [comment]
Hi Leonie,
thank you for your reply. I tried all you wrote and realized there was a
hidden issue. Although I am able to install NVIDIA drivers I cannot use my
NVIDIA gpu of my computer because I am running Ubuntu on virtual machine (I
unfortunately have Windows).

Is there anything you think I could do to actually be able to run the whole
FastSurfer without NVIDIA on a virtual machine?
Thank you so much for your help and patience!
Best,
Sara

Sara Romanella
Fellow (Ph.D. in Neuroscience)
Phone nr. +393409831115
Personal Mail: romanellasara@gmail.com


Il giorno lun 30 nov 2020 alle ore 11:16 LeHenschel <
notifications@github.com> ha scritto:

**Comment by LeHenschel** [comment]
Hey Sara,

I am not an expert on the topic, but based on a quick web search I do not think it is possible to grant GPU access from a windows host to a linux guest (at least not for a standard windows installation). On the supported versions of Microsoft Windows Server (Microsoft Hyper-V Server 2016, Windows Server 2016, Windows Server 2019, Microsoft Hyper-V Server 2019), you can use Discrete Device Assignment (DDA) to enable a VM to access a GPU directly (via passthrough: https://docs.nvidia.com/grid/5.0/grid-vgpu-user-guide/index.html#using-gpu-pass-through-windows-server-hyper-v, https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploying-graphics-devices-using-dda) or use vGPU if you have a graphic card that supports it (a licensed product on supported Tesla GPUs: https://docs.nvidia.com/grid/5.0/grid-vgpu-user-guide/index.html#supported-gpus-grid-vgpu).

Maybe you can think about having a dual install of windows and ubuntu or create a persistent live drive with e.g. a USB stick (https://ubuntuforums.org/showthread.php?t=2230389)?

Best,
Leonie

**Comment by SaraRomanella** [comment]
Hi Leonie, 
Thank you for your response. I am going to look into it. Without NVIDIA and CUDA, you don't think I am going to be able to run the entire process of segmentation in FastSurfer? Thank you so much!

**Comment by LeHenschel** [comment]
Hey Sara,

you can run the CPU-based version of the network, but this is much slower than GPU-based version. If you have a good computing cluster it might still be reasonably fast, however, for any deep-learning network I would always recommend using a GPU (especially if you have one).

Alternatively, you could try an online computing service (like AWS or Google Colab).

Best,
Leonie

**Comment by bumbutudor** [comment]
``

**Comment by rockmind-eng** [comment]
> Hey Sara,
> 
> you can run the CPU-based version of the network, but this is much slower than GPU-based version. If you have a good computing cluster it might still be reasonably fast, however, for any deep-learning network I would always recommend using a GPU (especially if you have one).
> 
> Alternatively, you could try an online computing service (like AWS or Google Colab).
> 
> Also, what version of windows are you using? If you are on Windows 10, I think you might be able to use Docker to run the pipeline with GPU-support. See: https://stackoverflow.com/questions/49589229/is-gpu-pass-through-possible-with-docker-for-windows
> 
> Best, Leonie

ahm hey 
can u help me....i dont have nvidia...can i run 2ddepthmap without nvidia i mean can i use intel hd 4000 or cpu instead of nvidia?

**Comment by m-reuter** [comment]
What is 2d depth map? 
Anyway, we have no experience with running fastsurfer on Intel GPUs. You would need to run the CPU version.

**Comment by rockmind-eng** [comment]
> What is 2d depth map? Anyway, we have no experience with running fastsurfer on Intel GPUs. You would need to run the CPU version.

actually i was trying to make my ng file to find depth map to make it as 3d so i use google ai with stereo maker but cmd says its need to install nvidia and i have intel hd 4000...can u help me

**Comment by rockmind-eng** [comment]
> What is 2d depth map? Anyway, we have no experience with running fastsurfer on Intel GPUs. You would need to run the CPU version.

then how to run in cpu version can u tell me pls

**Comment by m-reuter** [comment]
Just to make sure this is clear: FastSurfer is a package for the segmentation and analysis of human brain MRI images. It contains a CNN and a surface processing pipeline. We support running this software here for its intended purpose, where the CNN can run either on a GPU or CPU. The Docker README Example 4 shows how to build a Docker image for the CPU version of the CNN. The docker file basically is a recipe what dependencies are needed if you want to replicate this directly on your computer. 

https://github.com/Deep-MI/FastSurfer/blob/master/Docker/README.md#example-4-build-cpu-fastsurfercnn-container-segmentation-only 

If you plan to use our FastSurferCNN network architecture for other goals, e.g. to retrain it to some other segmentation task, then this is possible ( we put the train script with our parameters here : https://github.com/Deep-MI/FastSurfer/blob/master/FastSurferCNN/train.py ), but we cannot support you in this. This would therefore require sufficient knowledge on your end. And probably also you would want to use a GPU as training on the CPU will take a long time.

**Comment by JahangheerShaik** [comment]
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

**Comment by m-reuter** [comment]
Not sure what you are trying to say. This is the automatic behaviour in our code already: 
https://github.com/Deep-MI/FastSurfer/blob/8d6e7ee4ee24dc24754ece97a10b76745315eddb/FastSurferCNN/utils/common.py#L85

and also in the Trainer:
https://github.com/Deep-MI/FastSurfer/blob/8d6e7ee4ee24dc24754ece97a10b76745315eddb/FastSurferCNN/train.py#L52

**Comment by KPCOFGS** [comment]
You can change some codes in model_management.py file, You can find this file by searching it in the folder provided by the system search. When you launcher it, There will be lines telling you which line in this file went wrong, and then you can just delete these lines

**Comment by HMG-Official** [comment]
> > What is 2d depth map? Anyway, we have no experience with running fastsurfer on Intel GPUs. You would need to run the CPU version.
> 
> then how to run in cpu version can u tell me pls

In the SPM py source code, we can modify the references to CUDA to CPU.

**Comment by LeHenschel** [comment]
In FastSurfer there is the --device flag which allows you to set the device you want to run the inference on. By default, we use the "auto" option which uses the GPU if one with enough Memory is available. This is also detailed in the README and the help text:

> --device: Select device for NN segmentation (auto, cpu, cuda, cuda:<device_num>, mps), where cuda means Nvidia GPU, you can select which one e.g. "cuda:1". Default: "auto", check GPU and then CPU. "mps" is for native MAC installs to use the Apple silicon (M-chip) GPU
