### ISSUE TITLE
HCP dataset: ground truth used for training

### ISSUE THREAD

**Issue by romainVala** [Deep-MI/FastSurfer#393]
Hello

I would like to know for the HCP dataset, if you recompute (for training and evaluation) the ground truth lables as stated in the article with the FreeSurfer v7.1.1 JHirRes stream, or if you used the aparc+aseg.nii.gz deliver in the HCP data release ?

the later is at 0.7 mm but it looks like an interpolation of the 1mm segmentation, in comparison the fastSurfer predictions (at native resolution 0.7)  are much smoother (and nicer)
I will compute the dice soon, but I expected to not be very good ...

Thanks
Romain

**Comment by LeHenschel** [comment]
Hey Romain,

we reprocessed the HCP dataset with the FreeSurfer hires stream as the delivered HCP labels are at 1.0 mm as far as I know (the HCP processing pipeline only constructs the surfaces at hires and the images are all at 1.0 mm)

**Comment by romainVala** [comment]
I just double check, but when I unzip a specific subject I get the files aparc+aseg.nii.gz at 0.7 resolution in the T1w subdir ... but I do not know how it has been computed 

would it be possible to share one subject (for instance100610)  aparac+aseg files that you preprocessed with hires stream, so that I can check if they are different ?

there is also a ribbon.nii.gz file, where the gray matter segmentation looks better. Would you advise to take this as ground truth for Gray Matter (instead of the aparc+aseg files) ?

**Comment by LeHenschel** [comment]
Not sure if they changed it. For me, the aparc+aseg.mgz is 1.0 mm:

```
mri_info preprocessed/fs-processed/100610/mri/aparc+aseg.mgz 
Volume information for preprocessed/fs-processed/100610/mri/aparc+aseg.mgz
          type: MGH
    dimensions: 256 x 256 x 256
   voxel sizes: 1.000000, 1.000000, 1.000000
```

For the gray matter, ribbon.nii.gz should be fairly similar to the aparc+aseg.mgz (except that the cortical parcels are merged and subcortical structures are not used to mask GM portions). So I would say it depends a bit on the task you want to achieve.

**Comment by LeHenschel** [comment]
So I just checked and it seems like they did indeed change the processing. The old version used to process everything at 1.0 mm except the surfaces (here is the line generating the aparc+aseg.mgz and other cortical segmentations. It does not include the hires flag, so output will be at 1.0 mm: https://github.com/Washington-University/HCPpipelines/blob/master/FreeSurfer/FreeSurferPipeline-v5.3.0-HCP.sh#L232)

In the new version they use the recon-all.v6.hires script (https://github.com/Washington-University/HCPpipelines/blob/master/FreeSurfer/FreeSurferPipeline.sh#L536). It also seems like there is some additional processing for the ribbon.nii.gz, so they may indeed be more different: https://github.com/Washington-University/HCPpipelines/blob/master/PostFreeSurfer/scripts/CreateRibbon.sh

**Comment by romainVala** [comment]
thanks for digging into it. but it is not easy to check: I have the v3 version of hcp, and I do find a aparc+aseg file at 0.7 resolution but the results is not very good, so I am not sure it has been processed with the last high res version

If I have no other choice I will try to run the hires pipeline, but if you can share a segmentation obtain by one subject (may be by mail romain.valabregue@upmc.fr) I could check if it worth it

**Comment by m-reuter** [comment]
Not sure we can share derived data (would need to look at the data share agreement with HCP), why not just run FreeSurfer with the highres flag and wait half a day to get the segmentations? @LeHenschel can you post here what flags and FreeSurfer version we used to process the HCP data?

But if the FastSurfer segmentation looks good (which is what you say above), then why not use that? As it learns from so many cases, it often looks better and less noisy than FreeSurfer.

**Comment by romainVala** [comment]
I understand, and I would appreciate to have the exact command option you run

I am using FastSurfer, but as a "baseline" model (since you did a very good job). I work with synthetic training (similar to Billot SynthSeg) and the topic related to my question was about models performance evaluation. 

I think there are a lot of biases using freesurfer aseg as the Ground Truth (GT) ...  but it is tricky to find other option. ... 
Anywhay here I want to be sure to evaluate against the "fairest" GT, so the closet to the one you used for training.

**Comment by LeHenschel** [comment]
The FreeSurfer version is 7.1.1. I added the -hires and -3T flag:

`recon-all -s ${sid} -i ${input}.mgz -all -hires -3T -sd ${sdir} `
