### ISSUE TITLE
Docker build with build.py

### ISSUE THREAD

**Issue by m-reuter** [Deep-MI/FastSurfer#394]
## Feature Description

When building a docker image users may hit some complications:
- The PYTHONPATH needs to be set. Here we need to update the documentation as on most systems ```PYTHONPATH=<fastsurferdir>``` is not sufficient and needs an ```export PYTHONPATH=...``` to work.
- It would be great if build.py can be called without having FastSurfer available or alternatively that it finds it automatically (as the project root will almost always be ../../ from the docker dir), and no PYTHONPATH env is needed.
- Even after setting the PYTHONPATH, it complains that packages are missing, for example 'nibabel' which is probably not actually needed for the build to work.  Why is the the function HelpFormatter in segstats.py , it should not need nibabel.

## Motivation

build.sh should work out of the box and not require users to install unnecessary packages or setup paths that are fixed anyway.

## Alternatives

Automatically find the Fastsurfer root and remove imports of unneeded packages (e.g. by organising packages differently). Or even better get rid of the Fastsurfer dependencies completely and use local or simpler routines to achieve the same task.

**Comment by dkuegler** [comment]
There is actually already some functionality in the `build.py` to make the script independent. The problem was, that the imported files in turn also import FastSurferCNN functionality and thus needed the path to be set...
So I have added that path in #395 .

**Comment by m-reuter** [comment]
Thanks!
