### ISSUE TITLE
RuntimeError: DefaultCPUAllocator: can't allocate memory - Error code 12 (Cannot allocate memory)

### ISSUE THREAD

**Issue by InRuiz** [Deep-MI/FastSurfer#396]
Hello, I have the following problem. 

I am analyzing two groups of MRI, each from a different center. I have the dicom in a SSD, I make a transformation to .nii.gz in my WSL and there I process the images. I have not had any problem with the MRI of the first group, but when I have adapted the script to those of the second group (the only thing that changes is the number of dicoms and the name). As the only difference, the folder with the .nii.gz that was generated with the first group (when it worked), was about 1.9Gb (about 10Mb per converted file), and now is 5Gb with de second grooup (about 30Mb per file). I don't know if this could be the problem. 

I find the following error:

RuntimeError: [enforce fail at alloc_cpu.cpp:66] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 27747328000 bytes. Error code 12 (Cannot allocate memory)

This is the script I am using: 
docker run --gpus all -v ~/my_subjects_inigo/57642843_T1:/data \
>   -v /usr/local/freesurfer/7.4.1/license.txt:/fs_license/license.txt \
>   -v ~/my_subjects_inigo/57642843_T1:/output \
>   --rm --user $(id -u):$(id -g) docker.io/deepmi/fastsurfer:latest \
>   --fs_license /fs_license/license.txt \
>   --t1 /data/FastSurfer/80491470.nii.gz \
>   --sid subject_inigo --sd /output \
>   --parallel

Environment
FreeSurfer Version: freesurfer-linux-ubuntu22_x86_64-7.4.1-20230614-7eb8460
OS: Ubuntu 22.04.3 LTS
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Python software package versions:
attrs==21.2.0
blinker==1.4
certifi==2020.6.20
chardet==4.0.0
command-not-found==0.3
cryptography==3.4.8
dbus-python==1.2.18
distro==1.7.0
distro-info==1.1+ubuntu0.1
docker==5.0.3
docker-compose==1.29.2
dockerpty==0.4.1
docopt==0.6.2
httplib2==0.20.2
idna==3.3
importlib-metadata==4.6.4
jeepney==0.7.1
jsonschema==3.2.0
keyring==23.5.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
more-itertools==8.10.0
netifaces==0.11.0
oauthlib==3.2.0
pycairo==1.20.1
PyGObject==3.42.1
PyJWT==2.3.0
pyparsing==2.4.7
pyrsistent==0.18.1
python-apt==2.4.0+ubuntu2
python-debian==0.1.43+ubuntu1.1
python-dotenv==0.19.2
PyYAML==5.4.1
requests==2.25.1
SecretStorage==3.3.1
six==1.16.0
systemd-python==234
texttable==1.6.4
ubuntu-advantage-tools==8001
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
wadllib==1.3.6
websocket-client==1.2.3
zipp==1.0.0

Thank you so much for your help

**Comment by m-reuter** [comment]
I don't think it is generally a problem of your file sizes as it will only read the one file that you pass with T1 flag. Maybe you can try --device CPU and not pass the GPUs to docker. 
Have you looked at the converted image at ```~/my_subjects_inigo/57642843_T1/FastSurfer/80491470.nii.gz```if everything is OK with it?

**Comment by dkuegler** [comment]
WSL docker does not support gpus at the moment, this is probably not your issue. FastSurfer (or something) is trying to allocate 27GB of RAM. This error is **not** primarily a WSL issue.
Please check the voxel size of your image (`mri_info <filename>` from FreeSurfer) or similar.

You probably want to set a manual voxel size -- use FastSurfer `--vox_size 0.7`  for isotropic voxel size of 0.7.

**Comment by InRuiz** [comment]
Thank you very much for your help, indeed that was the problem, adding the manual voxel size works. 

I have checked the voxel size using mri_info, and for the first image (80491470.nii.gz), the voxel sizes are 0.428571, 0.428571, 1.000000. Setting a manual voxel size with --vox_size 0.7 for an isotropic voxel size of 0.7, I don't get the error anymore.

Now, my concern is whether adjusting the voxel size manually will introduce any issues when comparing results with other group for which I haven't manually adjusted the voxel size. Are there specific considerations I should take?

Thanks again,

**Comment by m-reuter** [comment]
FastSurfer does not use a fixed internal resolution (different from FreeSurfer, which uses 1mm by default) but takes the smallest voxel size and resamples to isotropic voxels. FastSurfer has been tested between 0.7 and 1mm and can probably go a little outside this range. 

Best input images are isotropic scans. So 
- if your datasets get scanned with different sequences (maybe on different scanners etc) then results will never be 100% comparable no matter how you resample. 
- anisotropic voxels are not great as really the lowest resolution (1mm in your case) is the bottleneck.
- to reduce impact of different input resolutions, you should at least resample everything to the same resolution. It is up to you to select which one. Depends on what other resolutions you have in your data.

**Comment by InRuiz** [comment]
Thank you so much for the clarification.

Considering your advice, I will resample the images to an isotropic voxel size within the range of 0.7 to 1 mm, with the intention of reducing the impact of different input resolutions. I understand the importance of having consistent voxel sizes for better comparability.
