### ISSUE TITLE
FastSurfer stops at mris_sample_parc

### ISSUE THREAD

**Issue by nimzodisaster** [Deep-MI/FastSurfer#397]
Running docker latest on WSL. Fails to create pial surfaces.
 
 In the recon-surf log a signal 9 terminate signal keeps getting sent:
 
=========== Creating surfaces rh - map input asegdkt_segfile to surf ===============
 
mris_sample_parc -ct /opt/freesurfer/average/colortable_desikan_killiany.txt -file /fastsurfer/recon_surf/rh.DKTatlaslookup.txt -projmm 0.6 -f 5  -surf white.preaparc 110021-100_1 rh aparc.DKTatlas+aseg.orig.mgz aparc.DKTatlas.mapped.prefix.annot
Command terminated by signal 9
@#@FSTIME  2023:11:25:21:48:54 mris_sample_parc N 14 e 73.01 S 50.62 U 7.95 P 80% M 12330484 F 1666 R 1972570 W 0 c 298 w 11874 I 42520 O 0 L 2.04 1.98 1.58
@#@FSLOADPOST 2023:11:25:21:50:08 mris_sample_parc N 14 2.08 2.00 1.63

**Comment by m-reuter** [comment]
Most likely there is already a problem with the input data? You could double check that aparc.DKTatlas+aseg.orig.mgz looks good and also rh.white.preaparc . 
```freeview norm.mgz aparc.DKTatlas+aseg.orig.mgz  -f rh.white.preaparc``` 
(not sure how to run Freeview on WSL, maybe you need to run it in a virtual machine. maybe the FreeSurfer webpages have some details).

**Comment by nimzodisaster** [comment]
Thanks. Just checked it out. It looks generally okay to me. some pics attached.

![image](https://github.com/Deep-MI/FastSurfer/assets/19696085/3176fc39-4a16-491a-a8df-9383de57fe3e)
![image](https://github.com/Deep-MI/FastSurfer/assets/19696085/33932292-80c8-4bd8-a774-7065f893f125)

**Comment by m-reuter** [comment]
Yes the white looks ok, but this is not the ```aparc.DKTatlas+aseg.orig.mgz``` right? Because that should also have cortical sub-segmentations in it, and here it looks like there is only left and right GM.

**Comment by nimzodisaster** [comment]
Sorry, I had altered the color scheme. The segmentation looks okay
![image](https://github.com/Deep-MI/FastSurfer/assets/19696085/00d3b476-0a77-4728-b245-a76282ce11ca)

**Comment by nimzodisaster** [comment]
[build-stamp.txt](https://github.com/Deep-MI/FastSurfer/files/13514850/build-stamp.txt)
[deep-seg.log](https://github.com/Deep-MI/FastSurfer/files/13514851/deep-seg.log)
[defect2seg.log](https://github.com/Deep-MI/FastSurfer/files/13514852/defect2seg.log)
[lastcall.build-stamp.txt](https://github.com/Deep-MI/FastSurfer/files/13514854/lastcall.build-stamp.txt)
[patchdir.txt](https://github.com/Deep-MI/FastSurfer/files/13514855/patchdir.txt)
[ponscc.cut.log](https://github.com/Deep-MI/FastSurfer/files/13514856/ponscc.cut.log)
[recon-all.log](https://github.com/Deep-MI/FastSurfer/files/13514857/recon-all.log)
[recon-all-status.log](https://github.com/Deep-MI/FastSurfer/files/13514858/recon-all-status.log)
[recon-surf.log](https://github.com/Deep-MI/FastSurfer/files/13514860/recon-surf.log)
[unknown-args.txt](https://github.com/Deep-MI/FastSurfer/files/13514861/unknown-args.txt)

all the logs

**Comment by m-reuter** [comment]
Thanks, unclear why the command ```mris_sample_parc``` fails, everything looks good as far as I can see. This happens on a single case or on several cases? Is there a way for you to share this case with us, or is it maybe from a publicly available dataset?

**Comment by nimzodisaster** [comment]
Thanks. I have emailed you directly @dzne.de

**Comment by m-reuter** [comment]
I just ran the ```mris_sample_parc```command from FreeSurfer 7.3.2 directly on your data and it works.
Strange that it fails for you inside the docker (which also uses 7.3.2). I will try a complete run in docker on Linux next.

**Comment by m-reuter** [comment]
It also runs through with docker. I think it is a memory related issue. We found out that ```mris_sample_parc```requires much more memory than other FreeSurfer binaries (like >15GB in some cases). Maybe you can increase the memory that is provided to the docker image?

**Comment by m-reuter** [comment]
I just merged a python replacement for the sample_parc into the dev branch, that should not have these memory issues.
