### ISSUE TITLE
WSL questions about running the container in docker

### ISSUE THREAD

**Issue by caotihutang** [Deep-MI/FastSurfer#398]
when I run the pulled image in docker, the container will start and then exit immediately with code 0. what should i do ?

**Comment by m-reuter** [comment]
Please let us know what operating system you are on. Do you have a GPU. Which container are you running and what is the command you use (and output if there is any).

**Comment by caotihutang** [comment]
Thanks. I work on windows 10 with WSL2 and docker desktop. I have a GPU but I only use the cpu. 
I use the command below.
![image](https://github.com/Deep-MI/FastSurfer/assets/48438844/0b8cf9e8-2054-44c1-b08c-d383e093560a)
![image](https://github.com/Deep-MI/FastSurfer/assets/48438844/790a294f-0050-4fe2-84d3-5b25d8985db2)

**Comment by m-reuter** [comment]
Maybe the space in "FastSurfer Code" messes it up? Probably best if you rename the directory and never use spaces in file names or directories.

**Comment by caotihutang** [comment]
It works after removing the space. Thanks.

**Comment by dkuegler** [comment]
... or quote or escape the space :)
