### ISSUE TITLE
No further processed results using Docker version

### ISSUE THREAD

**Issue by yooha1003** [Deep-MI/FastSurfer#40]
Hi, I am trying to use fastsurfer:cpu using docker since I am using MacOS (High Sierra) and don't have any NVIDIA graphic card.
I tried to follow README file to run single orig.mgz file but I am stuck in the initial step.
After the following message, 

"Cuda available: False, # Available GPUS: 0, Cuda user disabled (--no_cuda flag): True, --> Using device: cpu"

The processing finished without any error message and the output directory did not have any created files except empty directories 'mri' and 'scripts' with deep-seg.log file.

Do you have any idea to fix this issue ?

Thanks for your kind comments in advance.

**Comment by LeHenschel** [comment]
Hey yooha,

with the given information it is a bit difficult to tell what is going on. My first guess would be that this is a memory issue. For running FastSurfer you would need approx. 10 GB RAM. By default, Docker Desktop on MAC is set to use 2 GB runtime memory. So you might try to change these settings (under Docker Desktop --> Preferences --> Resources --> Advanced, slide the bar under Memory to 10 GB; see: https://docs.docker.com/docker-for-mac/ for details).

**Comment by yooha1003** [comment]
> Hey yooha,
> 
> with the given information it is a bit difficult to tell what is going on. My first guess would be that this is a memory issue. For running FastSurfer you would need approx. 10 GB RAM. By default, Docker Desktop on MAC is set to use 2 GB runtime memory. So you might try to change these settings (under Docker Desktop --> Preferences --> Resources --> Advanced, slide the bar under Memory to 10 GB; see: https://docs.docker.com/docker-for-mac/ for details).
> 
> If this does not work, it would be helpful if you could provide the original command you ran (docker run ...) as well as some more information about your system and the deep-seg.log file content.
> 
> Best,
> Leonie

Dear Leonie,

I appreciate for your fix this issue.
It worked after the adjustment of memory capacity.
Have a good one!

Best,
Yooha

**Comment by LeHenschel** [comment]
Ok, great :). Glad it worked! 

I am closing this issue then.

Best,
Leonie
