### ISSUE TITLE
The meaning of "normMean" of the segstats.py output

### ISSUE THREAD

**Issue by gmeng92** [Deep-MI/FastSurfer#405]
Hey. I am running the segstats.py to get the vol_seg.stats after running the segmentation only module. According to the output, there is a column "normMean". I wonder what is the meaning of this column specifically. Thanks.
![image](https://github.com/Deep-MI/FastSurfer/assets/36212932/2bf29ff5-01e6-42ee-a22b-463c8e0c9b8a)

**Comment by m-reuter** [comment]
That is the mean image intensity inside that structure. It is not comparable with FreeSurfer, as freesurfer uses the norm.mgz file, but during segmentation, we only have a bias field corrected image, so these values are not very normalised yet and can differ across datasets etc.

**Comment by gmeng92** [comment]
Gotta you! Thanks for clarifying the difference of that to freesurfer output.

**Comment by dkuegler** [comment]
That is not really a difference to the freesurfer output. Freesurfer has the same output in `mri_segstats` in stats/aseg.stats or similar.

**Comment by gmeng92** [comment]
A follow-up question about the "--gt_nocc" in generate_hdf5.py. I am currently trying to modify the FastSurferCNN so I can train using my own data (seg was labeled using WM,GM, CSF etc.). Since I did not have the ground truth from Freesurfer-like output, is it reasonable to set the  gt_noncc as None?

**Comment by m-reuter** [comment]
This is not a follow up to your issue. Please post as new issue with the question label.
