### ISSUE TITLE
ModuleNotFoundError: No module named 'lapy.read_geometry'

### ISSUE THREAD

**Issue by weberam2** [Deep-MI/FastSurfer#409]
## Description

This was previously working for us. I recently had to delete the /var/lib/docker folder as I was getting weird docker errors

After reinstalling fastsurfer, it runs, but then suddenly stops

```
RunBatchJobs: Logfile: /output/sub-Pilot19/scripts/recon-surf.log
RunBatchJobs: CMDF: /output/sub-Pilot19/scripts/lh.processing.cmdf
RunBatchJobs: CMDF: /output/sub-Pilot19/scripts/rh.processing.cmdf
Waiting for PID 1104 of (1104 1108) to complete...
Waiting for PID 1108 of (1104 1108) to complete...
PIDs (1104 1108) completed and logs appended.
```

When I read the recon-surf.log file, I see:

```
@#@FSLOADPOST 2023:12:01:19:51:36 mri_mc N 3 1.08 1.22 1.13
python3.8 /fastsurfer/recon_surf/rewrite_mc_surface.py --input /output/sub-Pilot19/surf/rh.orig.nofix --output /output/sub-Pilot19/surf/rh.orig.nofix --filename_pretess /output/sub-Pilot19/mri/filled-pretess127.mgz
Traceback (most recent call last):
  File "/fastsurfer/recon_surf/rewrite_mc_surface.py", line 21, in <module>
    from lapy.read_geometry import read_geometry
ModuleNotFoundError: No module named 'lapy.read_geometry'
Command exited with non-zero status 1
@#@FSTIME  2023:12:01:19:51:36 python3.8 N 7 e 0.21 S 0.03 U 0.18 P 99% M 75240 F 0 R 14121 W 0 c 12 w 5 I 0 O 8 L 1.08 1.22 1.13
@#@FSLOADPOST 2023:12:01:19:51:36 python3.8 N 7 1.08 1.22 1.13
```

Which, the "no module named lapy.read_geometry' sticks out

I don't get it. If it is a docker image/container, shouldn't it all be there?

## Environment
 - OS: Ubuntu 22.04

### Execution

```
docker run --gpus all -v ${BIDSdir}/sub-${subid}/anat:/data \
    -v ${BIDSdir}/derivatives/FastSurfer:/output \
    -v ${fslicense}:/fs_license \
    --rm fastsurfer:gpu --fs_license /fs_license/license.txt \
    --t1 /data/sub-${subid}_T1w.nii.gz --sid sub-${subid} --sd /output --parallel
```

**Comment by weberam2** [comment]
This is what it says when I type `docker images`

```
docker images
REPOSITORY          TAG       IMAGE ID       CREATED             SIZE
fastsurfer          gpu       c5ae470768bd   59 minutes ago      8.21GB
<none>              <none>    72689c46fcd5   About an hour ago   20.5GB
ubuntu              20.04     bf40b7bc7a11   8 weeks ago         72.8MB
deepmi/fastsurfer   latest    93e50a00e5c6   2 months ago        8.29GB
nipreps/mriqc       latest    160876df4636   5 months ago        14GB
hello-world         latest    9c7a54a9a43c   7 months ago        13.3kB
nipreps/fmriprep    23.0.2    e79247cd39ce   7 months ago        10.7GB
```

**Comment by LeHenschel** [comment]
Based on the name I assume that you build the docker image from scratch. Can you say which version of FastSurfer you build from? And do you get the same error with the deepmi/fastsurfer image?

**Comment by weberam2** [comment]
How do I check?

**Comment by weberam2** [comment]
This is what I did to install

```
git clone git@github.com:Deep-MI/FastSurfer.git
```

```
docker pull deepmi/fastsurfer:latest
```

```
cd FastSurfer
docker build --rm=true -t fastsurfer:gpu -f ./Docker/Dockerfile .
```

But I'm not sure when I cloned it

what's strange is this was working on this machine recently

**Comment by weberam2** [comment]
Maybe I'll try reinstalling

**Comment by LeHenschel** [comment]
If you clone from github right now, you get the dev branch not stable (you would need to specify the branch ` git clone --branch stable https://github.com/Deep-MI/FastSurfer.git`).  

The images on docker hub that you get with `docker pull deepmi/fastsurfer:latest` are based on the tested stable release. If that one is working, it would mean that the dev branch has some issues, which might be true as the docker stuff has been severely restructured.

**Comment by m-reuter** [comment]
Hi, you first need to distinguish from a docker version that you pull from dockerhub, and a version you build locally. 

Try with the one from docker hub which is the one we provide and support. Seems you already ```docker pull deepmi/fastsurfer:latest```. That one should work, you can just run it (put deep/fastsurfer instead of fastsurfer:gpu in your docker run command).

Note, that when you clone from git, it will clone our dev version. That version is under constant development and can fail at any time. You should clone the stable branch:

```git clone --branch stable https://github.com/Deep-MI/FastSurfer.git```

which should be the same or at least very close to the last released version.

**Comment by LeHenschel** [comment]
So it would be helpful if you test the command with the dockerhub image (which is based on stable):

```
docker run --gpus all -v ${BIDSdir}/sub-${subid}/anat:/data \
    -v ${BIDSdir}/derivatives/FastSurfer:/output \
    -v ${fslicense}:/fs_license \
    --rm deepmi/fastsurfer:latest --fs_license /fs_license/license.txt \
    --t1 /data/sub-${subid}_T1w.nii.gz --sid sub-${subid} --sd /output --parallel
```

**Comment by m-reuter** [comment]
yes, in lapy it is now ```_read_geometry```. But the import in FastSurfer dev is correct and has been adjusted https://github.com/Deep-MI/FastSurfer/blob/da998a15dbc8812875f1080549b8fd5c7b1f75d6/recon_surf/rewrite_mc_surface.py#L21 . I think here you mix old fastsurfer code with new requirements, which makes it fail in your case.

**Comment by weberam2** [comment]
Thanks for your help! I will try these ideas and get back to you all
I didn't realize I was pulling a development branch

**Comment by m-reuter** [comment]
> I didn't realize I was pulling a development branch

but not the current one, as your code still includes lapy.read_geometry wich is outdated. 

In short: you don't need to build your own docker, unless you want to test development branch. Else just pull the release from dockerhub (no need to build from stable unless you are modifying it).

**Comment by weberam2** [comment]
Sorry if this is basic, but when I try the above, I get this:

```
Run FastSurfer
You are trying to run './run_fastsurfer.sh' as root. We advice to avoid running FastSurfer as root,
because it will lead to files and folders created as root.
If you are running FastSurfer in a docker container, you can specify the user with
'-u $(id -u):$(id -g)' (see https://docs.docker.com/engine/reference/run/#user).
If you want to force running as root, you may pass --allow_root to run_fastsurfer.sh.
```

Then when I include the `-u $(id -u):$(id -g)`, I get:

```
Run FastSurfer
./run_fastsurfer.sh: line 641: /output/sub-Pilot20/scripts/deep-seg.log: Permission denied
tee: /output/sub-Pilot20/scripts/deep-seg.log: Permission denied
Mon Dec 11 20:15:19 UTC 2023
tee: /output/sub-Pilot20/scripts/deep-seg.log: Permission denied

python3.8 /fastsurfer/FastSurferCNN/run_prediction.py --t1 /data/sub-Pilot20_T1w.nii.gz --asegdkt_segfile /output/sub-Pilot20/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /output/sub-Pilot20/mri/orig.mgz --brainmask_name /output/sub-Pilot20/mri/mask.mgz --aseg_name /output/sub-Pilot20/mri/aseg.auto_noCCseg.mgz --sid sub-Pilot20 --seg_log /output/sub-Pilot20/scripts/deep-seg.log --vox_size min --batch_size 1 --viewagg_device auto --device auto
tee: /output/sub-Pilot20/scripts/deep-seg.log: Permission denied
Traceback (most recent call last):
  File "/fastsurfer/FastSurferCNN/run_prediction.py", line 388, in <module>
    setup_logging(args.log_name)
  File "/fastsurfer/FastSurferCNN/utils/logging.py", line 44, in setup_logging
    handlers.append(FileHandler(filename=log_file_path, mode="a"))
  File "/venv/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/venv/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/output/sub-Pilot20/scripts/deep-seg.log'
ERROR: FastSurfer asegdkt segmentation failed.
```

any advice? Otherwise maybe I will purge my docker images and recreate using the newer stable one from github

**Comment by weberam2** [comment]
I will try running as root as well

**Comment by m-reuter** [comment]
Hi, when you start docker without the -u flags the user inside docker will be root. This means that the files created by docker on your computer (in the mounted directories) will be owned by root. If you are not root on your computer, then you will not be able to delete them etc. This is not recommended. 

When you pass the -u flag, the user inside docker will get the same ID and group as your current user on the host system. This makes sense, but in your case, your user may not have access to the directories that you are mounting into docker. Probably it cannot write to the files, because they already exist and are owned by root?

Try to re-run from scratch in a new directory where you have write permissions, using the released docker images from docker hub. Then you only need to make sure that the input files are readable by your user.

**Comment by dkuegler** [comment]
A common issue here is that you created the folder for different user and not your main group. 

Check this: 
Get the owner of the subject directory (`LS -al subject_dir`) and your own group (`getent group $(id -g)`). 

I expect they are different.

you can fix that by also adding `--group-add [the group]` to docker.

The issue would be that only your main group is getting passed into the docker container and that is not enough. You also needed secondary groups
