### ISSUE TITLE
Error with contourpy when running     pip install -r requirements.txt

### ISSUE THREAD

**Issue by karllandheer** [Deep-MI/FastSurfer#416]
Hello, I got this even after running pip install update. I don't think contourpy==1.2.0 is hosted on pypi. Is it possible to downgrade requirements.txt?

ERROR: Could not find a version that satisfies the requirement contourpy==1.2.0 (from -r /fastsurfer_tutorial/fastsurfer//requirements.txt (line 21)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.1.0, 1.1.1rc1, 1.1.1)

I ran this on Ubuntu 20.04

**Comment by m-reuter** [comment]
We currently support Ubuntu 22.04. If this is not available on 20.04 you can try an older version, but who knows what will happen. Better to run our docker or singularity images which are tested.

**Comment by dkuegler** [comment]
> I don't think contourpy==1.2.0 is hosted on pypi. 

I am not really sure that is true. Maybe it is not there for your python version? Please confirm you are using python 3.9+ (`python --version`). Note, that we only support python 3.10 with the current stable fastsurfer version (2.2).  Before, the default and supported version was python 3.8.
https://pypi.org/project/contourpy/
