### ISSUE TITLE
Is the package yml located in the top level?

### ISSUE THREAD

**Issue by pmahon3** [Deep-MI/FastSurfer#418]
https://github.com/Deep-MI/FastSurfer/blame/a000faa1a5b9fd2355b6d9e8502c64929dd0ae07/INSTALL.md#L96

As per the native install instructions the package yml should be in the top level of the repo but it doesn't seem to be there. The only yaml's i see are under /env https://github.com/Deep-MI/FastSurfer/tree/2118c5c2104874c7bdef1243e4c1de31fd2ffbd7/env

**Comment by dkuegler** [comment]
Hi,

That is indeed outdated with the most recent release. We no longer have multiple environments per hardware setup either. 

The short version is: use `env/FastSurfer.yaml` now (for conda) or the requirements.txt in root (for pip).

I''ll update the docs.

**Comment by dkuegler** [comment]
Maybe I should double-check if the recon-surf ymls file is actually the same as the `MODE=base` file. Then we could consider dropping the reconsurf yml file...
