### ISSUE TITLE
Skip the brain extraction step in FastSurfer

### ISSUE THREAD

**Issue by yooha1003** [Deep-MI/FastSurfer#42]
Hi,

I am trying to run docker versioned Fastsurfer without brain extraction step but I don't know how to to that.
In freesurfer, I usually flagged -<no>skullstrip when I run recon-all process.
Is it possible to use that option in FastSurfer ?

Best,
Yooha

**Comment by LeHenschel** [comment]
Hey Yooha,

the skull stripped image called brainmask.mgz which is produced by FreeSurfer if you run `recon-all -skullstrip` should also be automatically generated with FastSurfer (image of the same name in the subjid/mri/ directory). Specifically, this is done in the recon-surf pipeline.

Is this file not present in your output or are you only running the segmentation with FastSurferCNN and want a skull stripped image based on it?

Best,
Leonie

**Comment by m-reuter** [comment]
Hi @yooha1003 
FastSurfer requires full head images for the segmentation step as we never trained with brain only. It should, however, work with de-faced images. By the way also FreeSurfer needs full head images to get a better Talairach registration for the estimated total intracranial volume. It may run without, but unclear how reliable those estimates will be when using only brain. 
Best, Martin

**Comment by yooha1003** [comment]
> Hey Yooha,
> 
> the skull stripped image called brainmask.mgz which is produced by FreeSurfer if you run `recon-all -skullstrip` should also be automatically generated with FastSurfer (image of the same name in the subjid/mri/ directory). Specifically, this is done in the recon-surf pipeline.
> 
> Is this file not present in your output or are you only running the segmentation with FastSurferCNN and want a skull stripped image based on it?
> 
> Best,
> Leonie

I am sorry for making you confused. I just wanted to run fastsurfer from the brain extracted images.
There was no problem with extraction of the skull from the image in fastsurfer.

**Comment by yooha1003** [comment]
> Hi @yooha1003
> FastSurfer requires full head images for the segmentation step as we never trained with brain only. It should, however, work with de-faced images. By the way also FreeSurfer needs full head images to get a better Talairach registration for the estimated total intracranial volume. It may run without, but unclear how reliable those estimates will be when using only brain.
> Best, Martin

Thanks Martin for the answer of my question.
I got your point.
I just wanted to use my own extracted brain images in fastsurfer.

Best,
Yooha.
