### ISSUE TITLE
Integrate cereb_segfile.mgz to aparc.a2009s or aparc.DKTatlas like aparc.a2009s+aseg.mgz?

### ISSUE THREAD

**Issue by iPsych** [Deep-MI/FastSurfer#420]
Is there any way to generate the integrated file like "aparc.a2009s+aseg.mgz" in freesurfer default using  cereb_segfile.mgz file?
The goal is replacing the whole left and right cerebellum with  cereb_segfile.mgz. 
using mris_calc or fscalc fails due to image size mismatch.

**Comment by dkuegler** [comment]
There is currently no easy way, although we plan to create a consolidated file in the future. The reason for this is that the cereb segmentation is currently always on 1mm while the aparc+aseg is at the possibly higher conformed resolution. 
So for higher resolution, such a merge would require label resampling, which loses detail. So it cannot really be used for QC and for all other applications the benefit for a merged segmentation file is not obvious.
Additionally, the boundary between cerebellar white matter and brain stem is not 100% clear. I.e. which definition do we follow and how do we fill the voxels there.
If there is a demand and use case for this, we might prioritize adding this, but we do not see this right now.
