### ISSUE TITLE
Fastsurfer segmentation for multiple subjects

### ISSUE THREAD

**Issue by Kaonashi22** [Deep-MI/FastSurfer#422]
Hi,

I am trying to run the fastsurfer segmentation for multiple subjects using singularity. 
As explained in the tuto, I typed the following command:
singularity exec --nv \
                 --no-home \
                 -B /test1:/data \
                 -B /test1:/output \
                 -B /test1:/fs_license \
                 ./fastsurfer-gpu.sif \
                 /fastsurfer/run_fastsurfer.sh \
                 --fs_license /fs_license/license.txt \
                 --sd /output \
                 --subjects_list /data/subjects_list.txt \
                 --cereb_segfile
                 --parallel --3T 

I provided the absolute path to the subjects directory in the subjects_list.txt file: 
suj1=/test1/suj1
suj2=/test1/suj2

When I run the command, the flag "--subjects_list" is not recognized. I get the same error when I give the path to the T1-w images (suj1=/test1/suj1/T1.nii)

Could you help me with this issue?

Thanks in advance!

**Comment by dkuegler** [comment]
Thank you for reporting this issue.

This is a typo in the doc, this feature is new.

`/fastsurfer/run_fastsurfer.sh => /fastsurfer/brun_fastsurfer.sh `

I already updated the docs. #423

**Comment by Kaonashi22** [comment]
Thanks for your reply
________________________________
De : David Kügler ***@***.***>
Envoyé : mercredi 3 janvier 2024 04:24
À : Deep-MI/FastSurfer ***@***.***>
Cc : Lydia Chougar, Dr ***@***.***>; Author ***@***.***>
Objet : Re: [Deep-MI/FastSurfer] Fastsurfer segmentation for multiple subjects (Issue #422)


Thank you for reporting this issue.

This is a typo in the doc, this feature is new.

/fastsurfer/run_fastsurfer.sh => /fastsurfer/brun_fastsurfer.sh

I already updated the docs. #423<https://github.com/Deep-MI/FastSurfer/pull/423>
