### ISSUE TITLE
Version: 2.1.1: Does Fastsurfer produce /mri/transforms/talairach.m3z file?

### ISSUE THREAD

**Issue by fw-ashmistry** [Deep-MI/FastSurfer#426]
Quick question, does Fastsurfer output mri/transforms/talairach.m3z? I see that it generates these files, but not talairach.m3z. Is there a way to produce that file downstream (after a Fastsurfer run)? I know that in recon-all this corresponds to [CA Register (-<no>careg)](https://surfer.nmr.mgh.harvard.edu/fswiki/recon-all#CARegister.28-.3Cno.3Ecareg.29)

- talairach.auto.xfm
-  talairach.auto.xfm.lta
-  talairach.lta 
-  talairach.xfm 
-  talairach.xfm.lta 
-  talairach_avi.log 
-  talairach_with_skull.lta

**Comment by m-reuter** [comment]
Hi, FastSurfer does not need to create a non-linear atlas registration as we segment everything directly with FastSurferVINN (the neural network). And as you say, if you have FreeSurfer installed, you can just run ```recon-all .... -careg``` to create that file or directly: 

```
mri_ca_register -align-after -nobigventricles -mask brainmask.mgz -T transforms/talairach.lta norm.mgz $FREESURFER_HOME/average/RB_all_2016-05-10.vc700.gca transforms/talairach.m3z
```
