### ISSUE TITLE
WSL: Invalid reference format

### ISSUE THREAD

**Issue by KontorErnestKissi** [Deep-MI/FastSurfer#428]
Hi, I am Ernes. I am new to Fastsurfer. I have followed the instructions using the CPU version.This is the code that I used 

docker run -v C:/Users/Ernes/my_mri_data:/data \
           -v C:/Users/Ernes/my_fastsurfer_analysis:/output \
           -v C:/Users/Ernes/my_fs_license_dir:/fs_license \
           --rm --user $(id -u):$(id -g) deepmi/fastsurfer:cpu-v2.0.0 \
           --fs_license /fs_license/license.txt \
           --t1 /data/subjectX/H1.nii.gz \
           --device cpu \
           --sid subject1 --sd /output \
           --parallel
          But I got Invalid reference format. How do I solve this?

**Comment by m-reuter** [comment]
Hi Ernes, you are probably using windows, which requires WSL2. 
Did you follow our installation instruction here: https://github.com/Deep-MI/FastSurfer/blob/dev/INSTALL.md#windows ?

Also we would need to know the exact Windows version and also output when you run this command.

**Comment by KontorErnestKissi** [comment]
Yeah, I already had WSL2 installed because I use Ubuntu for some analysis. So I downloaded Docker and followed the instructions on the link you provided. So after following the instructions, I copied the code and edited it based on my username and the appropriate paths as showed above.

**Comment by m-reuter** [comment]
You might want to replace :cpu-v2.0.0 with :cpu-latest to run the most recent release. 
Also you probably double checked that the license dir and the data dir really contain the license.txt and subjectX/H1.nii.gz ?

And can you post the exact output you are getting when running the command?

**Comment by KontorErnestKissi** [comment]
Sure, I will try that. But now I am running some commands in my terminal. I will get back to you tomorrow. Thank you very much.

**Comment by m-reuter** [comment]
I think I found the issue in your command. The reason that docker throws an "Invalid reference format" error is when it cannot find the image. The image is the first parameter after the flags, and in this case should be the deepmi/fastsurfer...

If however, any flag before contains a space, then it will use some other string as the image and cannot find it. This can happen in paths with spaces, which should be inside quotation marks "". In your case it looks like there could be a space in the user flag ```--user $(id -u):$(id -g)``` before the colon? Other things to try is to put quotation marks around that ```--user "$(id -u):$(id -g)"``` .

**Comment by KontorErnestKissi** [comment]
I made the changes to --user 1001:1001 and it kinda worked but now I have error "FastSurfer asegdkt segmentation failed".

C:\Windows\System32>docker run -v C:/Users/Ernes/my_mri_data:/data -v C:/Users/Ernes/my_fastsurfer_analysis:/output -v C:/Users/Ernes/my_fs_license_dir:/fs_license --rm --user 1001:1001 deepmi/fastsurfer:cpu-latest --fs_license /fs_license/license.txt --t1 /data/subjectX/H1.nii.gz --device cpu --sid subjectX --sd /output --parallel
Version: 2.2.0+9f37d02
Sun Jan 14 08:23:58 UTC 2024

python-s /fastsurfer/FastSurferCNN/run_prediction.py --t1 /data/subjectX/H1.nii.gz --asegdkt_segfile /output/subjectX/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /output/subjectX/mri/orig.mgz --brainmask_name /output/subjectX/mri/mask.mgz --aseg_name /output/subjectX/mri/aseg.auto_noCCseg.mgz --sid subjectX --seg_log /output/subjectX/scripts/deep-seg.log --vox_size min --batch_size 1 --viewagg_device auto --device cpu
[INFO: run_prediction.py:  546]: Checking or downloading default checkpoints ...
[INFO: common.py:  111]: Using device: cpu
[INFO: run_prediction.py:  234]: Running view aggregation on cpu
[INFO: inference.py:  200]: Loading checkpoint /fastsurfer/checkpoints/aparc_vinn_coronal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /fastsurfer/checkpoints/aparc_vinn_sagittal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /fastsurfer/checkpoints/aparc_vinn_axial_v2.0.0.pkl
[INFO: common.py:  820]: Single subject with absolute file path for input.
[INFO: common.py:  833]: No subjects directory specified, but the parent directory of the output file /output/subjectX/mri/aparc.DKTatlas+aseg.deep.mgz is 'mri', so we are assuming this is the 'mri' folder in the subject directory.
[INFO: common.py:  875]: Analyzing single subject /data/subjectX/H1.nii.gz
[INFO: common.py:  970]: Output will be stored in Subjects Directory: /output
[INFO: run_prediction.py:  310]: Successfully loaded image from /data/subjectX/H1.nii.gz.
[INFO: run_prediction.py:  418]: Output image directory 001.mgz does not exist. Creating it now...
Traceback (most recent call last):
  File "/fastsurfer/FastSurferCNN/run_prediction.py", line 561, in <module>
    for subject, (orig_img, data_array) in iter_subjects:
  File "/fastsurfer/FastSurferCNN/run_prediction.py", line 462, in pipeline_conform_and_save_orig
    yield subject, self.conform_and_save_orig(subject)
  File "/fastsurfer/FastSurferCNN/run_prediction.py", line 316, in conform_and_save_orig
    if not conf.is_conform(
  File "/fastsurfer/FastSurferCNN/data_loader/conform.py", line 625, in is_conform
    iaffine = img.affine[0:3, 0:3] - LIA_affine * (
ValueError: operands could not be broadcast together with shapes (3,3) (4,)
ERROR: FastSurfer asegdkt segmentation failed.

**Comment by m-reuter** [comment]
This is a new issue and I moved that discussion to #431  so this can be closed
