### ISSUE TITLE
SubmillimeterRecon

### ISSUE THREAD

**Issue by marcoduering** [Deep-MI/FastSurfer#43]
Hi all!

First of all congratulations, FastSurfer is really impressive and a great tool!

As you are of course aware, FreeSurfer has the option to do [SubmillimeterRecon ](https://surfer.nmr.mgh.harvard.edu/fswiki/SubmillimeterRecon). 

Any plans to support this in FastSurfer? Would be nice to work in native resolution with high-res scans.

All the best,
Marco

**Comment by m-reuter** [comment]
Hi Marco, 
Thanks. 
Actually we are working on that already. But it will take some more time. 

Best Martin
