### ISSUE TITLE
Curiosity about excluding optic chiasm segmentation

### ISSUE THREAD

**Issue by 36000** [Deep-MI/FastSurfer#440]
Out of curiosity: why is the optic chiasm label being excluded here? Is the classification not reliable? If I removed this line, what would happen?

https://github.com/Deep-MI/FastSurfer/blob/ec456aaafb0def21f2245848e46dbae1fdd0c69f/FastSurferCNN/data_loader/data_utils.py#L636

**Comment by m-reuter** [comment]
Hi, not sure anymore. That decision was done in 2016/2017 when we started with this. Probably the structure was not segmented reliably in FreeSurfer or had other issues. 

Our new hypothalamus sub-segmentation tool provides optic chiasm and nerve labels and will be added as a module to FastSurfer soon. 
https://direct.mit.edu/imag/article/doi/10.1162/imag_a_00034/118047/FastSurfer-HypVINN-Automated-sub-segmentation-of

Removing that line in the code above will not help, unless you plan to train your own network.

**Comment by 36000** [comment]
Exciting! It looks like you tested this on the UKBiobank as well. Thats good, because I want to run it on UKBiobank and other similar quality datasets. Also, all the other optic segmentations (nerve, tract) will be useful, even if they are not prefect/only in some subjects due to data quality in those regions. I eagerly await this addition!

Of less crucial important to my work, do you have any plans in the future to train a network to do the thalamic subsegmentation and add it to fastsurfer: https://freesurfer.net/fswiki/ThalamicNuclei ?

**Comment by m-reuter** [comment]
Yes, we are considering to train an updated version at some point with lots of additional labels, also for better eTIV estimation, but it is unclear if Thalamic Nuclei will be included. This depends on the questions whether FreeSurfer's labels are good enough, or whether we need manual ground truth for training.
