### ISSUE TITLE
Difference between aseg+DKT.stats and aseg.stats

### ISSUE THREAD

**Issue by karllandheer** [Deep-MI/FastSurfer#441]
Hello, I see that aseg.stats is generated after running the surface module, but practically what is the difference? Is it expected that aseg.stats should be more accurate than aseg+DKT.stats? Or do they contain complementary information? Help with how to interpret the difference between these two files would be greatly appreciated.

**Comment by m-reuter** [comment]
Hi, similar to FreeSurfer we correct the segmentations with the surfaces. This ensures: 
- that outside of the pial surface we have no brain labels
- inside of WM surface we have no cortical structures
- in between GM and WM we have the cortical structures in (relatively) clean columns
- underneath labels that are outside the cortex label on the surface (e.g. hippocampus area etc), we have no cortical labels

So generally, the surface corrected final segmentation would be recommended. But the deep learning generated segmentation already looks pretty good most of the time (and depending on your images, it can happen that it looks even better). So feel free to choose what looks best for you. In a paper I would report it as either the segmentation from the deep learning module, or after full FastSurfer.

**Comment by dkuegler** [comment]
Also, additional values such as the etiv are only in the aseg.stats. on the other hand, aseg+DKT.stats is available very quickly (no surfaces, so 2-5 minutes depending on hardware and settings).

**Comment by karllandheer** [comment]
I understand, thank you very much for your help.
