### ISSUE TITLE
Need help building the Docker image from Docker file

### ISSUE THREAD

**Issue by AkhilaPhenomx** [Deep-MI/FastSurfer#442]
## Question/Support Request

Hi Team,
I am trying to build the docker image from Docker file. But it is failing with below error

**`The command '/bin/bash --login -c cd /fastsurfer ; python3 FastSurferCNN/download_checkpoints.py --all &&     python3 -m compileall * &&     python3 FastSurferCNN/version.py --sections +git+checkpoints+pip --build_cache BUILD.info -o fullBUILD.info &&     mv fullBUILD.info BUILD.info' returned a non-zero code: 2`**

## Screenshots

![image](https://github.com/Deep-MI/FastSurfer/assets/60080310/93585fa1-209c-4ce0-a77d-aa24da44a0ee)

Run Command: 

`docker build  . -t fs:v1 -f Docker/Dockerfile`

**Comment by m-reuter** [comment]
Have you tried using the provided build.py python script as described in the README: https://github.com/Deep-MI/FastSurfer/blob/dev/Docker/README.md

**Comment by AkhilaPhenomx** [comment]
@m-reuter Yes, but failing with same error. "BUILD.INFO" file is required. Where can I get this file.

**Comment by m-reuter** [comment]
On what system are you building? what linux or Mac ?
@dkuegler would be the right one to answer, as he created the new build stuff.

**Comment by AkhilaPhenomx** [comment]
@m-reuter I am using Linux

**Comment by dkuegler** [comment]
If the `BUILD.info` file is is not found, that means you are not using the build script `Docker/build.py` as described in https://github.com/Deep-MI/FastSurfer/blob/dev/Docker/README.md#example-1-build-gpu-fastsurfer-image .

That script creates this file as part of the script.
The `BUILD.info` file is used to add version information, such as the git branch, git hash, and git status (difference overview to the commit) of the current commit to the docker image.

**Comment by AkhilaPhenomx** [comment]
@dkuegler Is there any way to build it using Dockerfile and docker build command?

**Comment by dkuegler** [comment]
Just run the build script `Docker/build.py` with  the `--print` option. This will print out which docker build command you are supposed to use, but also create the correct the BUILD.info file as you would need.

**Comment by AkhilaPhenomx** [comment]
@dkuegler I tried running build.py

Now I am getting below error
`(base) phenomx@phenomx-workstation:/mnt$  cd /mnt ; /usr/bin/env /home/phenomx/anaconda3/envs/py310/bin/python /home/phenomx/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 34753 -- /mnt/nas03/Akhila/new_Fastsurfer/temp/FastSurfer/Docker/build.py --device cuda 
error: unknown option `show-current'
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
   or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
   or: git branch [<options>] [-r] (-d | -D) <branch-name>...
   or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
   or: git branch [<options>] (-c | -C) [<old-branch>] <new-branch>
   or: git branch [<options>] [-r | -a] [--points-at]
   or: git branch [<options>] [-r | -a] [--format]`

**Line number 200 in FastSurfer/FastSurferCNN/version.py file**

```
if has_git and not prefer_cache:
            futures["git_hash"] = Popen(["git", "rev-parse", "--short", "HEAD"], **kw_root).as_future(pool)
            if sections != "":
                futures["git_branch"] = Popen(["git", "branch", "--show-current"], **kw_root).as_future(pool)
            if "+git" in sections:

                futures["git_status"] = pool.submit(filter_git_status, Popen(["git", "status", "-s", "-b"], **kw_root))
```

**Comment by AkhilaPhenomx** [comment]
@dkuegler @m-reuter Can you help me resolve this issue?

**Comment by dkuegler** [comment]
This is an error in git, please make sure you have a recent version of git.
I myself am using git 2.34.1, but I have seen this issue on a different PC and it was the git version.

It seems `--show-current` was introduced with version 2.22 in 2019, this would be required.

**Comment by AkhilaPhenomx** [comment]
@m-reuter @dkuegler After upgrading the Git version. I can build it successfully. 
Thank you for the help.
