### ISSUE TITLE
Help apptainer

### ISSUE THREAD

**Issue by CPernet** [Deep-MI/FastSurfer#446]
right now I have issues with apptainer beyond fast surfer, however I believe that the right way to call it now should be, for instance,

apptainer exec  --nv ./fastsurfer-gpu.sif \ 
                 -B /home/user/my_mri_data:/data \
                 -B /home/user/my_fastsurfer_analysis:/output \
                 -B /home/user/my_fs_license_dir:/fs_license \
                 /fastsurfer/run_fastsurfer.sh 
                 *fastsurfer-flags*

for me it always wants at least 2 arguments for the build pointing directly to the image -- but I may be totally wrong! would be nice to have an example in the readme with that update for apptainer, thx a lot

**Comment by dkuegler** [comment]
apptainer should be called the same way singularity is called see https://github.com/Deep-MI/FastSurfer#example-2-fastsurfer-singularity

With respect to your example, make sure your linebreaks and the escaping of linebreaks is correct.

Also all apptainer arguments (like -B) go before the image name, fastsurfer arguments after.

**Comment by m-reuter** [comment]
I assume this is resolved, if not feel free to re-open.

**Comment by CPernet** [comment]
FYI apptainer messed up 'users' permissions on our server
this can be resolved export 
```
SINGULARITY_HOME=/users/yourusername
singularity run --cleanenv \
                 other arguments
```

**Comment by dkuegler** [comment]
Aptainer should often be run with `--no-home` as well (otherwise it will mount your user dir and your user options into the container). See our docs as well.

**Comment by CPernet** [comment]
Yes totally but somehow with no home it only runs always then cannot figure the user ID ... using both does the trick
