### ISSUE TITLE
Example for running fastsurfer with docker on Windows WSL: batch processing scripts

### ISSUE THREAD

**Issue by FahimFBA** [Deep-MI/FastSurfer#449]
## Documentation

...

I have used FastSurfer in my Linux machine (native) for my research work on 3D MRI Brain images from ADNI and OASIS. Currently, I am using FastSurfer via Docker GPU on my Windows machine.

As I needed to process more than 7/8K images, I created a bash script that takes all `.nii.gz` images from the input directory and does full work on all of them. 

I wanted to add the script as documentation in this repository so others can also be benefitted.

Please let me know what you think about that. I can add a pull request, but I need to know do I need to add the entire thing in existing documentation within the Windows Docker GPU segment, or do I need to create a new MarkDown file and link that under the Windows Docker GPU segment.

**Comment by dkuegler** [comment]
We already recently added (and updated) two scripts that do that kind of thing.
See brun_fastsurfer.sh and srun_fastaurfer.sh
There is also some documentation in the readme.md.

I am not really sure if your script does something different... Please have a look and say if there is something you are missing.

We would not like to double this functionality, if possible.

If you want to contribute additional documentation, we would be happy to look into that.

**Comment by FahimFBA** [comment]
After checking the scripts, my scripts might not be anything new to add to the repository. However, as I had created the issue, already, I think it is a good idea to show that script so that it might help others if they would also want something simple to just make their segmentation work through Docker, WSL2, Windows OS.

1. Batch process full recon: https://gist.github.com/FahimFBA/ee2add66c1bcbc401466b06e88cd37b9
2. Batch process - only segmentation: https://gist.github.com/FahimFBA/3b2af75e7f49ce21e45000b4d82e464b

**Comment by dkuegler** [comment]
It is always good to have examples to illustrate how fastsurfer can be run on different platforms, so we appreciate these examples as is.
