### ISSUE TITLE
Crash in nu_correct if FOV > 256

### ISSUE THREAD

**Issue by davecash75** [Deep-MI/FastSurfer#45]
Hi there-
I'm currently using the CPU Docker and I am running the standard docker command for the full FastSurfer as you have in the README, with the exception that I pass in a Nifti where the FOV is greater than 256 mm. WHen I run, the deep_seg runs fine but during the recon, I get a crash with the following key messages: 
WARNING ==================++++++++++++++++++++++++=======================================
The physical sizes are (228.80 mm, 282.00 mm, 282.00 mm), which cannot fit in 256^3 mm^3 volume.
The resulting volume will have 282 slices.
If you find problems, please let us know (freesurfer@nmr.mgh.harvard.edu).
==================================================++++++++++++++++++++++++===============
Mask volume and input volume must be the same size.
nu_evaluate: crashed while running evaluate_field (termination status=512)
nu_correct: crashed while running nu_evaluate (termination status=512)
ERROR: nu_correct
I run mri_convert with the --cw256 command outside of FastSurfer, and it no longer has this error. So I guess the question is would it be possible to have an option that conforms (and crops) images with FOV > 256 mm just like the original FreeSurfer allows.
Many thanks,
David Cash

**Comment by m-reuter** [comment]
Hi David, yes such a flag would make sense. Currently, with large field of view, you need to convert images yourself before you pass them into FastSurfer. If you end up modifying our scripts to take such a flag, please generate a pull request. Thanks

**Comment by m-reuter** [comment]
I have looked into this a little. conform.py seems to be able to automatically conform these to 255 cube images. So not sure why nu_correct fails later. It could be that the stream does not use this image, but instead runs a second conform (potentially from freeSurfer) without the -cw256 flag at a later stage again. We need to check the pipeline steps.

**Comment by m-reuter** [comment]
should be fixed by #92
