### ISSUE TITLE
Multiple subjects FastSurferCNN via Docker 

### ISSUE THREAD

**Issue by evaaamodt** [Deep-MI/FastSurfer#450]
## Question/Support Request
Hi, I`m trying to run the 1 min FastSurferCNN via Docker on multiple subjects, using brun. 
I`m getting this error;

INFO: run_fastsurfer not explicitly specified, using $FASTSURFER_HOME/run_fastsurfer.sh.
ERROR: T1 image (/home/eaamodt/fastsurfer/data/Z***_AX_T1_3D_MPRAGE_POST_MRI_BRAIN_W_WO_CONTRAST.nii.gz) could not be found. Must supply an existing T1 input (full head) via 
--t1 (absolute path and name) for generating the segmentation.
NOTES: If running in a container, make sure symlinks are valid!

The symbolic links in the subject list are however correct. Is there anything I'm doing wrong? I`m sure it`s something simple I`m not seeing.. 

### Execution
sudo docker run --gpus all \
-v /home/eaamodt/fastsurfer/data:/data \
-v /home/eaamodt/fastsurfer/output:/output \
-v /home/eaamodt/fastsurfer/FastSurfer-stable:/fs_license \
--entrypoint "/fastsurfer/brun_fastsurfer.sh" \
--rm --user $(id -u):$(id -g) \
deepmi/fastsurfer:latest \
--fs_license /fs_license/license.txt \
--sd /output --subject_list /data/subject_list.txt --seg_only --threads 25 --3T \

**Comment by dkuegler** [comment]
You are running the segmentation inside the container. The path you provided is the path on the host system.
What you need to do is edit the subject_list such that the paths are with respect to the docker, not the host file system.
The brun script does not do that for you (srun does, but only applies to slurm clusters).

So, open  /home/eaamodt/fastsurfer/data/subject_list.txt and replace all  /home/eaamodt/fastsurfer/data with /data. That should fix your problems.

This is what
> Note, that all paths (path_to_t1) are as if you passed them to the run_fastsurfer.sh script via --t1 <path> so they may be with respect to the singularity or docker file system. Absolute paths are recommended.

is also intending to say.

**Comment by evaaamodt** [comment]
Ah! I was thrown off by that sentence (absolute paths recommended) so I changed it to the whole path (d'oh!) Thank you so much - it is working now!
