### ISSUE TITLE
eTIV calculation  

### ISSUE THREAD

**Issue by evaaamodt** [Deep-MI/FastSurfer#452]
I am running FastSurferCNN with --seg_only via Docker. How can I get the eTIV?

**Comment by dkuegler** [comment]
The eTIV is not calculated in the seg_only pipeline, because FastSurfer uses FreeSurfer binaries and the FreeSurfer talairach registration to get the eTIV. So you only get the eTIV after `--surf_only` (or by not specifying `--seg_only`). 

And then it will have the numbers in `stats/aseg.stats`.

**Comment by evaaamodt** [comment]
Thank you!

**Comment by m-reuter** [comment]
The idea is that we compute the eTIV differently in the future (segmentation based) but not sure when that will be released.
