### ISSUE TITLE
FastSurfer on multiple subjects via Native Windows WSL

### ISSUE THREAD

**Issue by hylin-work** [Deep-MI/FastSurfer#454]
I tried to run multiple subjects using **brun_fastsurfer.sh** command with a subjects_list.txt as input.  Here are the execution command, subjects_list.txt and the screenshot of error message. 

I made several successful execution using run_fastsurfer.sh for single subject.   However, multiple-subject using brun_fastsurfer.sh does not work after several attempts.  Any suggest is very welcome.
 
![image](https://github.com/Deep-MI/FastSurfer/assets/77444078/d46471e4-e6c1-430e-ab20-6cb222be5c70)

## Environment
 - FastSurfer Version: v2.2.0
 - OS: Windows WSL (Ubuntu 20.04.6 LTS)

### Execution
Run Command: 
($FASTSURFER_HOME/brun_fastsurfer.sh --subject_list $inputDir/subjects_list.txt --sd $outputDir --seg_only --py python3 --parallel --threads 16 --allow_root --debug)

Content in the subjects_list.txt:
subject_id1=/home/hlin/fastsurfer/Tutorial/data/1.nii.gz 
subject_id2=/home/hlin/fastsurfer/Tutorial/data/2.nii.gz 

Error message:
INFO: run_fastsurfer not explicitly specified, using $FASTSURFER_HOME/run_fastsurfer.sh.
DEBUG: subject 1: subject_id1=/home/hlin/fastsurfer/Tutorial/data/1.nii.gz
 --sd /home/hlin/fastsurfer/Tutorial/output --py python3 --parallel --threads 16 --allow_root [&]urfer/Tutorial/data/1.nii.gz
) could not be found. Must supply an existing T1 input (full head) via
--t1 (absolute path and name) for generating the segmentation.
NOTES: If running in a container, make sure symlinks are valid!

**Comment by dkuegler** [comment]
The text looks a bit garbled. 

Can you make sure, your line endings in the subject_list file are with \n?

We used to have that in the doc, but that confused some people...

**Comment by hylin-work** [comment]
Here is the subjects_list.txt file I created for this command. I clicked "Enter" for each "new line" using either "Notepad+" in Windows or "nano" in Ubuntu.  

Thanks for your time to  troubleshooting this issue because I was frustrated after two days of trial-and-error.
 
[subjects_list.txt](https://github.com/Deep-MI/FastSurfer/files/14229443/subjects_list.txt)

**Comment by dkuegler** [comment]
![Screenshot 2024-02-10 224710](https://github.com/Deep-MI/FastSurfer/assets/12848082/3a2b1a0d-2509-4377-9c78-7e1675042310)

This is how you can make Notepad++ show the line endings.

<img width="528" alt="Screenshot 2024-02-10 224808" src="https://github.com/Deep-MI/FastSurfer/assets/12848082/5dda7b0c-99b9-4848-8c25-8459d79154ef">

This is how you change the line endings in Notepad++

<img width="511" alt="Screenshot 2024-02-10 224825" src="https://github.com/Deep-MI/FastSurfer/assets/12848082/b2823df8-28fa-4b3e-913a-894e4518eac4">

This is what it looks like after.

**Comment by hylin-work** [comment]
I made the change in Notepad+ based on your recommendation.  However, the error message seems the same as before.  Please see the new subjects_list.txt and error output using --debug options.

Thanks.


[subjects_list.txt](https://github.com/Deep-MI/FastSurfer/files/14230931/subjects_list.txt)


(test_requirement) hlin@DESKTOP-MGFR1CH:~/fastsurfer/Tutorial/data$ ($FASTSURFER_HOME/brun_fastsurfer.sh --subject_list $inputDir/subjects_list.txt --sd $outputDir --seg_only --py python3 --parallel --threads 16 --allow_root --debug)
/home/hlin/fastsurfer/brun_fastsurfer.sh --subject_list /home/hlin/fastsurfer/Tutorial/data/subjects_list.txt --sd /home/hlin/fastsurfer/Tutorial/output --seg_only --py python3 --parallel --threads 16 --allow_root --debug
Sat, 10 Feb 2024 16:51:50 -0800

---START DEBUG---
Debug parameters to script brun_fastsurfer:

subjects:
subject_id1=/home/hlin/fastsurfer/Tutorial/data/1.nii.gz subject_id2=/home/hlin/fastsurfer/Tutorial/data/2.nii.gz
---
task_id/task_count: /
running default

FastSurfer parameters:
--seg_only

--sd /home/hlin/fastsurfer/Tutorial/output
--py python3
--parallel
--threads 16
--allow_root
Running in  /usr/bin/bash

---END DEBUG  ---
INFO: run_fastsurfer not explicitly specified, using $FASTSURFER_HOME/run_fastsurfer.sh.
DEBUG: subject 1: subject_id1=/home/hlin/fastsurfer/Tutorial/data/1.nii.gz
DEBUG: /home/hlin/fastsurfer/run_fastsurfer.sh --seg_only --sid subject_id1 --t1 /home/hlin/fastsurfer/Tutorial/data/1.nii.gz  --sd /home/hlin/fastsurfer/Tutorial/output --py python3 --parallel --threads 16 --allow_root [&]
ERROR: T1 image (/home/hlin/fastsurfer/Tutorial/data/1.nii.gz ) could not be found. Must supply an existing T1 input (full head) via
--t1 (absolute path and name) for generating the segmentation.
NOTES: If running in a container, make sure symlinks are valid!

![image](https://github.com/Deep-MI/FastSurfer/assets/77444078/be146e98-a9ce-459e-aa3f-15ba417f075b)

**Comment by dkuegler** [comment]
At this point the error message is what I have to go by, the rest looks pretty clean.

Are you sure `/home/hlin/fastsurfer/Tutorial/data/1.nii.gz` exists? You can also run "plain fastsurfer" see the highlighted part of the output to see if that is working.

> DEBUG: **/home/hlin/fastsurfer/run_fastsurfer.sh --seg_only --sid subject_id1 --t1 /home/hlin/fastsurfer/Tutorial/data/1.nii.gz --sd /home/hlin/fastsurfer/Tutorial/output --py python3 --parallel --threads 16 --allow_root** [&]

**Comment by dkuegler** [comment]
Turns out there is a space at the end of each line in the subjects list.

![grafik](https://github.com/Deep-MI/FastSurfer/assets/12848082/7ebaa276-eece-46cc-9eb0-90546d753ef3)

That should not be there

**Comment by hylin-work** [comment]
Wow! It works perfectly. The space in the end of each line is really matter.  

The devil is in the details.  Thanks for help. @dkuegler
