### ISSUE TITLE
where are cerebellum segmentation maps stored ? (Schmahmann atlas)

### ISSUE THREAD

**Issue by lydiachougar** [Deep-MI/FastSurfer#460]
Hi,

Is there a way to obtain the atlas used by CerebNet for the cerebellar segmentation? I can find it in the different folders when I download Fastfurfer.

Best,
Lydia

**Comment by dkuegler** [comment]
Hi Lydia,

I am uncertain what you mean. Cerebellum segmentation maps are stored in `<subject directory>/<subject id>/mri/cerebellum.CerebNet.nii.gz`. 

That is not 100% the Schmahmann atlas as described in the CerebNet paper -- some smaller regions are merged.

**Comment by m-reuter** [comment]
Hi Lydia, 
the atlas/protocol that was used to segment the cerebellum manually follows the Schmahmann atlas (mainly but not completely) and is described in the CerebNet paper as well as here: https://www.medrxiv.org/content/10.1101/2022.05.09.22274814v1.full.pdf

In CerebNet there is no atlas file or standard space/image. We train with manually segmented images and you get the trained network. You can run it on your data and obtain the segmentation in the path posted by David above.

**Comment by lydiachougar** [comment]
Hi,

Thanks for your replies. 
I needed an atlas file for further analyses. What I did was run the CerebNet segmentation on the MNI template to create a kind of atlas in MNI space.

Best,
Lydia

**Comment by m-reuter** [comment]
Hi, the template image could be an average of multiple MRIs or it could be from an old unsupported scanner etc. etc. So the segmentation quality can differ a lot from what we tested. Just want to make sure you are aware of this risk.

**Comment by lydiachougar** [comment]
OK, thank you. The segmentation seems accurate.
Best,
Lydia


Le ven. 23 févr. 2024 à 08:57, Martin Reuter ***@***.***> a
écrit :

**Comment by zhenzonglin** [comment]
@lydiachougar 
Dear Lydia, 

Hi.

The CerebNet segmentation on MNI that you mentioned is interesting, and I also want to further analyze on this atlas. May I ask if your results are published so that I can cite them, thanks.

Best,
Zhenzong Lin
linzhenzong1@163.com
