### ISSUE TITLE
N4 bias field correction without rescaling also converts to UCHAR

### ISSUE THREAD

**Issue by dkuegler** [Deep-MI/FastSurfer#461]
## Description
In recon_surf/N4_bias_correct.py if it is called to output the --outvol, but the input is not UCHAR (i.e. the mean is not around 150 or so) the script renormalizes the input to the old mean (of the input image). After that, it is converted to UCHAR by clamping, so all intensity information >255 is lost. This is not an expected behavior.

## Steps to Reproduce
Run N4_bias_correct on an image that is not UCHAR / not conformed.

## Expected Behavior
Retains data type, or additional flag for conforming intensities.

**Comment by m-reuter** [comment]
I think the expected behaviour if only bias field is corrected,  is to keep data type. If also intensities are rescaled to 0--255 then the default could be to convert to UCHAR (as that is the main reason of scaling to that range).

**Comment by dkuegler** [comment]
I agree, but scaling/conversion to UCHAR is probably likely use case (at least we need it for #459 ), so maybe by default we keep the data type of the input, but we can also add an option to rescale the not am normalized image to UCHAR and that the also is a robust scaling (that also gives us limits on how to scale, i.e. by percentiles).
