### ISSUE TITLE
python3.10 command not found: error running ./run_fastsurfer.sh

### ISSUE THREAD

**Issue by suhanasaigoli05** [Deep-MI/FastSurfer#464]
running: 
./run_fastsurfer.sh --t1 $datadir/bert/mri/T1.mgz \
                    --sid bert --sd $fastsurferdir \
                    --parallel --threads 4 --3T
error:
<img width="1066" alt="image" src="https://github.com/Deep-MI/FastSurfer/assets/63617775/def5dc1d-e13f-4134-b120-f2d59ee51770">

## Environment
 - OS: MacOS
 - Native install

python packages:
<img width="234" alt="image" src="https://github.com/Deep-MI/FastSurfer/assets/63617775/38c6cee0-35c0-450b-b2ce-8dc8fa52e797">
<img width="256" alt="image" src="https://github.com/Deep-MI/FastSurfer/assets/63617775/e7fe54c5-3bfb-4156-ac06-dd6f9a94156d">
<img width="229" alt="image" src="https://github.com/Deep-MI/FastSurfer/assets/63617775/d30fd8ed-b873-4deb-9eac-8d05b0d2dafe">

Run Command: 

export FREESURFER_HOME=//Applications/freesurfer/7.4.1
source $FREESURFER_HOME/SetUpFreeSurfer.sh
datadir=/Applications/freesurfer/7.4.1/subjects
fastsurferdir=/Users/username/Applications/FastSurfer
./run_fastsurfer.sh --t1 $datadir/bert/mri/T1.mgz \
                    --sid bert --sd $fastsurferdir \
                    --parallel --threads 4 --3T

**Comment by dkuegler** [comment]
Hi,

It seems you are running python 3.11.4. Fastsurfer 2.2 only officially supports python 3.10., but you should still be able to run Fastsurfer with 3.11 by adding the flag `--py python3.11` though.

Although our recommendation would be to set up an environment with python 3.10...

**Comment by m-reuter** [comment]
Could also be an old bash version or the "tee" command ?

**Comment by m-reuter** [comment]
closing this for now, feel free to re-open if this does not solve the issue.
