### ISSUE TITLE
CC values all 0 in aseg+DKT.stats

### ISSUE THREAD

**Issue by karllandheer** [Deep-MI/FastSurfer#469]
Hello, attached is a screenshot of an aseg+DKT.stats file I have. As you can see, the CC values are all 0. I assume I am doing something wrong? Any ideas?

<img width="874" alt="Screenshot 2024-03-05 at 12 09 17 PM" src="https://github.com/Deep-MI/FastSurfer/assets/76697225/a1f9a22e-97c7-4f4b-b7ee-c8e41ded8ca0">

**Comment by m-reuter** [comment]
maybe. What is the command you ran? The CC is added later in the recon-surf pipeline, but there is an option to stop after CC is added and not run the full surfaces.

**Comment by karllandheer** [comment]
Hello, sorry I should have included it. This is the line I have used to run it:

```
docker run -v ${SETUP_DIR}:/data my_fastsurfer:cpu \
   --t1 /data/T1_unbiased_brain.nii.gz --sd /data/  --sid Tutorial \
   --py python3 --allow_root --3T  --fs_license /data/FreeSurferLicense.txt \
   --parallel --fsaparc --threads 2
```

**Comment by m-reuter** [comment]
Thanks, looks good. So I check the readme and the aseg+DKT.stats file gets created directly after the segmentation, so it will not yet contain the CC. You should look e.g. at the aseg.stats for that.

**Comment by m-reuter** [comment]
Did you find the CC values in aseg.stats? I will close this now. Feel free to re-open if those values cannot be found there.

**Comment by karllandheer** [comment]
Hello, yes it is there. Thank you for the great support!!
