### ISSUE TITLE
Error during smooth_aparc.py mode_filter

### ISSUE THREAD

**Issue by rafaloz** [Deep-MI/FastSurfer#479]
## Question/Support Request
I am processing my database with FastSurfer (they are T1w FSPGR acquisitions) and during mode_filter once the labels for the surface segmentation are being smoothed and reorganized, I get the next error in the recon-surf.log:

_writing annotation to aparc.DKTatlas.mapped.prefix.annot...
@#@FSTIME  2024:03:09:12:47:37 mris_sample_parc N 14 e 11.48 S 3.97 U 8.05 P 104% M 17596356 F 0 R 2205592 W 0 c 33 w 195 I 0 O 2104 L 8.31 8.55 7.76
@#@FSLOADPOST 2024:03:09:12:47:48 mris_sample_parc N 14 8.02 8.47 7.75
python3.10 /home/saprn1/FastSurfer/recon_surf/smooth_aparc.py --insurf /cubric/collab/349_alspactd/scratch/rafa/subjects_FS/10008A_brain/surf/rh.white.preaparc --inaparc /cubric/collab/349_alspactd/scratch/rafa/subjects_FS/10008A_brain/label/rh.aparc.DKTatlas.mapped.prefix.annot --incort /cubric/collab/349_alspactd/scratch/rafa/subjects_FS/10008A_brain/label/rh.cortex.label --outaparc /cubric/collab/349_alspactd/scratch/rafa/subjects_FS/10008A_brain/label/rh.aparc.DKTatlas.mapped.annot
Reading in surface: /cubric/collab/349_alspactd/scratch/rafa/subjects_FS/10008A_brain/surf/rh.white.preaparc ...
Reading in annotation: /cubric/collab/349_alspactd/scratch/rafa/subjects_FS/10008A_brain/label/rh.aparc.DKTatlas.mapped.prefix.annot ...
Reading in cortex label: /cubric/collab/349_alspactd/scratch/rafa/subjects_FS/10008A_brain/label/rh.cortex.label ...
Non-cortex vertices with labels: 67
Fill Round: 1
rows: 881  reduced to 428
[11 11 11 11]
11
Traceback (most recent call last):
  File "/home/saprn1/FastSurfer/recon_surf/smooth_aparc.py", line 367, in <module>
    smooth_aparc(options.insurf, options.inaparc, options.incort, options.outaparc)
  File "/home/saprn1/FastSurfer/recon_surf/smooth_aparc.py", line 333, in smooth_aparc
    labels_new = mode_filter(adjM, labels, fillonlylabel, np.array([fillonlylabel]))
  File "/home/saprn1/FastSurfer/recon_surf/smooth_aparc.py", line 238, in mode_filter
    labels_new[ids[row]] = mvals[0]
IndexError: invalid index to scalar variable.
Command exited with non-zero status 1_

I tried to add print commands for ids, row and mvals, but it is not printing anything out... Has this been a recurrent error? 

## Screenshots
I can't see any big defects in the previous steps:

![Captura desde 2024-03-11 14-00-26](https://github.com/Deep-MI/FastSurfer/assets/19437794/d39cf3ad-32a2-4fd7-b88b-58faa45dd13a)

## Environment
 - FastSurfer Version: 2.2.0
 - FreeSurfer Version: 7.4.1
 - OS: Centos Linux 7
 - CPU: Intel Xeon ES472 3.00 GHz
 - GPU: Nvidia-a100

I run the FastSurfer v2.2.0 requirements.txt file to create my conda environment on which I am running fastsurfer.

Run Command: 

t1_file=/xxxxx/collab/xxxxxxx/scratch/rafa/data/10008A/10008A_brain.nii
filename="${t1_file##*/}"
filename_no_ext="${filename%.nii}"
./run_fastsurfer.sh --t1 ${t1_file} --sid ${filename_no_ext} --sd $SUBJECTS_DIR --parallel --3T --threads 4

**Comment by m-reuter** [comment]
Hi @rafaloz , I haven't seen this error before. It looks like a bug in the code, that only happens in rare situations. For some reason one of those variables is not an array therefore should not be indexed. 
If you add print statements and call the python file directly with the listed command it should print those values. 
If you can share the inputs (not the image, just the insurf, aparc and cortex label) we could also try to debug this here.

**Comment by rafaloz** [comment]
Hello @m-reuter, I have been trying to debug it myself but there are many things I do not understand about the whole pipeline so it is taking me a while. If you can help me I'll be very thankful! Here are the files: 

[10008A_brain.tar.gz](https://github.com/Deep-MI/FastSurfer/files/14587971/10008A_brain.tar.gz)

**Comment by m-reuter** [comment]
Hi, I just ran this on my machine and it works (using dev, not sure if there have been any changes). 

```
python3 smooth_aparc.py \         
    --insurf 10008A_brain/surf/rh.white.preaparc \
    --inaparc 10008A_brain/label/rh.aparc.DKTatlas.mapped.prefix.annot \
    --incort 10008A_brain/label/rh.cortex.label \
    --outaparc 10008A_brain/label/rh.aparc.DKTatlas.mapped.annot
Reading in surface: 10008A_brain/surf/rh.white.preaparc ...
Reading in annotation: 10008A_brain/label/rh.aparc.DKTatlas.mapped.prefix.annot ...
Reading in cortex label: 10008A_brain/label/rh.cortex.label ...
Non-cortex vertices with labels: 67
Fill Round: 1
rows: 881  reduced to 428
Fill Round: 2
rows: 453  reduced to 209
Fill Round: 3
rows: 244  reduced to 75
Fill Round: 4
rows: 169  reduced to 38
Fill Round: 5
rows: 131  reduced to 31
Fill Round: 6
rows: 100  reduced to 19
Fill Round: 7
rows: 81  reduced to 14
Fill Round: 8
rows: 67  reduced to 7
Fill Round: 9
rows: 60  reduced to 8
Fill Round: 10
rows: 52  reduced to 8
Fill Round: 11
rows: 44  reduced to 7
Fill Round: 12
rows: 37  reduced to 7
Fill Round: 13
rows: 30  reduced to 8
Fill Round: 14
rows: 22  reduced to 6
Fill Round: 15
rows: 16  reduced to 6
Fill Round: 16
rows: 10  reduced to 5
Fill Round: 17
rows: 5  reduced to 3
Fill Round: 18
rows: 2  reduced to 2
rows: 133486  reduced to 32026
rows: 133486  reduced to 15615
rows: 133486  reduced to 7644
Outputting fixed annot: 10008A_brain/label/rh.aparc.DKTatlas.mapped.annot
```

Things you can try:
- run everything in our released docker image (to make sure you have the right dependencies installed, maybe there is a problem)
- checkout our dev branch and use the smooth_aparc.py from there in case there were any changes.

**Comment by m-reuter** [comment]
Also I tested with nibabel version 5.0.1, 5.1.0 and 5.2.1 and it worked with all of them.

**Comment by rafaloz** [comment]
Hi @m-reuter, you are right, I reinstalled FastSurfer and is working flawlessly. Thanks for the help, sorry for the inconvenience.
