### ISSUE TITLE
Biasfield-corrected image input of the segstats.py

### ISSUE THREAD

**Issue by gmeng92** [Deep-MI/FastSurfer#485]
## Question/Support Request
Thanks for the implementation of the auto segmentation model! I use it for a mix of healthy subjects and patients with degenerative disease and it works pretty well!  I have some question regarding the input images to the segstats.py in FastSurferCNN. 

1. According to the help function, a " Biasfield-corrected image in the same image space as segmentation" is required to calculate the summary statistics. Is this the same image as the conform_image of the output of run_prediction.py? I assume it it not. Because I did not see any biased correction step in the run_prediction script. If not, what is the best way to get that biased corrected image?
2. If I understand the output aseg.stats correctly, all the columns with prefix "norm"(like normMean, etc) are derived from the biasfield-corrected images while the Nvoxels  is directly derived from the segmentation results. That means, if I only need the Nvoxels, I don't have to use the Biasfield-corrected images, right?

**Comment by m-reuter** [comment]
Hi, if you use our most recent release even if you run only the segmentation module, the `orig_nu.mgz`and stats should be created for you automatically. In earlier versions this only happened in the surface module. 

1. the conform step alone, does not bias correct. We recommend you use the newest release version (see above). 
2. principally you are right, but we also have a column with partial volume corrected values, this is not purely the voxel count, as some voxels are not fully inside or outside a structure. The partial volume correction needs the bias corrected image to compute the values. They will be more accurate than the simple voxel count.

**Comment by dkuegler** [comment]
Just to add to this answer.
Since FastSurfer 2.2, the `run_fastsurfer.sh` script includes a bias-field correction step in the segmentation pipeline (previously it was part of the surface pipeline). As Martin has said, this is the `mri/orig_nu.mgz` file. If you want to generate this file yourself, you could use the `recon_surf/N4_bias_correct.py` script, but generally, we would recommend, you just use the `run_fastsurfer.sh` script. There, is also a call to segstats.py in `run_fastsurfer.sh` in the segmentation pipeline, which generates this stats file `stats/aseg+DKT.stats`.

**Comment by gmeng92** [comment]
> Hi, if you use our most recent release even if you run only the segmentation module, the `orig_nu.mgz`and stats should be created for you automatically. In earlier versions this only happened in the surface module.
> 
> 1. the conform step alone, does not bias correct. We recommend you use the newest release version (see above).
> 2. principally you are right, but we also have a column with partial volume corrected values, this is not purely the voxel count, as some voxels are not fully inside or outside a structure. The partial volume correction needs the bias corrected image to compute the values. They will be more accurate than the simple voxel count.

Thanks! That answers my question!

**Comment by gmeng92** [comment]
> Just to add to this answer. Since FastSurfer 2.2, the `run_fastsurfer.sh` script includes a bias-field correction step in the segmentation pipeline (previously it was part of the surface pipeline). As Martin has said, this is the `mri/orig_nu.mgz` file. If you want to generate this file yourself, you could use the `recon_surf/N4_bias_correct.py` script, but generally, we would recommend, you just use the `run_fastsurfer.sh` script. There, is also a call to segstats.py in `run_fastsurfer.sh` in the segmentation pipeline, which generates this stats file `stats/aseg+DKT.stats`.

Great! Then I will try both and see which fits my needs better.
