### ISSUE TITLE
Use of '--rm' argument in build.py results in a TypeError

### ISSUE THREAD

**Issue by jrussell9000** [Deep-MI/FastSurfer#486]
## Description
Use of '--rm' argument when running docker build script results in TypeError.

## Steps to Reproduce
Clone dev branch, 'python build.py --device cu118 --tag fast:dev --target runtime --rm'.

![image](https://github.com/Deep-MI/FastSurfer/assets/25013843/a4b63e28-16f6-49fe-8cc4-e6d3789e48c8)

## Environment
 - FastSurfer Version: Current dev branch as of 03162024
 - FreeSurfer Version: N/A
 - OS: Ubuntu 22.04
 - CPU: Intel Xeon 8164
 - GPU: Tesla V-100
 - Python 3.10.13 in a conda environment

**Comment by dkuegler** [comment]
Thanks for reporting this issue.

I think we will just remove support for the `--rm` flag. This flag is discouraged, because it means that the time-consuming steps of the build will not be cached, which makes little sense... So the benefit of this flag is not significant :).

**Comment by jrussell9000** [comment]
Works for me!

**Comment by m-reuter** [comment]
I think we should keep this open until the --rm flag is removed or solved. Also I had other issues with the build script which should be fixed at the same time.

**Comment by dkuegler** [comment]
Both these issues should be addressed in #489 .

#489 removes the --rm flag and tries to allow building without buildx... I cannot really check that as all our machines seem to have buildx.
