### ISSUE TITLE
Is it possible to get segstats of cerebellum after run FastSurfer pipeline?

### ISSUE THREAD

**Issue by iPsych** [Deep-MI/FastSurfer#491]
## Question/Support Request

Is it possible to get segstats of cerebellum after run FastSurfer pipeline?
Since the default option is not generating segstats, I wonder if I should run all pipeline,  or can generate segstats for cerebellum afterwards.

Bests,

**Comment by m-reuter** [comment]
After running the cerebnet module, which is part of the segmentation pipeline, you should get the statsfile, see : 
https://deep-mi.org/FastSurfer/dev/overview/OUTPUT_FILES.html#cerebnet-module 

You can run with `--seg_only`, which will include cerebnet. No need to run the longer surface pipeline for this. 
Make sure you use the latest release.

**Comment by iPsych** [comment]
> After running the cerebnet module, which is part of the segmentation pipeline, you should get the statsfile, see : 
> 
> https://deep-mi.org/FastSurfer/dev/overview/OUTPUT_FILES.html#cerebnet-module 
> 
> 
> 
> You can run with `--seg_only`, which will include cerebnet. No need to run the longer surface pipeline for this. 
> 
> Make sure you use the latest release. 

Thanks. 
Actually, I ran only cerebnet with already processed data via python directly as below.

python CerebNet/run_prediction.py  --t1 $t1 --asegdkt_segfile $asegdkt_segfile --conformed_name $conformed_name --cereb_segfile $cereb_segfile --seg_log $seg_log --batch_size $batch_size --viewagg_device $viewagg --device $device --async_io --threads $threads

I missed --cereb_statsfile $cereb_statsfile, so the statsfile did not generated.

**Comment by m-reuter** [comment]
You can either do the hard work of looking into run_fastsurfer scripts and also manually replicate the other steps, or you can just run the `--seg_only`again (takes only minutes per case) and get everything you need.
