### ISSUE TITLE
custom data in google colab do not work for me

### ISSUE THREAD

**Issue by layerfMRI** [Deep-MI/FastSurfer#50]
Thanks to Leoni Henschel for the nice tutorial via ISMRM this morning. 

I tested the Tutorial FastSurferCNN-QuickSeg via google colab following the live tutorial. 
It works for me with the "Alternative" solution of using the provided data (FreeSurfer tutorial). However, it does not seem to work with any other data. 

1.) As soon as I used the "alternative solution once, it seems to look at the wrong location (/content vs /content/fastfurfer).

2.) It does not seem to be able to find the atribute "data" (full error message at his [link).](https://www.dropbox.com/s/m99qmfs9mhrvrg4/Screenshot%202021-05-17%20at%2011.11.19.png?dl=1) I tried multiple MP2RAGE data in nii/nii.gz/mgz. But I always get the same error. 
Can you point me to descriptions of how I need to prepare my data to work for the tutorial? 

Thanks a lot, Renzo

**Comment by LeHenschel** [comment]
Hey Renzo,

thanks a lot. There was an error in the conform function (it should have been img.get_data() not img.dat(). It should be fixed now.

Best,
Leonie

**Comment by layerfMRI** [comment]
thanks a lot Leonie, It works now. 👍  😁

**Comment by LeHenschel** [comment]
Perfect :). I am closing this issue than.
