### ISSUE TITLE
FastSurfer surf pipeline did not finish: Missing .label files (not enough memory for mris_sample_parc)

### ISSUE THREAD

**Issue by mwendhaus** [Deep-MI/FastSurfer#503]
Hello, 
I am running FastSurfer using the provided Docker container from an Intel MacBook Pro. I use this command:

```
#!/bin/bash

export FREESURFER_HOME=/Applications/freesurfer/7.4.1
source $FREESURFER_HOME/SetUpFreeSurfer.sh

docker run            -v .../nifti_files/:/data \
                      -v ...:/output \
                      -v ...:/fs_license \
                      --rm --user $(id -u):$(id -g) deepmi/fastsurfer:latest \
                      --fs_license /fs_license/license.txt \
                      --t1 /data/mri_data_t1.nii.gz \
                      --sid subjectX --sd /output \
                      --parallel \
                      --3T \
```
The code runs fine, however I am missing several .label files in the resulting label folder, which are described in the OUTPUT_FILES.md, such as lh.aparc.DKTatlas.mapped.annot. The log files do not suggest any obvious error. I am thankful for any hint on what I might be doing wrong!
<img width="502" alt="image" src="https://github.com/Deep-MI/FastSurfer/assets/133356156/0c658321-77e2-4659-b162-8351b1d201f5">

**Comment by dkuegler** [comment]
Hi,

first off, you dont need to source FreeSurfer if you are using the docker container.

As for the data: Can you share your log files anyways, so we can have a look?

Kind regards,
David

**Comment by mwendhaus** [comment]
Thank you very much for the fast reply. I am attaching the recon-all.log, if any other file might be necessary please let me know.
[recon-all.log](https://github.com/Deep-MI/FastSurfer/files/14884996/recon-all.log)

**Comment by dkuegler** [comment]
Sorry, can you please send the deep-seg.log and the recon-surf.log?

**Comment by mwendhaus** [comment]
Of course:
[deep-seg.log](https://github.com/Deep-MI/FastSurfer/files/14901583/deep-seg.log)
[recon-surf.log](https://github.com/Deep-MI/FastSurfer/files/14901584/recon-surf.log)

**Comment by dkuegler** [comment]
`mris_sample_parc` gets terminated
`Command terminated by signal 9`

We have had some issues with `mris_sample_parc` acquiring excessive amounts of memory. This issue has been fixed in #430 , but we have not released a new docker image yet. 
You can try giving docker more memory by for example `--shm-size 8G` see https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources and see also https://github.com/Deep-MI/FastSurfer/tree/dev/Docker#example-3-experimental-build-for-amd-gpus

**Comment by mwendhaus** [comment]
Great, thank you very much for the help!

**Comment by mwendhaus** [comment]
Just to complete this case, I got the same error using --shm-size 8G, and increased to --shm-size 12G to make sure. This worked fine and all necessary files were generated.

**Comment by dkuegler** [comment]
@mwendhaus I am confused, you got the same error, BUT all necessary files were generated?

**Comment by mwendhaus** [comment]
I got the same error as before when I used the flag --shm-size 8G. However, when I further increased the memory to 12G, I did not get the error, and the files were created.

**Comment by dkuegler** [comment]
Thank you! I believe this underlying issue is solved with the current dev version anyways, but good you were able to run FastSurfer.

**Comment by mwendhaus** [comment]
Thank you for the help!
