### ISSUE TITLE
Question about content of wmparc.DKTatlas.mapped.mgz

### ISSUE THREAD

**Issue by karllandheer** [Deep-MI/FastSurfer#508]
Hello, I am just curious what exactly is inside wmparc.DKTatlas.mapped.mgz. Am I correct in that it contains all labels of aparc.DKTatlas+aseg.deep.withCC.mgz but also parcellates the white matter? For example if I am interested in quantifying something in all brain regions, can I just use wmparc.DKTatlas.mapped.mgz? Or should I still use aparc.DKTatlas+aseg.deep.withCC.mgz for the gray matter parcellations? Thanks very much!

**Comment by dkuegler** [comment]
There is an overview of the different files here:
https://github.com/Deep-MI/FastSurfer/blob/dev/doc/overview/OUTPUT_FILES.md

Generally, `wmparc` is the white matter parcellation, while `aparc` is the gray matter parcelleation. So they are not comparable.

Also, `aparc.DKTatlas+aseg.deep.withCC.mgz` is the parcellation based on the segmentation from the segmentation pipeline, without the updates from the the FreeSurfer surface reconstruction. `wmparc.DKTatlas.mapped.mgz` is after surface updates (`mapped`), where the parcellation from the surface is `mapped` to the image. So gray matter statistics between `wmparc.DKTatlas.mapped.mgz` and `aparc.DKTatlas+aseg.mapped.mgz` should not really differ.
