### ISSUE TITLE
Support for lesion masks?

### ISSUE THREAD

**Issue by ghost** [Deep-MI/FastSurfer#509]
Hello, 

I saw in a previous post something about a "lesion-robust tool" and was wondering if, when, and how his can be used to improve segmentation and surface reconstruction. I have a lot of subjects with brain tumors (often GBMs) where segmentation results are good but often contain errors around the lesion. Is this something that's available now?

Thanks, 

Travis

**Comment by m-reuter** [comment]
Hi Travis, we are indeed working on a lesion robust version that supports lesion masks. We are in the final stages of running experiments and finishing the paper. Usually we make the code public after paper acceptance and final testing. So this can still take months. Maybe we can share an early development version at some point for testing. Send an email.
