### ISSUE TITLE
Docker build workflows

### ISSUE THREAD

**Issue by m-reuter** [Deep-MI/FastSurfer#517]
## Description

Currently docker build workflow seem to be broken:

https://github.com/Deep-MI/FastSurfer/actions/runs/8897578099

Maybe this is still not adjusted to the current build workflow? It started when I published a release, the CPU version build (but did not upload, which could be because this version is already published there, or because it does not understand the all-tags flag?). 

The GPU version never builds. 

We should discuss how we want this to work in the future and fix it. One issue is that optimally the version that is uploaded to docker should also be the image that was tested with out test pipeline. So maybe we should disable the workflow?

**Comment by dkuegler** [comment]
This is not using the Docker/build.py script for some reason. I am not sure who merged this workflow, I certainly never reviewed this.

**Comment by dkuegler** [comment]
Actually, I did comment on the commit, but my [comment](https://github.com/Deep-MI/FastSurfer/pull/278#issuecomment-1819356245) was never followed up... despite the [conversation](https://github.com/Deep-MI/FastSurfer/pull/278#issuecomment-1856165405) saying so...
weird.

**Comment by dkuegler** [comment]
**deleted my comment** that was incorrect.

**Comment by dkuegler** [comment]
So the message is
```
System.IO.IOException: No space left on device : '/home/runner/runners/2.316.0/_diag/Worker_20240430-181019-utc.log'
```

No space is not an issue we can easily solve. Maybe [large runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#specifications-for-general-larger-runners). Alternatively, this can also be run on private runners instead of on github runners...

**Comment by dkuegler** [comment]
I had another look at the CPU build and that is due to a bug in the script 
```
Run docker push --all-tags ***/fastsurfer:cpu-v.2.2.0
  docker push --all-tags ***/fastsurfer:cpu-v.2.2.0
  shell: /usr/bin/bash -e {0}
tag can't be used with --all-tags/-a
Error: Process completed with exit code 1.
```

**Comment by dkuegler** [comment]
I just realized we are a bit lucky, because re-building these images would have changed the (versioned) static images for Fastsurfer. That means same version docker Images may have lead to different images based on when they were pulled...

**Comment by m-reuter** [comment]
I stoped automated runs of this workflow in dev and stable for now. Once we decided how to do this in the future, we can delete those files.
