### ISSUE TITLE
DKTAtlas instead of aparc.stats file in FastSurfer

### ISSUE THREAD

**Issue by farah-naz01** [Deep-MI/FastSurfer#527]
## Question/Support Request
I used to extract the cortical thickness from aparc files produced by freesurfer recon_all and the output with the names "lh.aparc.stats and rh.aparc.stats" saved in stats folder. Now I tried FastSurfer, and the stats folder contains aparc files with the names "lh.aparc.DKTatlas.mapped.stats, and rh.aparc.DKTatlas.mapped.stats". 

My question is, are these the same outputs with different names?

**Comment by m-reuter** [comment]
FastSurfer is using the newer DKT atlas (FreeSurfer's default is the older DK atlas, but it also generates the DKT results). DKT is only a small modification with some cleaned up boundaries and a few structures merged. See also  https://mindboggle.readthedocs.io/en/latest/labels.html and the linked publication.

**Comment by m-reuter** [comment]
https://www.frontiersin.org/journals/neuroscience/articles/10.3389/fnins.2012.00171/full#T2

> Three regions were eliminated from the original DK protocol: the frontal and temporal poles and the banks of the superior temporal sulcus. The poles were eliminated because their boundaries were comprised primarily of segments that “jumped” across gyri rather than along sulci. By redistributing these regions to surrounding gyri we have increased the portion of region boundaries that along similar curvature values, that is, along sulci and gyri rather than across them, which improves automatic labeling and the reliability of manual edits. The banks of the superior temporal sulcus region was eliminated because its anterior and posterior definitions were unclear and it spanned a major sulcus. Additional, more minor, modifications took the form of establishing distinct sulcal boundaries when they approximated a boundary in the original protocol that was not clearly defined. ...

**Comment by m-reuter** [comment]
And finally you can of course create the stats file for the older atlas. Either by running the appropriate FreeSurfer command which (given that the registration is already established) will only take a few minutes. Or by adding the flag ```--fsaparc``` but that runs FreeSurfer code for all surface segmentations instead of mapping the ones from our deep learning module. So you should keep this consistent for a full study and not mix results. See also #51
