### ISSUE TITLE
no-cache argument for build.py

### ISSUE THREAD

**Issue by jrussell9000** [Deep-MI/FastSurfer#531]
In the Docker/build.py, is it possible to append a 'no-cache' argument? This may already be possible with the current script but if not, it would be helpful! Open to other suggestions as well!

**Comment by dkuegler** [comment]
Attaching a `--no-cache` string is currently not possible from the command line.

But what you can do is running 
```bash
$(python Docker/build.py <...> --print) --no-cache
```
in bash. This has the same effect

**Comment by jrussell9000** [comment]
Works for me! Thanks!!!
