### ISSUE TITLE
Updated Docker Image

### ISSUE THREAD

**Issue by B-Judge** [Deep-MI/FastSurfer#533]
Hey,

I was just wondering if you could make a newer Docker Image for gpu-latest so that it would include the addition of the SEGMENTATION PIPELINE --tal_reg option that was added after the last Docker Image creation?

Thanks!

**Comment by dkuegler** [comment]
Our docker images are always the release versions, which we extensively test. We are about to release a new version pretty soon, which will also include the hypothalamus subsegmentation (merged in dev yesterday).
