### ISSUE TITLE
Surface module fail in dev

### ISSUE THREAD

**Issue by minchulusa** [Deep-MI/FastSurfer#543]
## Description

I built the fastsurfer using naive install and run_fastsurfer only generates segmentation output and fails to generate surface.
## Steps to Reproduce

This is the command I used
./run_fastsurfer.sh --t1 /data/SKKUproject/KBSMC_example/3D_T1_brain/kbsmc_SS_3D_T1_TFE_SAG_20240612133806_601.nii --sd /data/SKKUproject/KBSMC_example/3D_T1_brain  --sid testVunoWorkstation   --py python3.10

FreeSurfer recon-all itself runs well and when I do 'bash rh.processing.cmdf', it also runs well.

### Execution

Run Command:  ./run_fastsurfer.sh --t1 /data/SKKUproject/KBSMC_example/3D_T1_brain/kbsmc_SS_3D_T1_TFE_SAG_20240612133806_601.nii --sd /data/SKKUproject/KBSMC_example/3D_T1_brain  --sid testVunoWorkstation   --py python3.10 

CPU:Intel(R) Xeon(R) w7-2495X
GPU:RTX A6000

I attached the recon-all.log

Many thanks

Minchul
[recon-all.log](https://github.com/user-attachments/files/16170106/recon-all.log)

**Comment by m-reuter** [comment]
Hi, we would need more information on this. First this seems to be a native install. Most of the time errors come from the fact that dependencies are different versions than what we use in our tested docker images. Furthermore, the problem starts earlier and the recon-all log is not helpful. Please provide: 

- what machine and operating system version are you using
- pip freeze (to see what dependencies you have)
- fastsurfer version (release version or are you using the dev branch which is not tested?)
- recon-surf.log file

I would also recommend to run this with our released docker or singularity image. If that fails we have an issue with fastsurfer or the quality of the input data. If that works it is a problem with your native install.

**Comment by minchulusa** [comment]
Thank you for the reply.

I am sorry that I used the  '-dev' branch. When I tested with 'stable' version, it worked fine. 
Although the HyppVINN is not incorporated yet..

I use Dell precision 5860 machine 
with Ubuntu22.04.

I attach the result of pip freeze, and recon-surf.log file

Many thanks
Minchul

[recon-surf.log](https://github.com/user-attachments/files/16185785/recon-surf.log)

[pip_freeze.txt](https://github.com/user-attachments/files/16185786/pip_freeze.txt)

**Comment by m-reuter** [comment]
I think it is not running the surfaces at all due to a problem with fs_time: 

> RUNNING lh sequentially ... 
>
> /data/SKKUproject/KBSMC_example/3D_T1_brain/testVunoWorkstation/scripts/lh.processing.cmdf
>
> fs_time [options] command args
> options:
>  -o outputfile : save resource info into outputfile
>  -k key
>  -l : report on load averages as from uptime
 
what is your bash version? We need to fix this before our release, as it works for you in stable. Thanks for reporting.

**Comment by minchulusa** [comment]
This is my bash --version

GNU bash, version 5.2.21(1)-release (x86_64-conda-linux-gnu)

I am also using with language 'Korean', just in case letting you know..

**Comment by dkuegler** [comment]
I think I have identified the bug. Thank you for reporting this. I will test (and commit) a fix in the hours.

**Comment by m-reuter** [comment]
Should work now in dev (I merged #545 ) . If not I can re-open this issue.
