### ISSUE TITLE
CerebNet support for submillimeter images?

### ISSUE THREAD

**Issue by Satob95** [Deep-MI/FastSurfer#550]
Hi,
I wanted to ask if there is some way for me to use CerebNet on natively submillimeter Scans? I've tried using it on 0.8mm Scans and it fails, I've also tried upsamplaing the scans to 1mm isotropic but Cerebnet still fails. By failing i mean the code still runs but the segmentations are incorrect (e.g. huge holes within one hemisphere or borders being cut-off). Do you have any ideas on how to preprocess/upsample natively high-res Images to 1mm so that Cerebnet works on them?

Best,
Sam

**Comment by dkuegler** [comment]
Fastsurfer should automatically upsample the 0.8 images to 1mm for you when you run with CerebNet. Running natively on sub-millimeter is obviously something we would like as well, but CerebNet is not trained for this and thus does not support this.

Can you post the logfile? `subjects_dir/subject_id/scripts/deep-sea.log`?

Also can you share the original image? CerebNet is trained on a smaller dataset than Fastsurfer and it might be the acquisition is too different.

**Comment by dkuegler** [comment]
One solution might be to run CerebNet on the bias field corrected image, if bias fields are too strong.

**Comment by m-reuter** [comment]
Closing this for now. Missing response by poster. Also native support for high-res in cerebnet is on our list, but not possible without high quality labels on such data, which we don't have at the moment. Downsampling should work already, unless acquisition or images are too different from our training images.
