### ISSUE TITLE
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by Ianyliu** [Deep-MI/FastSurfer#56]
Hi FastSurfer Team and others,

I am trying to use FastSurfer on a MacBook Pro carrying the Apple Silicon M1 chip. I've encountered 2 issues already specific to those using the Apple Silicon chip and resolved them (see previously posted issues), but this one seems like an issue just for Docker (see screenshot below). 

I have searched online already the returned error but all I got was that I was supposed install nvidia-container-toolkit via `sudo apt-get`. However, apt-get doesn't work on Mac as far as I know, and Homebrew does not have  nvidia-container-toolkit available to install. 

Regards, Ian L

<img width="1294" alt="Screen Shot 2021-07-11 at 3 07 11 PM" src="https://user-images.githubusercontent.com/37123262/125207323-adc0ea00-e259-11eb-9a84-fcf18c8a921d.png">

**Comment by m-reuter** [comment]
I think on Mac you can only use the CPU version.

**Comment by m-reuter** [comment]
If there is a way to get the nvidia-smi docker running on a Mac , it should also work with Fastsurfer. Until then I am closing this, and only the CPU version will work.
