### ISSUE TITLE
Issues Running FastSurfer on SLURM via Singularity (Missing srun_fastsurfer.sh and Directory Creation Errors)

### ISSUE THREAD

**Issue by xuansean** [Deep-MI/FastSurfer#580]
Hi FastSurfer Team,

I'm new to both FastSurfer and SLURM and am currently trying to run a single subject using the standard workflow via Singularity on SLURM. Upon inspecting the `.sif` image, it seems like the `srun_fastsurfer.sh` script is not included, even though the documentation suggests it should be part of the container.

I've tried bypassing this by mounting the `srun_fastsurfer.sh` from the directory on the cluster, but I encountered several issues that I couldn't fully understand (still learning how containers work). So, I moved forward by running the standard FastSurfer command using `singularity exec` without invoking `srun_fastsurfer.sh`. However, I encountered the following error:

```
[jhpce03 /dcs07/xuan/data/scripts/xuan]$ cat fastsurfer_test_9811619.out 
INFO: The subject directory did not exist, creating it now.
ERROR: directory creation failed
```
Below is my SLURM `sbatch` script for reference:
```
#!/bin/bash
#SBATCH --job-name=fastsurfer_test         # Job name
#SBATCH --output=fastsurfer_test_%j.out    # Output file (job ID in the name)
#SBATCH --error=fastsurfer_test_%j.err     # Error file (job ID in the name)
#SBATCH --time=12:00:00                    # Time limit (adjust as needed)
#SBATCH --mem=64G                          # Memory request
#SBATCH --cpus-per-task=16                 # Number of CPUs
#SBATCH --ntasks=1                         # Single task
#SBATCH --mail-type=END,FAIL               # Mail events (job finished or failed)
#SBATCH --mail-user=wangx23@students.ecu.edu  # Your email for notifications

module load singularity                    # Load Singularity module
module load freesurfer                     # Load FreeSurfer module

# Paths
T1_IMG=/dcs07/xuan/data/ukbiobank_bids/batch_1/sub-10005132025220/ses-01/anat/sub-10005132025220_ses-01_T1w.nii.gz
T1_IMG_DIR=$(dirname ${T1_IMG})  # Directory of the T1 image
OUTPUT_DIR=/dcs07/xuan/data/fastsurfer_output  # Output directory
WORK_DIR=/dcs07/xuan/data/fastsurfer_work      # Work directory
SINGULARITY_IMG=/dcs07/xuan/data/fastsurfer-gpu.sif  # Singularity image

# Use the correct license path
LICENSE_PATH=/jhpce/shared/jhpce/core/freesurfer/7.4.1/license.txt

# Ensure the work directory is clean before starting
rm -rf ${WORK_DIR}
mkdir -p ${WORK_DIR}
mkdir -p ${OUTPUT_DIR}

# Bind the T1 image directory and FreeSurfer license, and run FastSurfer
singularity exec -B ${T1_IMG_DIR}:/data/t1_images \
                 -B ${LICENSE_PATH}:/opt/freesurfer/license.txt \
                 ${SINGULARITY_IMG} /fastsurfer/run_fastsurfer.sh \
    --t1 /data/t1_images/$(basename ${T1_IMG}) \
    --sd ${OUTPUT_DIR} \
    --fs_license /opt/freesurfer/license.txt \
    --threads 16
```
Could someone please advise on:

1. Since srun_fastsurfer.sh is missing, what is the correct way to invoke it?
2. How to resolve the "directory creation failed" error during the standard execution? Also if I'm setting the work and output dir correctly?

Thanks for your help!

**Comment by m-reuter** [comment]
Hi, 
- you need write permissions in the output directory 
- srun is a script to orchestrate the slurm stuff so it needs to run outside the singularity image, just download it from GitHub

**Comment by dkuegler** [comment]
the srun_fastsurfer script is not supposed to be used from inside the container. It is theoretically designed to address the use case you are having, but you have to get a "full download" of Fastsurfer (either using git `git clone https://github.com/Deep-MI/FastSurfer`) or download [here](https://github.com/Deep-MI/FastSurfer/archive/refs/heads/stable.zip).

There is also soem help [here](https://deep-mi.org/FastSurfer/stable/scripts/SLURM.html).

Your script above does not work because you are trying to call fastsurfer inside the container with `--sd ${OUTPUT_DIR}`but `${OUTPUT_DIR}` was never mounted (`-B ${OUTPUT_DIR}:/output` and the `--sd /output`) to fix that.

**Comment by xuansean** [comment]
> the srun_fastsurfer script is not supposed to be used from inside the container. It is theoretically designed to address the use case you are having, but you have to get a "full download" of Fastsurfer (either using git `git clone https://github.com/Deep-MI/FastSurfer`) or download [here](https://github.com/Deep-MI/FastSurfer/archive/refs/heads/stable.zip).
> 
> There is also soem help [here](https://deep-mi.org/FastSurfer/stable/scripts/SLURM.html).
> 
> Your script above does not work because you are trying to call fastsurfer inside the container with `--sd ${OUTPUT_DIR}`but `${OUTPUT_DIR}` was never mounted (`-B ${OUTPUT_DIR}:/output` and the `--sd /output`) to fix that.

Thank you so much for your helpful response! It makes a lot more sense now and I've managed to successfully run my test subject using the standard run method. I've downloaded the srun_fastsurfer.sh script and tried it according to the documentation you provided + example 6. My cluster doesn't have $HPCWORK defined so I manually provided the workdir which I have write permission. However, my job failed with the following log:
```
Log of FastSurfer SLURM script
Tue, 24 Sep 2024 14:26:37 -0400
/dcs07/manno/data/fastsurfer_repo/srun_fastsurfer.sh --data /dcs07/manno/data/bids_test_batch/batch_1 --pattern sub-*/ses-01/anat/*_ses-01_T1w.nii.gz  

Neither --work nor $HPCWORK are defined, make sure to pass --work!

```
I did defined the path in my job submitting script:
```
#!/bin/bash
#some standard sbatch stuff omitted

# Load the required modules
module load singularity

# Paths
BATCH_DIR=/dcs07/manno/data/bids_test_batch/batch_1  # Test batch directory with multiple subjects
OUTPUT_DIR=/dcs07/manno/data/fastsurfer_output       # Output directory
WORK_DIR=/dcs07/manno/data/fastsurfer_work/test_batch1  # Work directory
SINGULARITY_IMG=/dcs07/manno/data/fastsurfer-gpu.sif  # Singularity image
FASTSURFER_SCRIPT_DIR=/dcs07/manno/data/fastsurfer_repo  # Directory containing srun_fastsurfer.sh
LICENSE_PATH=/jhpce/shared/jhpce/core/freesurfer/7.4.1/license.txt  # FreeSurfer license file

# Ensure the work and output directories are clean before starting
rm -rf ${WORK_DIR}
mkdir -p ${WORK_DIR}
mkdir -p ${OUTPUT_DIR}

# Run FastSurfer using srun_fastsurfer.sh
${FASTSURFER_SCRIPT_DIR}/srun_fastsurfer.sh \
    --data ${BATCH_DIR} \
    --pattern "sub-*/ses-01/anat/*_ses-01_T1w.nii.gz" \  # Pattern for all subjects in the batch
    --sd ${OUTPUT_DIR} \
    --work ${WORK_DIR} \
    --fs_license ${LICENSE_PATH} \
    --num_cases_per_task 1 \  # Adjust based on parallelism
    --num_cpus_per_task 16 \
    --singularity_image ${SINGULARITY_IMG} \
    --partition seg=GPU_partition,surf=CPU_partition \
    --debug  # Add --dry for testing without submitting \
    --dry

```
Despite defining the --work option, I still get the error regarding --work not being passed or $HPCWORK not being defined.

Could you kindly provide guidance on what might be missing or misconfigured here?

Thank you once again for your assistance!

**Comment by dkuegler** [comment]
So for block one, you are not passing an option for `--work` so it makes sense it is giving you that error.

Looking at block 2
```
#!/bin/bash
#some standard sbatch stuff omitted

# Load the required modules
module load singularity
```

All that is not needed. `srun_fastsurfer.sh` does all these things for you.

Just copy and run in the console (on the slurm login node) ***This BLOCK IS BROKEN, SEEE BELOW***:
```bash
BATCH_DIR=/dcs07/manno/data/bids_test_batch/batch_1  # Test batch directory with multiple subjects
OUTPUT_DIR=/dcs07/manno/data/fastsurfer_output       # Output directory
WORK_DIR=/dcs07/manno/data/fastsurfer_work/test_batch1  # Work directory
SINGULARITY_IMG=/dcs07/manno/data/fastsurfer-gpu.sif  # Singularity image
FASTSURFER_SCRIPT_DIR=/dcs07/manno/data/fastsurfer_repo  # Directory containing srun_fastsurfer.sh
LICENSE_PATH=/jhpce/shared/jhpce/core/freesurfer/7.4.1/license.txt  # FreeSurfer license file
${FASTSURFER_SCRIPT_DIR}/srun_fastsurfer.sh \
    --data ${BATCH_DIR} \
    --pattern "sub-*/ses-01/anat/*_ses-01_T1w.nii.gz"  # Pattern for all subjects in the batch \
    --sd ${OUTPUT_DIR} \
    --work ${WORK_DIR} \
    --fs_license ${LICENSE_PATH} \
    --num_cases_per_task 1  # Adjust based on parallelism \
    --num_cpus_per_task 16 \
    --singularity_image ${SINGULARITY_IMG} \
    --partition seg=GPU_partition \
    --partition surf=CPU_partition \
    --debug  # Add --dry for testing without submitting \
    --dry
```
Note the change to `--partition` and the position of the backslash in the `--pattern` and `--num_cases_per_task` lines.

You do not need to run `sbatch` yourself (`srun_fastsurfer.sh` does this for you) -- this is exactly the purpose of `srun_fastsurfer.sh`.

With the `--debug`flag set, you should also see if the script is able to find your cases/images.

**Comment by dkuegler** [comment]
Actually, that does not work at all... you cannot combine newlines and comments this way.... https://stackoverflow.com/questions/23591273/is-it-possible-to-use-comments-when-the-line-is-split-with-backslashes

```bash
BATCH_DIR=/dcs07/manno/data/bids_test_batch/batch_1  # Test batch directory with multiple subjects
OUTPUT_DIR=/dcs07/manno/data/fastsurfer_output       # Output directory
WORK_DIR=/dcs07/manno/data/fastsurfer_work/test_batch1  # Work directory
SINGULARITY_IMG=/dcs07/manno/data/fastsurfer-gpu.sif  # Singularity image
FASTSURFER_SCRIPT_DIR=/dcs07/manno/data/fastsurfer_repo  # Directory containing srun_fastsurfer.sh
LICENSE_PATH=/jhpce/shared/jhpce/core/freesurfer/7.4.1/license.txt  # FreeSurfer license file
${FASTSURFER_SCRIPT_DIR}/srun_fastsurfer.sh \
    --data ${BATCH_DIR} \
    --pattern "sub-*/ses-01/anat/*_ses-01_T1w.nii.gz" \
    --sd ${OUTPUT_DIR} \
    --work ${WORK_DIR} \
    --fs_license ${LICENSE_PATH} \
    --num_cases_per_task 1 \
    --num_cpus_per_task 16 \
    --singularity_image ${SINGULARITY_IMG} \
    --partition seg=GPU_partition \
    --partition surf=CPU_partition \
    --debug \
    --dry
```

**Comment by xuansean** [comment]
> Actually, that does not work at all... you cannot combine newlines and comments this way.... https://stackoverflow.com/questions/23591273/is-it-possible-to-use-comments-when-the-line-is-split-with-backslashes
> 
> ```shell
> BATCH_DIR=/dcs07/manno/data/bids_test_batch/batch_1  # Test batch directory with multiple subjects
> OUTPUT_DIR=/dcs07/manno/data/fastsurfer_output       # Output directory
> WORK_DIR=/dcs07/manno/data/fastsurfer_work/test_batch1  # Work directory
> SINGULARITY_IMG=/dcs07/manno/data/fastsurfer-gpu.sif  # Singularity image
> FASTSURFER_SCRIPT_DIR=/dcs07/manno/data/fastsurfer_repo  # Directory containing srun_fastsurfer.sh
> LICENSE_PATH=/jhpce/shared/jhpce/core/freesurfer/7.4.1/license.txt  # FreeSurfer license file
> ${FASTSURFER_SCRIPT_DIR}/srun_fastsurfer.sh \
>     --data ${BATCH_DIR} \
>     --pattern "sub-*/ses-01/anat/*_ses-01_T1w.nii.gz" \
>     --sd ${OUTPUT_DIR} \
>     --work ${WORK_DIR} \
>     --fs_license ${LICENSE_PATH} \
>     --num_cases_per_task 1 \
>     --num_cpus_per_task 16 \
>     --singularity_image ${SINGULARITY_IMG} \
>     --partition seg=GPU_partition \
>     --partition surf=CPU_partition \
>     --debug \
>     --dry
> ```

Thank you! I certainly didn't know that commenting would cause an issue and I have a much better understanding on how this script and slurm works in general.

I think I have one final obstacle that I have to overcome. I've removed the unnecessary lines but it still failed with the following log at end in the terminal output:
```
# discard the exit code of run_fastsurfer (exit with success), so following
# jobarray items will be started by slurm under the aftercorr dependency
# see https://github.com/Deep-MI/FastSurfer/pull/434#issuecomment-1910805112
exit 0
--- end of script ---
sbatch: error: invalid partition specified:  gpu
sbatch: error: Batch job submission failed: Invalid partition name specified
```
The only changes I made to the flags are the partition names. I believe based on the output above everything at the beginning like the directories and file patterns etc are correct.

I've confirmed with my slurm support team that 'gpu' is a valid partition name. Quoting what they said:

> One note, when using the gpu partition, you need to specify “--gpus=1” in order to request 1 GPU or use the “--gres” option to request a particular GPU. Without one of those options, you’ll be put on a GPU node, but won’t have a GPU assigned to you for use. You may need to reach out to the developer of FastSurfer to see if they have any thoughts.

I've looked at the content of the srun script and by default it allocates resource "--gpus=1" at line 605 which all I need to pass to srun is just the name of the partition.

I've also checked the availability of the partitions using sinfo before running it.

Logically speaking it doesn't make sense that I would get such an error. Do you have any possible clues? 
Once again I greatly appreciate your assistance and guidance!

**Comment by dkuegler** [comment]
Fastsurfer (`srun_fastsurfer.sh`) adds `--gpus=1` automatically (i think only if you'd add `--device cpu` this is not added, but I am not 100% on this). [edit: `srun_fastsurfer.sh` has a `--cpu_only` flag for this purpose.]

Looking at the error message it seems to me that you do not actually have a alarm partition called "GPU". But you can list partitions with `sinfo` (I believe).

For now, you can just remove the partition arguments and let your cluster manage the job assignment completely freely. Segmentation should then only get assigned to servers with gpus because those jobs "ask for" a GPU...

**Comment by xuansean** [comment]
The puzzling part to me is that I've used `sinfo` and 'gpu' indeed is valid with enough resource avaliable.
![Screenshot 2024-09-26 at 2 04 42 PM](https://github.com/user-attachments/assets/978880d6-e7f3-4c27-873e-66c88ad1ff7f)
My cluster support staff also confirmed this. 
I've tried removing the partition arguments by both:
1. remove both lines
2. change it to only one line `--partition shared \`

But removing both lines would give me `sbatch: error: Batch job submission failed: Requested node configuration is not available`
![Screenshot 2024-09-26 at 2 12 25 PM](https://github.com/user-attachments/assets/37f059c0-5f36-4d71-9143-6b2bbaebee88)

And second method would just give me the same error saying the name is invalid :/ 
Would you suggest that this is more of a problem about cluster configurations rather than the code we have?

**Comment by dkuegler** [comment]
It seems to not pick up the partition correctly. Also it seems to say there are no nodes with gpus in the poartition you selected

**Comment by dkuegler** [comment]
Also, it looks like a potential problem in srun_fastsurfer to me right now, but I cannot really recreate that issue right now since I have no slurm cluster to test on right now... i'll have a look tomorrow....

**Comment by xuansean** [comment]
> Also, it looks like a potential problem in srun_fastsurfer to me right now, but I cannot really recreate that issue right now since I have no slurm cluster to test on right now... i'll have a look tomorrow....

Thank you for the update! I appreciate you taking the time to look into this, and I look forward to any insights you might have tomorrow.

Would you prefer I continue the conversation here or start a new post?

**Comment by dkuegler** [comment]
This post is fine. I am not really sure what is happening yet. If I look at your debug output, it says you have not defined a partition at all yet. That really confuses me... 

Can you maybe run the script with `bash -x srun_fastsurfer.sh ...` this produces a lot of output, so you probably want to pipe it into a file like by adding `> mylogfile.log` at the very end and that can help me figure out why it is not selecting the correct partition but that does not really explain why it was not able to use the gpu partition earlier...

**Comment by xuansean** [comment]
[fastsurfer_debug.log](https://github.com/user-attachments/files/17156275/fastsurfer_debug.log)
Here you go.

I've also tested with a single line to see if slurm recognize the gpu partition with something very simple and it worked:
`sbatch --gpus=1 --mem=7G --cpus-per-task=16 --time=10 -p gpu --wrap="echo 'GPU test'"`

**Comment by dkuegler** [comment]
I think I may have found a BUG in the code of `srun_fastsurfer.sh` Unfortunately, I cannot really test this right now, because our SLURM cluster is down. But you can maybe download this file and check if it resolves your issue.

https://github.com/Deep-MI/FastSurfer/blob/b9e8b0cee8dfcd3485c898aef482d680f00e519c/srun_fastsurfer.sh

Cheers
David

**Comment by xuansean** [comment]
Thank you so much! I had to make one correction though:
`line 575: first_non_empty: command not found`

at line 575 and 672 I believe it should be `first_non_empty_arg`.

After that small change the jobs were able to submit:
![Screenshot 2024-09-27 at 10 45 28 AM](https://github.com/user-attachments/assets/0f2f91dc-a5f0-440f-9a99-866432084397)

A real quick side question though, my cluster have 17 GPUs(another 12 coming in a month or two) and daily usage is like below:
![Screenshot 2024-09-27 at 10 50 42 AM](https://github.com/user-attachments/assets/6f53b0d8-dc89-4754-9a96-cde7335fb7a4)

I have about 23000 subjects from ukbiobank, already grouped into 20 subjects per batch with roughly 1150 total batches. Based on the availability of the gpu and my grouping, what would you recommend for setting the `num_cases_per_task` and `num_cpus_per_task`? I think what I have already should be just fine since the segmentation is only a few minutes, but just want to see if you have any other suggestions. I'm thinking about iterate through 25 batches (500 subjects) to start with but could it be too much or no? (I don't want to overload the job arrays with more than a thousand jobs)

And finally thank you so much for all the help! Glad we caught an error and made fastsurfer better!

**Comment by dkuegler** [comment]
Num_cases_per_task is just a Parameter that splits the full subjects_list into groups of that number... So it would seem you already wanted that to be 20.
These would be processed sequentially for segmentation. I would expect roughly 5 minutes per case on one GPU, so 12*17~200 per hour... This will go fast.

I would choose num_cpus_per_task to at most the share of cores per gpu you have for that server, so for 32 cores and 2 gpus I would choose 16 num_cpus_per task maximum. I also think the benefits you get for more that 16 fall off... So much more than 16 also does not help much.

For the surface pipeline, srun_fastsurfer will only use 1 or 2 cores per parallel task (so depending on whether or not you specify --parallel).

**Comment by xuansean** [comment]
Alright. Thank you! Much appreciated 👍
