### ISSUE TITLE
Question: GPU Usage and Volume extraction 

### ISSUE THREAD

**Issue by garciadias** [Deep-MI/FastSurfer#6]
I am using the FastSurfer inside Docker example. As in the example, I used "--gpu all", to use both of mine GTX 1080Ti cards. However, monitoring the GPU usage I see no more than 5% of one GPU being used, [Screenshot with GPU and CPU usage](https://ibb.co/fG0Tmyq).

Also, how can I specify only volume extraction, ignoring the cortical thickness?

(Thank you for your great contribution to the community. Your article is very interesting and this tool will be of great use for many studies.)

**Comment by LeHenschel** [comment]
Hey,

I assume the segmentation also takes longer than 1 minute? There should also be some printout to the screen which looks like this:  Cuda available: True, # Available GPUS: 1, Cuda user disabled (--no_cuda flag): False, --> Using device: cuda
Is this set to cuda for you? 

Looking at the screenshot, my guess is that the problem is your CUDA Version (11.0). The Docker is currently set up for 10.0. You could change the Docker file to your version and see if the image works in that case.

Best,
Leonie

**Comment by zhangcc89claire** [comment]
hi,
Thank you for a wonderful job，while running locally, an error was reported as follows:
I have checked the .py file and found no specific reason for the error. Could you please tell me how to solve it?
Thanks very much.



#5 ./run_fastsurfer.sh: line 227: syntax error near unexpected token `&'

**Comment by m-reuter** [comment]
Hi, the flag for only volume processing has been added. We haven't heard back from OP about the Cuda printout and Cuda version change in docker. closing for now.

**Comment by garciadias** [comment]
Thank you for adding the tag. I will test the new version. I was testing different combinations of docker images with the installations of Cuda. Matching them didn't help. I even tried in a clean system and observed the same problem. Using images like oguzpastirmaci/gpu-burn I got 100% of usage on both GPUs, so I suspect this is not the problem.

**Comment by garciadias** [comment]
Hi Leonie,

I never got the "Cuda available: False, # Available GPUS: 0, Cuda user disabled (--no_cuda flag): False, --> Using device: cpu" output. The process is always frozen in the output I sent before. With the --no_cuda flag it runs ok.
I will try to test pytorch and let you know if I have any luck.

Thank you,

Rafael

**Comment by garciadias** [comment]
> Hey,
> 
> I strongly suspect, that pytorch does not recognize your GPUs in which case you will get an output like this (this might take some time, if the network runs on the CPU):
> 
> Cuda available: False, # Available GPUS: 0, Cuda user disabled (--no_cuda flag): False, --> Using device: cpu
> 
> You can also test this with just the FastSurferCNN docker.
> 
> I took a quick look at the oguzpastirmaci/gpu-burn image and it did not look like they are using pytorch for testing the GPUs. During the installation process for pytorch you have to select the correct CUDA version, otherwise even if your GPUs are available with e.g. nvidia-smi inside the image, pytorch will not correctly identify them.
> 
> Best,
> Leonie

Just of your information, running directly from the FastSurferCNN folder, I got the following output:

> Reading volume /home/rgd/git/ABIDEII-BNI-1/sub-29006/ses-1/anat/sub-29006_ses-1_acq-1_run-1_T1w.nii.gz
> Conforming image to UCHAR, RAS orientation, and 1mm isotropic voxels
> Input:    min: 0.0  max: 203.0
> rescale:  min: 0.0  max: 175.595  scale: 1.4522053589225206
> Loading Axial
> Successfully loaded Image from /home/rgd/git/ABIDEII-BNI-1/sub-29006/ses-1/anat/sub-29006_ses-1_acq-1_run-1_T1w.nii.gz
> Loading Sagittal
> Successfully loaded Image from /home/rgd/git/ABIDEII-BNI-1/sub-29006/ses-1/anat/sub-29006_ses-1_acq-1_run-1_T1w.nii.gz
> Loading Coronal.
> Successfully loaded Image from /home/rgd/git/ABIDEII-BNI-1/sub-29006/ses-1/anat/sub-29006_ses-1_acq-1_run-1_T1w.nii.gz
> Cuda available: True, # Available GPUS: 2, Cuda user disabled (--no_cuda flag): False, --> Using device: cuda

Still uses very little percentage of GPU capabilities.

**Comment by LeHenschel** [comment]
Hey Rafael,

hm, ok that is odd. Just to be clear - running the network this way does not produce any output for you (so it just freezes and you stop it after some time)?

Best,
Leonie

**Comment by garciadias** [comment]
> Hey Rafael,
> 
> hm, ok that is odd. Just to be clear - running the network this way does not produce any output for you (so it just freezes and you stop it after some time)?
> 
> Best,
> Leonie

Hi Leoni,

It stays frozen until I kill the job or shutdown the computer. The output folder is created, but it is empity.

Thank you for your help,

Rafael
