### ISSUE TITLE
Mask Value Meaning

### ISSUE THREAD

**Issue by nengwp** [Deep-MI/FastSurfer#60]
This is a beginner's question. I used FastSurferCNN for segmentation and got the segmentation result mask, but I could not know the name of the corresponding value of mask, please tell me where to find it.

**Comment by m-reuter** [comment]
Hi, you probably mean the label map with all the segmentation ids? The Ids are from the FreeSurfer Atlas. You can find their meetings here: 
https://github.com/freesurfer/freesurfer/blob/dev/distribution/FreeSurferColorLUT.txt 
Also when opening the MRI and the segmentation in FreeView, you can see the name of each structure and a color label, see this tutorial:
https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/AnatomicalROI

**Comment by nengwp** [comment]
Thank you very much for your quick and accurate answer as to whether there is a list of mappings in fastSurferCNN output results 0-79. Because I'm intercepting its unmapped data, and if it's not, I'm just going to read it from the program.

**Comment by nengwp** [comment]
Thank you very much for your quick and accurate answer as to whether there is a list of mappings in fastSurferCNN output results 0-79. Because I'm intercepting its unmapped data, and if it's not, I'm just going to read it from the program.

**Comment by m-reuter** [comment]
It would be better to work with the mapped results instead of the internal ids. FreeSurfer is a standard and the internal IDs are not.

**Comment by nengwp** [comment]
Thank you very much for your answer and I will take your advice。
