### ISSUE TITLE
Does FastSurfer produce a Talairach transformation matrix?

### ISSUE THREAD

**Issue by AdiH7ri** [Deep-MI/FastSurfer#614]
Hi, does the FastSurfer pipeline include automatic alignment to the Talairach space? Is yes, then is there an option to save the **Talairach transformation matrix**, or perhaps the AC-PC coordinates? 

/Aditya

**Comment by m-reuter** [comment]
Hi Aditya, 
sure it puts the talairach transform matrix at the same place as FreeSurfer `<caseid>/mri/transforms` . Also, just a heads up, we plan to add a corpus callosum module that also segments the AC and the PC directly in the image.

**Comment by m-reuter** [comment]
Also, if you add ` --tal_reg` it performs the Talairach registration already during the segmentation block, if you want to skip the surfaces with `--seg_only`. That way also the eTIV (estimated total intracranial volume) will be reported in the segmentation statistics files. Make sure you add `--3T` in case your data comes from a 3T scanner (it will use a better fitting atlas for the registration).

**Comment by AdiH7ri** [comment]
Got it. Thanks for the quick reply!
