### ISSUE TITLE
Can preprocessed T1w MRI images in nii or nii.gz formats as inputs of FastSurfer?

### ISSUE THREAD

**Issue by XinQi7788** [Deep-MI/FastSurfer#62]
Can **Gradwarp, B1 correction, N3, scaled T1w MRI images in nii or nii.gz formats** as inputs of FastSurfer?

Or it must be the original image without any preprocessing step, as indicted in the data requirement "--t1: T1 full head input (not bias corrected, global path). "?

Looking forward to reply. Thanks a lot.
Xin

**Comment by XinQi7788** [comment]
Follow the same question, can we use the ADNI preprocessed T1w MRI images in nii format as inputs of FastSurfer?

**Comment by m-reuter** [comment]
Hi, it should work well with adni. Also the other images should work, but you need to check quality.

**Comment by XinQi7788** [comment]
Thanks for your reply and information.
