### ISSUE TITLE
syntax error near unexpected token `&'

### ISSUE THREAD

**Issue by m-reuter** [Deep-MI/FastSurfer#7]
hi,
Thank you for a wonderful job，while running locally, an error was reported as follows:
I have checked the .py file and found no specific reason for the error. Could you please tell me how to solve it?
Thanks very much.

./run_fastsurfer.sh: line 227: syntax error near unexpected token `&'

_Originally posted by @zhangcc89claire in https://github.com/Deep-MI/FastSurfer/issues/6#issuecomment-653173687_

**Comment by m-reuter** [comment]
hi  @zhangcc89claire ,
this is a separate issue which is why I moved it here. 
Probably your bash is too old to understand the |& command (which was added in bash 4 I think). You can update your bash to a more recent version or replace all occurrences with the equivalent:
2>&1 |

**Comment by zhangcc89claire** [comment]
Thank you very much for your reply. I have checked bash and it is the
latest version as follows：



clairedeiMac:FastSurfer-master claire$ echo $BASH && echo $BASH_VERSION

/usr/local/bin/bash

5.0.17(1)-release


May I ask if there are other possible reasons that need to be investigated?




Martin Reuter <notifications@github.com> 于2020年7月3日周五 上午4:18写道：

**Comment by m-reuter** [comment]
Do you have a working FreeSurfer 6.0 install? 
What OS are you running on?

**Comment by LeHenschel** [comment]
Hey,

could you paste the exact command you tried to run? And which operating system you are using? I ran it on ubuntu 20.04 with bash 5.0.16(1)-release and could not replicate the error.

Thank you

**Comment by zhangcc89claire** [comment]
Thanks very much for your reply.My operating system is macOS High Sierra
10.13.6 (17G65)


The errors I encountered are as follows：



(base) clairedeiMac:~ claire$ echo $BASH_VERSION

5.0.17(1)-release

(base) clairedeiMac:~ claire$ export
FREESURFER_HOME=/Applications/freesurfer

(base) clairedeiMac:~ claire$ source $FREESURFER_HOME/SetUpFreeSurfer.sh

-------- freesurfer-Darwin-OSX-stable-pub-v6.0.0-2beb96c --------

Setting up environment for FreeSurfer/FS-FAST (and FSL)

FREESURFER_HOME   /Applications/freesurfer

FSFAST_HOME       /Applications/freesurfer/fsfast

FSF_OUTPUT_FORMAT nii.gz

SUBJECTS_DIR      /Applications/freesurfer/subjects

MNI_DIR           /Applications/freesurfer/mni

FSL_DIR           /usr/local/fsl

(base) clairedeiMac:~ claire$ cd
/Users/claire/Downloads/FastSurfer-masterdatadir=/Users/claire/Downloads/FastSurfer-master/my_mri_data




*./run_fastsurfer.sh --fs_license /Users/claire/Downloads/license.txt \*

*                    --t1
/Users/claire/Downloads/FastSurfer-master/my_mri_data/subject1/orig.mgz \*

*                    --seg
/Users/claire/Downloads/FastSurfer-master/my_fastsurfer_analysis/subject1/aparc.DKTatlas+aseg.deep.mgz
\*

*                    --sid subject1 --sd
/Users/claire/Downloads/FastSurfer-master/my_fastsurfer_analysis *




*./run_fastsurfer.sh:line 1: ﻿#!/bin/bash: No such file or director*

*./run_fastsurfer.sh: line 227: syntax error near unexpected token `&'*



Best,

Claire

LeHenschel <notifications@github.com> 于2020年7月3日周五 下午3:21写道：

**Comment by m-reuter** [comment]
Currently we do not support MacOS. You would have to use docker for now. Sorry.

**Comment by m-reuter** [comment]
Update: in our upcoming release we added support for Mac (Intel cpu-based and M Apple Silicon also GPU on mps device) for the segmentation. Furthermore, we updated install instructions (especially to update the bash shell) and modified recon-surf slightly in #198 to run through. We do not do any testing on the Mac, so you should inspect results.
