### ISSUE TITLE
Missing files when using mris_surf2surf after fastsurfer

### ISSUE THREAD

**Issue by vnckppl** [Deep-MI/FastSurfer#70]
After succesfully running FastSurfer v. I want to project fMRI BOLD data onto the surface models. For this, I have tried to use mris_surf2surf. It seems however that FastSurfer is not writing out the required files for the mapping. The log including the error message is as follows:

```
mri_surf2surf --srcsubject fastsurfer --srchemi lh --srcsurfreg sphere.reg --trgsubject fsaverage --trghemi lh --trgsurfreg sphere.reg --tval /datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00/fastsurfer/registration/tmp.mris_preproc.56185/fastsurfer.1.mgh --sval /datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00/fastsurfer/registration/tmp.mris_preproc.56185/subjsurfvals.mgh --noreshape --cortex
MRISread(/datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00/fastsurfer/surf/lh.sphere.reg): could not open file
Source registration surface changed to sphere.reg
Target registration surface changed to sphere.reg

$Id: mri_surf2surf.c,v 1.103 2015/11/05 22:07:33 greve Exp $

setenv SUBJECTS_DIR /datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00
cd /datadisk/Utah/Kladblok/20210623_AD_R01_add_on/20211007_SurfaceProjection
mri_surf2surf --srcsubject fastsurfer --srchemi lh --srcsurfreg sphere.reg --trgsubject fsaverage --trghemi lh --trgsurfreg sphere.reg --tval /datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00/fastsurfer/registration/tmp.mris_preproc.56185/fastsurfer.1.mgh --sval /datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00/fastsurfer/registration/tmp.mris_preproc.56185/subjsurfvals.mgh --noreshape --cortex 

sysname  Linux
hostname Tuxedo
machine  x86_64
user     vincent
srcsubject = fastsurfer
srcval     = /datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00/fastsurfer/registration/tmp.mris_preproc.56185/subjsurfvals.mgh
srctype    = 
trgsubject = fsaverage
trgval     = /datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00/fastsurfer/registration/tmp.mris_preproc.56185/fastsurfer.1.mgh
trgtype    = 
srcsurfreg = sphere.reg
trgsurfreg = sphere.reg
srchemi    = lh
trghemi    = lh
frame      = 0
fwhm-in    = 0
fwhm-out   = 0
label-src  = lh.cortex.label
label-trg  = lh.cortex.label
OKToRevFaceOrder  = 1
UseDualHemi = 0
Reading source surface reg /datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00/fastsurfer/surf/lh.sphere.reg
No such file or directory
mri_surf2surf: could not read surface /datadisk/tmp/20211018_ADNI_SurfProjectTest/sub-ADNI002S0413/ses-V00/fastsurfer/surf/lh.sphere.reg
No such file or directory
```

Is there an option in FastSurfer to generate the lh.sphere.reg and rh.sphere.reg files that are required for mris_surf2surf?

**Comment by vnckppl** [comment]
Thanks, that fixed it.

**Comment by Ede1994** [comment]
We have a similar problem and the sphere.reg (lh.sphere.reg and rh.sphere.reg) files are also there after the FastSurfer run (v2.2). However, we are now trying to map them with fsaverage Yeo annotation using mri_surf2surf. I think we have made a mistake and wanted to ask for help.

How exactly do I manage to register the FastSurfer Ouputs to the corresponding annotation (Yeo) in the FreeSurfer fsaverage folders, so that I get the volumes for exactly this annotation?

**Comment by m-reuter** [comment]
I have not yet tried that. It should work the same way as in FreeSurfer, do you know if they have any documentation how to do it?

**Comment by Ede1994** [comment]
I could not find any specific instructions for this. But I must also confess that I am increasingly confused about the individual FreeSurfer tools and how they work.

**Comment by m-reuter** [comment]
Yes, it is a very powerful toolbox and can be overwhelming if you move away from the core functionality. You can check the freesurfer mail archive https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/ and if nobody has asked this yet, you can ask their email list directly. Once you know how it is done in FreeSurfer it should work the same in FastSurfer, if not, ask again here.
