### ISSUE TITLE
this scriptdidn't process it

### ISSUE THREAD

**Issue by stu5** [Deep-MI/FastSurfer#8]
Hello,

I ran this script and didn't process it.  The results are empty.I don't know where the problem is, can you answer me?And  if I ran python ,I found that “killed" on the terminal.
Thanks!
![image](https://user-images.githubusercontent.com/53066495/86509880-d419a180-be1d-11ea-83cb-f0d759da60c9.png)
![image](https://user-images.githubusercontent.com/53066495/86509855-a6ccf380-be1d-11ea-8689-753b1a8ae21d.png)
![image](https://user-images.githubusercontent.com/53066495/86509888-e1369080-be1d-11ea-90ae-b8797e91f2db.png)
![image](https://user-images.githubusercontent.com/53066495/86509966-8b161d00-be1e-11ea-8acc-1e903745bccf.png)

**Comment by LeHenschel** [comment]
Hey, 

looks like a memory problem. You can try to reduce the batchsize (see here: #4)

Best,
Leonie

**Comment by m-reuter** [comment]
probably resolved, if setting batch size to 1 (or reducing it) did not fix it, we can re-open
