### ISSUE TITLE
Problem running hippocampus/amygdala segmentation pipeline on FastSurfer

### ISSUE THREAD

**Issue by mh1618** [Deep-MI/FastSurfer#83]
Hi all, 

A problem occurred when I tried to run the hippocampus/amygdala segmentation pipeline (segmentHA_T1.sh) on FastSurfer.
I got an error message saying

```
Cannot find wmparc.mgz or norm.mgz or talairach.xfm for the subject.
Has the subject been procesed with recon-all?
```
It doesn't help even if I put those 3 files in the mri folder (I tried rename wmparc.mapped.mgz to wmparc.mgz and moved talairach.xfm from transforms folder to mri folder), the same error occurs. 

Could you please help me with this issue? Thank you.

Steps/commands used to run FastSurfer:

# Run FastSurfer
./run_fastsurfer.sh --t1 ${T1_image} \
                    --sid ${sub}_FastSurfer --sd $ResultsDir \
                    --parallel --threads 8 > ${ResultsDir}${sub}_FastSurfer.out

# create link for aparc+aseg 

ln -sr ${ResultsDir}${sub}_FastSurfer/mri/aparc+aseg.orig.mgz ${ResultsDir}${sub}_FastSurfer/mri/aparc+aseg.mgz 

5ttgen hsvs ${ResultsDir}${sub}_FastSurfer/ ${ResultsDir}${sub}_5TT_hsvs.mif.gz -scratch ${ResultsDir}
5tt2vis ${ResultsDir}${sub}_5TT_hsvs.mif.gz ${ResultsDir}${sub}_5TTvis_hsvs.mif.gz

# Connectome Generation
aparc_aseg=${ResultsDir}${sub}_FastSurfer/mri/aparc+aseg.mgz
default_file=${root_path}FTDMND/fs_default.txt
freesurfer_LUT=/usr/local/freesurfer/FreeSurferColorLUT.txt
T1norm=${ResultsDir}${sub}_FastSurfer/mri/norm.mgz
labelconvert ${aparc_aseg} ${freesurfer_LUT} ${default_file} ${ResultsDir}${sub}_nodes.mif.gz -force

# # # 4. Replace FreeSurfer’s estimates of sub-cortical grey matter structures with estimates from FSL’s FIRST tool
labelsgmfix ${ResultsDir}${sub}_nodes.mif.gz ${T1norm} ${default_file} ${ResultsDir}${sub}_nodes_fixSGM.mif.gz  \
-premasked \
-sgm_amyg_hipp \
-scratch ${ResultsDir} \
-force

**Comment by m-reuter** [comment]
Hi, 
only the wmparc.mgz should be missing (unless you run FastSurfer with the --fsaparc where it should get created using the slower FreeSurfer approach). However, it should be sufficient to just create a symbolic link to the mapped version:
`ln -s wmparc.mapped.mgz wmparc.mgz`

**Comment by mh1618** [comment]
> Hi,
> only the wmparc.mgz should be missing (unless you run FastSurfer with the --fsaparc where it should get created using the slower FreeSurfer approach). However, it should be sufficient to just create a symbolic link to the mapped version:
> `ln -s wmparc.mapped.mgz wmparc.mgz`

Thanks so much for the clarification, I appreciate it :)
