### ISSUE TITLE
aparc.a2009s+aseg

### ISSUE THREAD

**Issue by githubcooperation** [Deep-MI/FastSurfer#89]
Hi all, 
 when I  got the result of fastsurfer, I want to use it to run postsurferpipeline but I find that the postsurferpipeline needs file,  aparc.a2009s+aseg.mgz .However, there is no file named aparc.a2009s+aseg.mgz in the result of fastsurfer. So should I do to resolve this question 
thank you for your help
maylin

**Comment by LeHenschel** [comment]
Hey Maylin,

by default, we only return the DKTatlas (see also #51 ). You can get the resulting segmentations by adding the --fsaparc flag. Alternatively, if you already ran the recon-surf pipeline including the --surf-reg option, you can create the a2009s segmentation using FreeSurfer commands:

```
cd $SUJECTS_DIR/<subjid>/mri

mris_ca_label -l ../label/?h.cortex.label -aseg aseg.presurf.mgz <subjid> ?h ?h.sphere.reg $FREESURFER_HOME/average/?h.destrieux.simple.2009-07-29.gcs ../label/?h.aparc.a2009s.annot

mri_aparc2aseg --s <subjid> --volmask --annot aparc.a2009s --aseg aseg.presurf.hypos --a2009s
```

Hope this helps.

Best,
Leonie

**Comment by githubcooperation** [comment]
Hi Leonie,
thank you for your answer. I have solved this question by using your method. However, I have met another question which there is no file named aparc+aseg.mgz. The result of fastsurfer contains a file named aparc+aseg.orig.mgz. I want to know what is difference between the two files. Can I replace the former with the latter? 
Best,
Matlin

**Comment by githubcooperation** [comment]
> Hey Maylin,
> 
> by default, we only return the DKTatlas (see also #51 ). You can get the resulting segmentations by adding the --fsaparc flag. Alternatively, if you already ran the recon-surf pipeline including the --surf-reg option, you can create the a2009s segmentation using FreeSurfer commands:
> 
> ```
> cd $SUJECTS_DIR/<subjid>/mri
> 
> mris_ca_label -l ../label/?h.cortex.label -aseg aseg.presurf.mgz <subjid> ?h ?h.sphere.reg $FREESURFER_HOME/average/?h.destrieux.simple.2009-07-29.gcs ../label/?h.aparc.a2009s.annot
> 
> mri_aparc2aseg --s <subjid> --volmask --annot aparc.a2009s --aseg aseg.presurf.hypos --a2009s
> ```
> 
> Hope this helps.
> 
> Best, Leonie

Hi Leonie,
thank you for your answer. I have solved this question by using your method. However, I have met another question which there is no file named aparc+aseg.mgz. The result of fastsurfer contains a file named aparc+aseg.orig.mgz. I want to know what is difference between the two files. Can I replace the former with the latter?
Best,
Maylin @ClePol @LeHenschel

**Comment by LeHenschel** [comment]
Hey Maylin,

no, the two are different. The aparc+aseg.orig.mgz is the segmentation we return with FastSurfer which is based on the DKTatlas (31 labels per hemisphere ; paper: https://www.frontiersin.org/articles/10.3389/fnins.2012.00171/full). The aparc+aseg.mgz is based on another atlas (Desikian, 35 parcels per hemisphere; paper: https://www.sciencedirect.com/science/article/abs/pii/S1053811906000437?via%3Dihub). The DKTatlas is basically an adaptation thereof where four labels (bankstss (1001, 2001), corpus callosum (1004, 2004), frontal pole (1032, 2032), and temporal pole (1033, 2033)) have been merged with other labels. You can create the aparc+aseg.mgz (Desikian atlas) the same way as the a2009s (either running FastSurfer with --fsaparc or using the FreeSurfer commands):

```
cd $SUJECTS_DIR/<subjid>/mri

mris_ca_label -l ../label/?h.cortex.label -aseg aseg.presurf.mgz <subjid> ?h ?h.sphere.reg $FREESURFER_HOME/average/?h.curvature.buckner40.filled.desikan_killiany.2007-06-20.gcs ?h.aparc.annot

mri_aparc2aseg --s <subjid> --volmask --aseg aseg.presurf.hypos
```
Best,
Leonie

**Comment by githubcooperation** [comment]
Hey Leonie,
I am sorry that I have not recalled you for a long time. I am very grateful that you can give me some methods to resolve my questions. However, When I ran postfreesurfer, I got the result of this process. I find that the result of using t2w to assist with fastsurfer segment T1 is incorrect. So I want to know whether fastsurfer can not process T2-weighted images.(the first image is the result of fastsurfer, and the second image is the result of freesurfer)
Best,
Maylin @ClePol @LeHenschel
![100307 structuralQC wb_scene1](https://user-images.githubusercontent.com/48356035/146700037-daadb22a-8f44-4422-aae1-6fe467559a4e.png)
![100307 structuralQC wb_scene1](https://user-images.githubusercontent.com/48356035/146700151-97dc690d-002c-4ce1-9512-8bfc43e81318.png)

**Comment by LeHenschel** [comment]
Hey Maylin,

yes, at the moment fastsurfer only uses the T1 to generate the surfaces. The pial is not corrected with the T2 like it is possible in FreeSurfer. I am not sure what kind of postprocessing you are doing, but if you only need the surfaces on the T2 image, this is a simple registration of the T2 to the T1 image (as you can see by the comparison between FreeSurfer and FastSurfer). 

Best,
Leonie

**Comment by githubcooperation** [comment]
> Hey Maylin,
> 
> yes, at the moment fastsurfer only uses the T1 to generate the surfaces. The pial is not corrected with the T2 like it is possible in FreeSurfer. I am not sure what kind of postprocessing you are doing, but if you only need the surfaces on the T2 image, this is a simple registration of the T2 to the T1 image (as you can see by the comparison between FreeSurfer and FastSurfer).
> 
> Best, Leonie

Hey Leonie,
I am grateful for you can help me solve my question again. As you mentioned that the fastsurfer does not use T2-weighted image, however, I want to instead of the freesurfer's roles in the HCP pipelines using fastsurfer , So what should I do to process T2-weighted image. By the way, I find handling T2 is an optional operation for Freesurfer. The following image shows the commands for the optional process. I want to insert this optional process into fastsurfer, what should I do?
![freesurfer截图](https://user-images.githubusercontent.com/48356035/147066924-986ac1be-4fac-4f06-9d3b-11ab17a9f2d9.png)

**Comment by m-reuter** [comment]
Hi Maylin, 
as Leonie mentioned, currently the recon-surf script cannot use the T2 for surface correction. We can leave this issue open as a feature request for the future. In the past we had mixed results when using the T2 (it was cropping into the cortex in some places). This may be resolved in newer FS versions (or not). So we will not implement this for the current version of FastSurfer which is based on FreeSurfer 6.0. 

If you want to try yourself, you need to look at an actual FreeSurfer log file and at recon-all to make sure what steps are really done. Sometimes the Wiki (your screenshot) is missing some details or flags. If you are only interested in thickness maps, the above steps should be enough, but if you want thickness ROIs measures and also use the improved surface for updating the aseg, then you need to run all steps that come after this again, once you have the T2-corrected surfaces. We cannot support you for this.

**Comment by m-reuter** [comment]
In fact, because this issue is not only on the T2 feature request, but originally had a different topic, I will close it .Feel free to open a feature request separately.

**Comment by Ouzaixin** [comment]
Hi Leonie,

I want to ask how can I get DK segmentation file, because I need the bankssts.


> Hey Maylin,
> 
> no, the two are different. The aparc+aseg.orig.mgz is the segmentation we return with FastSurfer which is based on the DKTatlas (31 labels per hemisphere ; paper: https://www.frontiersin.org/articles/10.3389/fnins.2012.00171/full). The aparc+aseg.mgz is based on another atlas (Desikian, 35 parcels per hemisphere; paper: https://www.sciencedirect.com/science/article/abs/pii/S1053811906000437?via%3Dihub). The DKTatlas is basically an adaptation thereof where four labels (bankstss (1001, 2001), corpus callosum (1004, 2004), frontal pole (1032, 2032), and temporal pole (1033, 2033)) have been merged with other labels. You can create the aparc+aseg.mgz (Desikian atlas) the same way as the a2009s (either running FastSurfer with --fsaparc or using the FreeSurfer commands):
> 
> ```
> cd $SUJECTS_DIR/<subjid>/mri
> 
> mris_ca_label -l ../label/?h.cortex.label -aseg aseg.presurf.mgz <subjid> ?h ?h.sphere.reg $FREESURFER_HOME/average/?h.curvature.buckner40.filled.desikan_killiany.2007-06-20.gcs ../label/?h.aparc.annot
> 
> mri_aparc2aseg --s <subjid> --volmask --aseg aseg.presurf.hypos
> ```
> 
> Best, Leonie

**Comment by m-reuter** [comment]
try running with `--fsaparc` and you should get all the surface segmentations (also DK, which will be in the same files as in FreeSurfer aparc+aparc... and aparc stats).

**Comment by Ouzaixin** [comment]
It seems that these files are still referring to DKT not DK. 

![image](https://github.com/user-attachments/assets/3d309642-22d5-4ca1-8413-e4522c74bb19)


> try running with `--fsaparc` and you should get all the surface segmentations (also DK, which will be in the same files as in FreeSurfer aparc+aparc... and aparc stats).
