### ISSUE TITLE
recon-all "No such file or directory" error

### ISSUE THREAD

**Issue by zhengyangwang** [Deep-MI/FastSurfer#9]
Hi,

I was running the full pipeline on a T1 weighted nii image in docker. During recon-surf the error below occurred. 

mri_pretess done

#--------------------------------------------
#@# Fill Mon Jul  6 08:27:41 UTC 2020
/output/subject2/mri

 mri_fill -a ../scripts/ponscc.cut.log -xform transforms/talairach.lta -segmentation aseg.auto_noCCseg.mgz wm.mgz filled.mgz 

logging cutting plane coordinates to ../scripts/ponscc.cut.log...
INFO: Using transforms/talairach.lta and its offset for Talairach volume ...
using segmentation aseg.auto_noCCseg.mgz...
reading input volume...done.
searching for cutting planes...voxel to talairach voxel transform
 1.27551  -0.07937   0.10293  -45.56485;
 0.09484   1.40723   0.08887  -90.22624;
-0.12391   0.53786   2.07099  -235.68204;
 0.00000   0.00000   0.00000   1.00000;
voxel to talairach voxel transform
 1.27551  -0.07937   0.10293  -45.56488;
 0.09484   1.40723   0.08888  -90.22624;
-0.12391   0.53786   2.07099  -235.68204;
 0.00000   0.00000   0.00000   1.00000;
reading segmented volume aseg.auto_noCCseg.mgz...
Looking for area (min, max) = (350, 1400)
area[0] = 57 (min = 350, max = 1400), aspect = 0.85 (min = 0.10, max = 0.75)
need search nearby
using seed (112, 161, 56), TAL = (16.0, -72.0, -33.0)
talairach voxel to voxel transform
 0.77559   0.05945  -0.04110   31.01771;
-0.05612   0.71816  -0.02803   55.63380;
 0.06098  -0.18296   0.48768   101.20889;
 0.00000   0.00000   0.00000   1.00000;
segmentation indicates cc at (112,  161,  56) --> (16.0, -72.0, -33.0)
done.
could not find lh seed point around (139, 162, 107)
talairach cc position changed to (16.00, -72.00, -33.00)
Erasing brainstem...done.
seed_search_size = 9, min_neighbors = 5
search rh wm seed point around talairach space:(34.00, -72.00, -33.00) SRC: (111.19, 164.41, 104.80)
search lh wm seed point around talairach space (-2.00, -72.00, -33.00), SRC: (139.11, 162.39, 106.99)
No such file or directory
Linux 94f1d98586a7 5.3.0-61-generic #55~18.04.1-Ubuntu SMP Mon Jun 22 16:40:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s subject2 exited with ERRORS at Mon Jul  6 08:27:46 UTC 2020

For more details, see the log file /output/subject2/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Command exited with non-zero status 1
@#@FSTIME  2020:07:06:08:23:53 recon-all N 7 e 233.58 S 2.63 U 230.30 P 99% M 1129484 F 1097 R 1036284 W 0 c 835 w 1836 I 259416 O 4064 L 1.27 1.80 2.19
@#@FSLOADPOST 2020:07:06:08:27:46 recon-all N 7 1.09 1.40 1.93

It looks like a freesurfer-specific issue. I wonder if there is any way I can diagnose it.

Thank you,
Zhengyang

**Comment by LeHenschel** [comment]
Hey Zhengyang,

first thing you could try is to just rerun the whole fastsurfer command and see if the error persists as well as visually check if the the inputs (aseg.auto_noCCseg.mgz, wm.mgz, filled.mgz) look ok. In case you are aloud to share the image with me, I can also check if it runs through here.

Best,
Leonie

**Comment by zhengyangwang** [comment]
Hi Leonie,

Thanks for the reply!
Rerunning the pipeline gave the same exact results.
It turned out to that the specific brain had some highly pathological anatomies and the segmentation results were simply weird. I suspect that was the reason for subsequent errors because running with a template file instead gave me good results.
On a irrelevant note, running the default "recon-surf.sh" with the "--nofsaparc" argument seems to not not generate the "T1.mgz" file in the "mri" folder which is required by BrainStorm3 for importing anatomy. Adding the following 2 lines after line 409 seems to do it for me.

cmd="mri_normalize -g 1 -mprage $mdir/nu.mgz $mdir/T1.mgz" 
RunIt "$cmd" $LF


Cheers,
Zhengyang

**Comment by LeHenschel** [comment]
Hey Zhengyang,

ok, thank you for the update. We do not include the T1.mgz in FastSurfer's output because as far as I know it is only needed within FreeSurfer's recon-all for the brainmask generation which we get directly from the segmentation. You are of course welcome to adopt your script to your purposes :).

Best,
Leonie

**Comment by neurosignal** [comment]
**FreeSurfer version:** 
freesurfer-linux-ubuntu20_x86_64-7.3.2-20220804-6354275

**Error:**
`amit3@dell7770:~/Downloads/fs_tmp$ nice recon-all -subject $SUBJECT -i /home/amit3/Downloads/sub-0014_T1w.nii.gz -autorecon-all `     
nice: 'recon-all': No such file or directory

**Solution:** Most likely, you need to install csh and tcsh. Do it as: 
`sudo apt-get install csh tcsh`

It worked for me.

**Comment by 573-pankaj** [comment]
> 

it worked for me :  " sudo apt-get install csh tcsh " to solve the problem recon-all command not find . Thank you so much

**Comment by m-reuter** [comment]
yes, csh and tcsh are dependencies of FreeSurfer and should be automatically installed if you install their packaged version (e.g. here is a description for Ubuntu in WSL: https://surfer.nmr.mgh.harvard.edu/fswiki/FS7_wsl_ubuntu?highlight=%28tcsh%29 ). They should, however, add this information for people who install the tar.gz packages ( https://surfer.nmr.mgh.harvard.edu/fswiki//FS7_linux ).
