### ISSUE TITLE
disturbing wmparc labels comment in recon-surf

### ISSUE THREAD

**Issue by mishaberegov** [Deep-MI/FastSurfer#93]
I happen to notice the following comments in the  `recon-surf.sh` file:

```
 -wmparc based on mapped aparc labels (from input seg) (1min40sec) needs ribbon and we need to point it to aparc.mapped:
   labels are messed up, due to the aparc mapped surface labels which are incorrect, we need a lookup above.
```

  
  I wonder if the warnings are still valid.
  If so, is there any way to obtain the correct labels?

**Comment by m-reuter** [comment]
Hi, 
labels should be fine, so probably this is a left-over from some early debugging stage where label-ids were different and did not match what was expected here. We will take a closer look in two weeks and can then probably remove this comment.

**Comment by mishaberegov** [comment]
Thank you for the answer! I appreciate your work on this tool.

**Comment by m-reuter** [comment]
I keep this open until we checked this.

**Comment by m-reuter** [comment]
removed the comment.
