### ISSUE TITLE
Issues with --sid flag in run_fastsurfer.sh

### ISSUE THREAD

**Issue by andlampa** [Deep-MI/FastSurfer#94]
## Question/Support Request

... When running the `run_fastsurfer.sh` command as exemplified in the tutorial section, I get this error message :
-> ERROR: Flag 140 unrecognized.
Not sure what is causing this problem or how to solve it.

## Environment
 - FastSurfer Version: Local Install fastsurfer_gpu  with conda, latest version
 - FreeSurfer Version: v6.0
 - OS: Linux Ubuntu 21.10 -> running on VM 

Input/Output Path
```
input=/home/andre/fastsurfer/Tutorial/data/140_orig.mgz
output=/home/andre/fastsurfer/Tutorial/output
```

### Anaconda3 Packages
[Anaconda3_Packages.txt](https://github.com/Deep-MI/FastSurfer/files/7765409/Anaconda3_Packages.txt)

### Execution

Run Command: 
```
$FASTSURFER_HOME/run_fastsurfer.sh --t1 $input \
                                   -sd $outputDir \
                                   --sid 140 \
                                   --seg_only

```

**Comment by m-reuter** [comment]
The sd flag should be with two hyphens:
--sd 
Let us know if this is wrong in any of the README examples or tutorials (file and line number if possible).

**Comment by andlampa** [comment]
Hello, 
Sorry, when passing the command i erased the hyfen somehow
original code is:
```
$FASTSURFER_HOME/run_fastsurfer.sh --t1 $input \
                                   --sd $outputDir \
                                   --sid 140 \
                                   --seg_only
```
The error is ocurring in --sid i think.

**Comment by m-reuter** [comment]
ok, have you tried giving it a non-numerical name? E.g. --sid subject_140 , could be that it has a problem with the integer value.

**Comment by andlampa** [comment]
Yes, same error occurs:
`ERROR: Flag subject_140 unrecognized.`

**Comment by LeHenschel** [comment]
Hey,

this is an error that occurs only if you directly copy paste from the google colab. It seems, like the formatting is changed such that the hyphens are not actually hyphens leading to the observed error. If you type the command manually, it should work (e.g. if I copy the command you posted above, it works for me. If I copy the one from the colab directly, I get the same error)

Works:
```bash
$FASTSURFER_HOME/run_fastsurfer.sh --t1 $input \
                                   --sd $outputDir \
                                   --sid 140 \
                                   --seg_only
```
Best,
Leonie

**Comment by andlampa** [comment]
Hello Leonie,

That was the problem indeed, the command is running fine now, thank you.
