### ISSUE TITLE
Brain Stem sub-region labels support

### ISSUE THREAD

**Issue by johnccshen** [Deep-MI/FastSurfer#97]
Hi team,

Thanks for the great work for FastSurfer. It's fascinating and easy to use. 
I have followed the tutorial and ran several cases on my machine. 
While comparing to Freesurfer 6, I found that FastSurfer does not support subregions of the brain stem (Midbrain, pons, medulla).
Is there any flag that I can use the generate the subregions of brain stem?

Great Thanks
ccshen

**Comment by m-reuter** [comment]
Hi ccshen, 

Thanks. 
The brain stem sub-regions (similar to other sub-regions, e.g. hippocampus) are not part of the regular FreeSurfer pipeline and therefore also not of FastSurfer.  We haven't tested this, but probably you can create them using FreeSurfer after Fastsurfer is done via:
`recon-all -s bert -brainstem-structures`
see also https://surfer.nmr.mgh.harvard.edu/fswiki/BrainstemSubstructures

**Comment by johnccshen** [comment]
Thanks for replying efficiently!!! Really appreciated it. 
I will try the solution.
