### ISSUE TITLE
Docker version stops early

### ISSUE THREAD

**Issue by immcdonough** [Deep-MI/FastSurfer#98]
## Question/Support Request
I am using the Docker version of FastSurfer and tried testing it on a single subject. It seems to load in a t1.nii.gz image fine but after the "Axial model loaded." message appears in the terminal, nothing else happens.

## Screenshots
![image](https://user-images.githubusercontent.com/20742375/148843907-33185399-2cb3-48c1-87fa-9162184b70c8.png)

## Environment
 - OS: Mac OS X 10.12.6
 
### Execution

Built it using:
```bash
cd ..
docker build --rm=true -t fastsurfer:cpu -f ./Docker/Dockerfile_CPU .
```
Ran it using:
```bash
docker run -v /Users/ianmcdonough/Documents/HABS/T1_Baseline:/data \
           -v /Users/ianmcdonough/Documents/HABS/fastsurfer_analysis:/output \
           -v /Users/ianmcdonough/Documents/fs_license:/fs60 \
           --rm --user 502 fastsurfer:cpu \
		   --t1 /data/P_0Q2B9K/T1.nii.gz \
		   --fs_license /fs60/.license \
		   --no_cuda \
           --sid P_0Q2B9K --sd /output \
           --parallel
```

**Comment by m-reuter** [comment]
Maybe not enough memory inside docker? See #49 ?

**Comment by immcdonough** [comment]
That fixed it! Thank you!
